### ISSUE TITLE
Permission column?

### ISSUE THREAD

**Issue by PiyushXCoder** [lxqt/pcmanfm-qt#1012]
I'm using Arch Linux. A day back I switched from lxde-gtk3 to lxqt. I found that two of the very helpful features are missing. Please add them.

##### Missing Features
First: Permissions column in list view as you can see in pcmanfm-gtk3 it is there.
Here is link to images. Please guide how I can add permissions column is its already there
https://imgur.com/a/nvqngjZ

Second: In list view, menu of parent folder should be shown when right-clicked on any column other than Name. Sorry if I'm not clear. 
Here is link to images. 
https://imgur.com/a/WV5Wv1V

##### System Information
* Distribution & Version: Arch
* Kernel: 5.3.1.arch1-1
* Qt Version:  5.13.1-2
* libfm-qt Version: 0.14.1-1
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 0.14.1-1

**Comment by tsujan** [comment]
> First: Permission column is very useful if you're a developer

"rwxr-xr-x" is an ugly string that could be confusing for the average user. And if you're a developer or advanced user, you won't need it in that place.

> If you think its not useful for many users...

I don't think for other users. They might tell us about their opinions.

> Second: Do you really think its a design problem.

Yes, as I said already. Each row is about a single file. Right clicking its different places and showing different menus is a design flaw.

**Comment by agaida** [comment]
@PiyushXCoder - you might be surprised - we are developers too and never missed both things - otherwise we had implemented it, nor we get any bug about these things are missed before. Might show the importance for others - and we get countless senseful bugs for pcmanfm-qt and libfm-qt in the past years. File permissions might be implemented if one will write an explicit feature request - priority wishlist or minor and not visible by default. Tbh, i would care more about acl's and such things - but these permissions are not easy to make visible in a file browser.

@tsujan - i had a look at thunar - and we could really make some additional rows available, hidden by default. Btw. i fully agree with the "design fault" thing and about the fuglyness of some rows.

@PiyushXCoder - and we don't sell pink ponies. So if you want anything special nobody is interested in or don't want to implement - we accept good PR's.

**Comment by tsujan** [comment]
> @tsujan - i had a look at thunar - and we could really make some additional rows available

Please discuss that at https://github.com/lxqt/pcmanfm-qt/issues/1013

I close this cluttered report; @PiyushXCoder likes to play with emojis here.

**Comment by PiyushXCoder** [comment]
😅Its isn't ugly, its helpful. I'm not so advanced dev that I can predict file's permissions 😂😂😂. 🤨 System logs look uglier than rw-rw-rw. Why don't you understand they are  important features for a file manager. I've been using pcmanfm and lxde for years. You're hurting my loyalty. 😞I feel bad that pcmanfm is loosing its legacy. Our favourite pcmanfm is now pcmanfm-qt. 

Please, will you help me? Can you please make a patch for them 🤗🤗. Don't include them in repo. 😅I'm noob in c++.

**Comment by cladelpino** [comment]
+1 for permissions column...

**Comment by PiyushXCoder** [comment]
> +1 for permissions column...
> 
> Other requests for this feature resulting in change of file explorer, as it will in my case https://askubuntu.com/questions/72991/how-to-make-pcmanfm-to-display-the-column-permissions-in-detailed-view-lubun

I respect your opinion but I don't think they will implement this feature of us.
Not to offend but developers here are little rude. You may use thunar as explained at askubuntu. Maybe if you wish, you may look for something better as xfce. :) Consistent and stable

**Comment by RandomErrorMessage** [comment]
Simple feature and useful feature, wont be implemented because GNOME-eseque "users don't actually want this, despite you saying you want this".
