### ISSUE TITLE
Excessive padding for mounted devices labels

### ISSUE THREAD

**Issue by eligt** [lxqt/pcmanfm-qt#1018]
Labels for mounted devices have a large amount of empty space to the right of the unmount icon which does not seem to serve any purpose other than making so the labels are very short, often just 1 letter long. 

The fact that the ellipsis at the end of the labels take the space of 3 characters is also unnecessary, maybe using the ellipses Unicode character (…) could further alleviate this issue.

##### Expected Behavior
Labels for drives should be readable, otherwise they're not usable.

##### Current Behavior
Labels for drives are cut short.

##### Steps to Reproduce (for bugs)
![user_002](https://user-images.githubusercontent.com/2043211/65957688-63d09080-e445-11e9-9146-f89c29502dec.jpg)

##### System Information
* Distribution & Version: Lubuntu 19.04
* Package version: 0.14.1

**Comment by tsujan** [comment]
What's in Lubuntu may not be the real pcmanfm-qt because the real app doesn't and has never had such an issue:

![real_pcmanfm-qt](https://user-images.githubusercontent.com/981076/65962429-807cc080-e465-11e9-8676-53a28549f4d0.png)

**Comment by tsujan** [comment]
On second thought, Lubuntu may not be the culprit. You could move the splitter to the right; it'll remember its position.

> unmount icon which does not seem to serve any purpose

If it didn't have any prpose, it wouldn't be there.

> maybe using the ellipses Unicode character

You might want to report that to Qt.

**Comment by eligt** [comment]
I obviously meant that the padding has no purpose, the icon definitely has one :)

Moving the splitter leaves the icon in the middle of the column and still a lot of padding to the right.

**Comment by tsujan** [comment]
I don't know what patches Ubuntu has applied to the source(s) but what your screenshot shows isn't reproducible here. I tested with Breeze and the eject button was never so much to the left.

**Comment by tsujan** [comment]
> I obviously meant that the padding has no purpose, the icon definitely has one :)

Sorry for my misunderstanding! Since there is no padding here, I thought you meant the icon.

**Comment by tsujan** [comment]
Reopening for further investigation because it may be related to the shortest volume name. In the reporter's screenshot, it's "sw" and "OS", while my mounted volumes have long names.

**Comment by tsujan** [comment]
OK, I find time to experiment and succeeded in reproducing the issue by changing my font to Noto Sans 13. This screenshot is taken with Breeze but the widget style makes no difference:

![eject_column](https://user-images.githubusercontent.com/981076/66002125-d6765600-e4af-11e9-9e77-a1e19d557be7.png)

Apparently, `QTreeView::setColumnWidth` doesn't work as expected: Qt sets the width of the eject button to a value greater than what we set in our code and considers the font size in its calculation, so that the bigger the font is, the wider the eject button column becomes.

This seems like a nasty Qt bug because there's no text beside the eject button. We need to find a workaround for it

**Comment by tsujan** [comment]
The workaround is here: https://github.com/lxqt/libfm-qt/pull/477. The problem may have started with Qt 5.11.

**Comment by eligt** [comment]
Great job! Thanks for investigating and finding a fix so quickly.

**Comment by tsujan** [comment]
Thanks for reporting an sorry that I didn't see the problem at first..
