### ISSUE TITLE
Custom Action multiple files

### ISSUE THREAD

**Issue by kodkuce** [lxqt/pcmanfm-qt#1039]
[Desktop Entry]
Type=Action
Name=ZIP
Icon=zip
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=all/all;
Exec=7z a %f.7.zip %F
Name=Default profile
SelectionCount==1

When i use this in old pcmanfm it shows even if i select multiple files , but in pcmanfm-qt it wont show if i select more then 1 file

##### Expected Behavior
Show custom action on right click when select more then 1 file

##### Current Behavior
It dose not show :(

##### Possible Solution
Duno

##### Steps to Reproduce (for bugs)
add zip.desktop entry to  ~/.local/share/file-manager/actions/

##### Context
i just want to have right click zip files, default commpress dosent work with xarchiver form what i see

##### System Information  
* Distribution & Version: Void linux
* Kernel: 5.3.9_1
* Qt Version: qt5-5.13.2_1 
* libfm-qt Version: libfm-qt-0.14.1_1
* libqtxdg Version: libqtxdg-3.3.1_3
* lxqt-build-tools Version:  am not building form source
* Package version: pcmanfm-qt-0.14.1_2

**Comment by tsujan** [comment]
You've explicitly set `SelectionCount` to 1 and expect it to show with more than one file?!

> When i use this in old pcmanfm it shows even if i select multiple files

Then, the old pcmanfm has a bug.

**Comment by kodkuce** [comment]
sorry, duno if i am wrong, but when i put SelectionCount=2(or delete it) to test it it just run same command but on separate files and i got 2 zip/archives instead one and i kinda dont get whats the point of %F ?

Duno i dident find anywhere a man for SelectionCount pls correct me if i am wrong

**Comment by tsujan** [comment]
`SelectionCount==2` is ignored because its syntax is wrong. `SelectionCount==2` would mean only 2 files; `SelectionCount=>2` would mean more than 2 files; etc. The first `=` doesn't count.

Lack of `SelectionCount` or a wrong syntax for it means any number of files.

For a comprehensive documentation see: https://github.com/lxqt/pcmanfm-qt/files/3274222/Desktop.file.specification.extension.-.Actions.zip

Unfortunately, Gnome has removed that article from Internet (perhaps, because Gnome3 devs have found it too complex for their codes -- I don't know) but pcmafm-qt follows most of the rules that are explained in the above-mentioned documentation.

**Comment by tsujan** [comment]
At some point, we should write a help doc for pcmanfm-qt. Contributions are welcome. (See https://github.com/lxqt/pcmanfm-qt/issues/550).

**Comment by kodkuce** [comment]
This manual really helps, about contribution cant promise anything atm am stuffed with work, anyway thank you for help and sorry for posting invalid issue

**Comment by tsujan** [comment]
> and sorry for posting invalid issue

No need to be sorry. I searched the Internet after your comment and found NOTHING on the first page of google! Luckily, I'd downloaded the doc years ago.

Without a help, several important capabilities of pcmanfm-qt will remain hidden from users.
