### ISSUE TITLE
[Feature request] Moving/copying should continue, despite interaction needed

### ISSUE THREAD

**Issue by ceever** [lxqt/pcmanfm-qt#1049]
##### Expected Behavior
When moving/copying files, the process should continue with the "unproblematic" files and queue any required interactions (overwrite, rename, etc.) meanwhile, until the user is ready to act. This would save time later, when the copying was still going on and the user was not looking at it.

##### Current Behavior
When moving/copying files, the process stops if files exist in the destination folder and a window asks for interaction (overwrite, rename, etc.). This wastes time especially when the user continues working on something else while the moving/coping is (supposedly) going on in the background.

##### Possible Solution
Create a queue for all interactions and continue with the "unproblematic" files.

##### Steps to Reproduce (for bugs)
1. Open pcmanfm-qt 
2. Select a file
3. Press CTRL+C
4. Press CTRL+V

##### Context
I believe this would make LXQT a more useful desktop environment and more efficient for every days work.

##### System Information
* Distribution & Version: Ubuntu Focal 19.10
* Kernel: 5.3.0.1003.4
* Qt Version: 5.12.4+dfsg-1
* libfm-qt Version: 0.14.1-9ubuntu3
* libqtxdg Version: 3.3.1-0ubuntu3
* lxqt-build-tools Version: 0.6.0-2ubuntu1
* Package version: 0.14.1-0ubuntu2

**Comment by tsujan** [comment]
Thanks for the clean report!

We use GLib for file management and I'm not sure if it's possible or resource-friendly to queue overwrites but I'll look into it.

I haven't checked other file managers; do you know of any that does so?

**Comment by tsujan** [comment]
This is a good idea but, after I gave it some thought, its probable drawbacks started to appear to me.

The reason is that all files should be processed *before* knowing which ones need prompts. Suppose that you want to copy 50,000 files, of which 10,000 files should be overwritten. The copy job won't know that until it processes all 10,000 files (after copying 40,000) and *only then*, it starts to prompt the user. That means a needless delay and, of course, extra resource usage. The more the number of files, the more the delay.

IMO, making it optional doesn't seem like a good option either because it needs lots of other changes.

That being said, when I find the time. I'll test it to know whether the delay or resource usage is really serious or just a theoretical consideration.

**Comment by agaida** [comment]
Learn from Windows - "Repeat for all ..."

**Comment by tsujan** [comment]
Have no Windows and don't know what you mean by  "Repeat for all ..."

What is wanted here is logically impossible. Counterexample: Copying 1000 folders, the first one has 1000 files *and* needs to overwrite *and* some of its contents exist in the destination too. If the overwrite prompt of the first folder comes last (which is possible by changing the code), there will still be overwrite prompts for its contents at the end because its contents can't be processed before it. So, we'll have an overwrite prompt in the middle (= that of the first folder).

I close this. Open another report about "Repeat for all ..." if it's good and we don't have it.

**Comment by tsujan** [comment]
And we have "Apply this option to all existing files" as well as "Ignore".

**Comment by ceever** [comment]
Hi there,

sorry I couldn't answer earlier. This feature request was closed faster than I thought. So, I will try to answer some of your questions, which hopefully clarify what was intended.

1. There are 3 ways to achieve this enhancement:
 a.) Scan source and destination before copying/moving, match and ask user for interaction (while already starting coping/moving all non-critical files).
 b.) Start copying/moving and ask user for interaction when necessary, continuing copying/moving and gathering further conflicts in the background. In case user chooses a "apply to all" action, all following conflicts are treated accordingly.
 c.) While copying/moving delay all conflicts are put to the end of the queue, and ask for interaction when there are no non-critical files left.
I was aiming for the option b.)
2. Remember that the source directory is consistent. So, there is no reason why a conflict should arise from the order of files processed, the waiting for the user input, etc. Actually, 1. c.) is the thought experiment that could be done to justify the workings of such an enhancement. However, of course, 1. b.) is the more efficient solution for the user.
3. So, to answer your first concern. The process does not have to know ahead which are the conflicting files, it will encounter them on the way and ask the user for interaction. (As it is done currently, isn't it? I do not quite know the current workings though.) Copying/moving always continues (in the background or foreground) for all non-critical files. Any further conflicts are queued and treated when the user is ready.
No need for any waiting.
4. Regarding your counterexample. Sure, all file overwrites for the first folder have to wait queuing until I you know what the user wants to do with this folder. However, this is not different from the current situation. The advantage of the enhancement though is, that beneath the other 999 folders, there are maybe 900 folders which do not exist in the destination and can already start copying/moving. Furthermore, as soon as the user treats the first duplicate folder with "apply to all", all further folder actions are known and the process will only look for file conflict now and queue them, for user interaction.

Does that make sense?

Cheers

**Comment by tsujan** [comment]
Please read https://github.com/lxqt/pcmanfm-qt/issues/1049#issuecomment-568594709 again. The decision about contained files depends on the decision about overwriting their containing folder. We can't get the file info for 1000 files before knowing whether it will be needed because that would be a waste of resources. And don't forget that "1000" was just an example and that each of those files can be a folder containing many (1000) files. It's simply impractical.

> The process does not have to know ahead which are the conflicting files, it will encounter them on the way and ask the user for interaction.

Incorrect. Think about my example again.

**Comment by ceever** [comment]
Yes, I understand. But this example is just one case where the new process would be identical to the old one. But as soon as we know what we do with that folder, the new process supersedes the old because now we are on file level again.

And again as I said, we do not have to know anything ahead. The idea is that as soon as the user decides what to do with that folder, the decisions will stack up, but not before.

**Comment by tsujan** [comment]
> But this example is just one case

No, it can cover so many cases. Folders are as valid as files.

> And again as I said, we do not have to know anything ahead.

And, as I said, we do ;)

Actually, I started to implement it when I saw your report because I found the idea interesting but, as soon as I encountered directories in the code, it was obvious that the full implementation would be possible only if we didn't care about resources used by unneeded file info jobs (but we do care).

**Comment by ceever** [comment]
Sure, but I can probably think of many cases where it would work fine. And I assumed in the weird folder case, it would just be as "low efficient" as it is currently implemented.

Also, actually I for myself never do complex folder copies, because I do not know whether overwriting means deleting the whole target folder or just potentially duplicate files. Unfortunately, every file browser behaves different in this sense. Some are even broken and creating a folder inside of a folder of the same name (you know "cp -r folder folder/").
Hence, I wonder how many other people actually trust the file browsers logic or understand what it mean if a folder is overwritten by a folder ... I doubt many. 🤷

Either way, I was just thinking of how to improve day to day work, i.e. instead of staring at the copying/moving process for any interaction to show up, to instead spend time on something else. But I really do no know the current process, so it might actually be impossible.

It is just so strange that we still have a copying/moving process in place that behaves like 30 years ago and was never made more efficient or useful, like the intended background continuation, clever queuing for several copying/moving windows, or anything else that is consistent with the old way but provides great improvement if the user is happy to accept them.

Thanks anyway! 👍

**Comment by tsujan** [comment]
When an idea isn't implemented in any good program I've encountered, I think either (1) no one has considered it yet, or (2) they've considered but found it impractical. I've seen many cases of (1) but I'm afraid (2) may be the case here.

However, I'll keep the current idea in mind.
