### ISSUE TITLE
Set shortcuts for view mode and show/hide sidebar

### ISSUE THREAD

**Issue by glpzzz** [lxqt/pcmanfm-qt#1052]
Set shortcuts for view mode and show/hide sidebar

##### Expected Behavior
Press shortcuts to change view modes and show/hide sidebar

##### Current Behavior
to change view modes: the buttons beside address bar
to show/hide sidebar: drag the separator to the left, till collapse it

##### Possible Solution
Ctrl + 1...2...3...4 for view modes
F9 for show/hide sidebar (as in other filemanagers)

**Comment by tsujan** [comment]
Acceptable.

I'll do it later because pcmanfm-qt might need a shortcut editor -- should find the most frugal way.

**Comment by glpzzz** [comment]
So, it's not so simple as setting shortcuts for this actions? I see your comment on the file dialog :thinking: Interesting and more tricky that I thought

**Comment by tsujan** [comment]
In a complex program, sometime, a change that seems complicated can be done easily; sometimes, a simple change needs more than meets the eye (see this for an example of the latter: https://github.com/lxqt/libfm-qt/commit/b80d3eb9c21a633dbf108dc678ab7c7f8b73540b) 

Should get my hands dirty to know what is what...

**Comment by tsujan** [comment]
OK, I knew that this was discussed before...

There is a simple problem: lack of free shortcuts — and we don't want complex shortcuts, as far as possible.

As I'd mentioned [elsewhere](https://github.com/lxqt/pcmanfm-qt/issues/558#issuecomment-320438238), `Ctrl+1,2,3,...` is used for switching tabs. `Alt+` can't be used either because it's taken by tab switching too (in the code, if `Alt` is present, it'll be used; otherwise, `Ctrl` will). `Ctrl+fx` changes desktop with KWin. `Meta` is never a good modifier for default shortcuts; etc.

Only `F9` may be acceptable for showing/hiding the side-pane. However, I'm not sure we want to hide the side-pane because it's too important for file management.

So, I think we should NOT add more shortcuts. Instead, if a shortcut editor is made for pcmanfm-qt, the user could add his/her custom shortcuts.

As for the shortcut editor, I'm not sure whether it's a good idea either because, with it, the shortcuts  of all actions of a window should be checked before it's shown. The delay may be negligible but that's a discussion for another time.

IMO, this can be closed but I'll keep it open for a while to see if devs/users have practical suggestions.

**Comment by glpzzz** [comment]
Very well explained. The only thing I don't understand is why have to sets of shortcuts for the same action: change tabs. Which of the two (Alt or Ctrl) is more popular for changing tabs? Use the other to change view mode. 

Hiding the sidebar makes sense to me specially when using the split view. 

The absence of this shortcuts just cuts the workflow for keyboard centric users. 

On January 3, 2020 2:06:51 AM GMT-05:00, tsujan <notifications@github.com> wrote:
>OK, I knew that this was discussed before...>
>>
>There is a simple problem: lack of free shortcuts — and we don't want
>complex shortcuts, as far as possible.>
>>
>As I'd mentioned
>[elsewhere](https://github.com/lxqt/pcmanfm-qt/issues/558#issuecomment-320438238),
>`Ctrl+1,2,3,...` is used for switching tabs. `Alt+` can't be used
>either because it's taken by tab switching too (in the code, if `Alt`
>is present, it'll be used; otherwise, `Ctrl` will). `Ctrl+fx` changes
>desktop with KWin. `Meta` is never a good modifier for default
>shortcuts; etc.>
>>
>Only `F9` may be acceptable for showing/hiding the side-pane. However,
>I'm not sure we want to hide the side-pane because it's too important
>for file management.>
>>
>So, I think we should NOT add more shortcuts. Instead, if a shortcut
>editor is made for pcmanfm-qt, the user could add his/her custom
>shortcuts.>
>>
>As for the shortcut editor, I'm not sure whether it's a good idea
>either because, with it, the shortcuts  of all actions of a window
>should be checked before it's shown. The delay may be negligible but
>that's a discussion for another time.>
>>
>IMO, this can be closed but I'll keep it open for a while to see if
>devs/users have practical suggestions.>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/lxqt/pcmanfm-qt/issues/1052#issuecomment-570484463

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tsujan** [comment]
> The only thing I don't understand is why have to sets of shortcuts for the same action

It's PCMan's design. We don't want to change these things.

> Hiding the sidebar makes sense to me specially when using the split view.

Understood.
