### ISSUE TITLE
Option to make "preserve folder settings" recursive

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1056]
It would be nice being able to set for example for all ~/pictures/year/month directories the same sorting order and view mode (here thumbnails), just hitting  in "pictures" the  "preserve settings for this  folder" option, having also  checkbox "include subfolders".

##### Expected Behavior

Just select also "include subfolders" the same setting will be applied to all sub folders
##### Current Behavior

If one would like to have the same setting for the sub folders it has to be done one by one.
Ideally this setting should also be respected by newly created directories, but this is not a must, one would have just to repeat the setting.

**Comment by tsujan** [comment]
I think it was proposed but rejected because of its probable resource usage (no limit to nested folders) and new subfolders that might be created later. But let's think about it again... It doesn't seem elementary but is worth reconsidering.

**Comment by stefonarch** [comment]
KDE used the approach with a hidden file in each directory, pcmanmf-qt could use wildcards?
```
~/.config/pcmanfm-qt/lxqt/dir-settings.conf
....
[/home/user/pictures/*]
SortOrder=ascending
SortColumn=mtime
ViewMode=thumbnail
ShowHidden=false
SortFolderFirst=true
SortCaseSensitive=false
SortHiddenLast=false

```

**Comment by tsujan** [comment]
> KDE used the approach with a hidden file in each directory

That was a bad approach we decided to avoid from the start. Only the custom icon and list of virtually hidden files (not supported by KDE, I think) are defined in files because they can be independent of all file managers.

> pcmanmf-qt could use wildcards?

I was thinking about something similar: an option for inheriting settings from a parent (parent of parent, parent of parent of parent,...) folder, unless the folder is explicitly customized. But there's a considerable probability that it might make changing directories slower -- which we don't want at all.

Another way is adding all current subfolders to the list, with the settings of the parent folder. Later, the user could change each setting if needed. Newly created subfolders will be ignored. A reasonable limit can also be set for the number of subfolders.

But these are only thoughts without codes...

**Comment by tsujan** [comment]
Back to this, just to explain the existing possibilities:

 1. `libfm-qt` has two ways of customizing a folder: (a) from a single config file (usually, `~/.config/pcmanfm-qt/lxqt/dir-settings.conf`); or (b) by creating the file `.directory` inside the folder (this method isn't used anywhere and *is limited to folders that are owned by the user*).
 2. Recursive customization is possible by using (b): the `.directory` files can be created inside all subfolders.
 3. Since a folder may contain too many subfolders, the recursive customization will need a progress dialog, so that the user could stop/cancel it.
 4. Non-native folders and those not belonging to the user should be skipped.
 5. A recursive removal of customization will also be needed, with its progress dialog.
 6. All this needs a well-thought-out GUI design (where should new options appear and how?).

So, it's quite possible but it isn't a piece of cake.

**Comment by stefonarch** [comment]
As for the GUI I think an sub-item "Include also subfolders" under "Preserve settings for this folder" would do, unchecking should then also delete all [.directory](url) files. Maybe also having a  hint about "this can take some time" in the tooltip.

As feature it would be useful I think: a view mode for documents, another for images, and so on.

My "foto" directory counts 435 subfolders.

**Comment by tsujan** [comment]
> Maybe also having a hint about "this can take some time" in the tooltip.

A progress dialog are a must. The user may check it unintentionally inside a folder with thousands of subfolders. Although it's rare, it isn't impossible. Also, some subfolders may be remote mounts (like google-drive), in which case, the process will be slow.

**Comment by tsujan** [comment]
> unchecking should then also delete all .directory files

I'm afraid it couldn't do that. It could only empty `.directory` files. As far as I remember, Dolphin leaves `.directory` files too. That's one of the reasons we don't use those files by default.

**Comment by tsujan** [comment]
> My "foto" directory counts 435 subfolders.

Oh, that made me reevaluate the situation.

Suppose that 435 `.directory` files are made. The main problem just starts: if you change any view setting inside the parent folder, the change should be written to 435 files. Like Qt, GLib creates temporary files when writing to config files. So, 435 temporary files should be created and deleted. That will cause a freeze after each click on a view action.

Even if we create a single `.directory` file and copy it into all subfolders (`libfm-qt` doesn't do so), we'll still experience nasty freezes.

If we don't create `.directory` files and do everything in the central config file, every directory change will be slow (not just inside the "foto" folder) because each directory change should be checked against so many entries inside the central config file.

I had high hopes ;) Now I think it isn't practical — at least not with the available methods.

**Comment by stefonarch** [comment]
Good point, but sad... maybe some idea will show up later. 
Setting a default view for image folders  isn't pratical too, as darktable for example has an .xml file for each raw file.

**Comment by tsujan** [comment]
> maybe some idea will show up later

Yes. I keep it open.

**Comment by tsujan** [comment]
Found a very simple way:

An option is added to Preferences; it says something like, "Apply custom folder settings recursively".

Suppose that the option is checked. Then, on changing the directory, the folder is first examined against the list of custom folders in `~/.config/pcmanfm-qt/lxqt/dir-settings.conf`, as usual. If a match is found, it'll accept the customization — again, as usual. If not, its parent folders will also be examined, starting from the first parent, then the second, then the third, etc. If a match is found, the folder in question will accept the customization of that parent.

I tested it and it worked fine. It's advantage is that not only it's fast but also it works with newly created folders. However, there are two problems:

 * I don't have a deep hierarchy of subfolders. So, I don't know what happens inside a deep hierarchy. Does it remain fast?
 * There's a logical problem too. If the user sees that a folder has a customized appearance, he mmight not know from which parent folder it inherits that cusstomization — until he goes up and up.

**Comment by stefonarch** [comment]
Cool!
I think a very deep hierarchy is  rare, but we could make a test using a script that creates one.
For the second I think this is acceptable IMO.

The difference now is that this applies to _all_ preserved views. Would it be possible that this is on by default and it activates only when a "apply recursively" option is checked in the parent folder?

**Comment by tsujan** [comment]
> Something like... Recursive=true

I don't know; maybe. An additional key needs an additional reading, which means an extra usage of the resources. But I'll look into it.

For now, there are details that surfaced only when I started to use it. For example, "Preserve Settings for This Folder" shouldn't be checked by for inherited customization because, otherwise, we could do nothing when it's unchecked by the user (but if it's checked by the user, we could switch to the original customization for that folder); etc.

I'll wrestle with problems in my free time. I think we're going in the right direction...

**Comment by tsujan** [comment]
OK, I found the following solution for all problems. It may seem complex in words but I think everything is self-explanatory in the GUI. I'll test it for a while before making an experimental PR (a draft).

Folders can have three kinds of view settings *(the third one is new)*:

 1. The default settings (= no customization);
 2. Customized settings; and
 3. Settings that are inherited from one of their parent directories.

(2) can have 2 forms *(the second one is new)*:

 **a.** Customized settings only for the current folder; or
 **b.** Recursively Customized settings (for the current folder and all of its sub-folders).

There are separate checkable menu items for (a) and (b). The user can check only one of them or neither.

(3) gets its meaning from (b): If a folder has no custom settings itself but is a child of a recursively customized folder, it inherits its settings from it.

The GUI shows an extra menu item for (3): "Go to Source of Inherited Settings". This item appears only when the current folder has an inherited look. If it's clicked, the directory will be changed to the recursively customized parent folder, so that the user will know from where the look of the original folder is inherited.

All menu items of customized view settings (three) are moved to a submenu.

**Comment by stefonarch** [comment]
Sounds really good, thanks! 
Waiting for your PR to test :)
