### ISSUE TITLE
add additional x-scheme-handlers

### ISSUE THREAD

**Issue by wxl** [lxqt/pcmanfm-qt#1067]
As a continuation of discussion at lxqt/libfm-qt#519, the idea is to add additional `x-scheme-handlers` to our Desktop Entry so that when using `Type=Link` Desktop Entries, the URIs appropriate to `pcmanfm-qt` make use of it.

##### Possible Solution

Looking to what Gvfs and KIO support, I suggested:
 * `afc`
 * `afp`
 * `cdda`
 * `fish`
 * `ftp`
 * `mtp`
 * `nfs`
 * `sftp`
 * `smb`

**Comment by tsujan** [comment]
I add that this isn't limited to `Type=Link`. For example, `smb` links (e.g., in FeatherPad) could be opened by pcmanfm-qt too.

**Comment by tsujan** [comment]
Clash with web browser should be taken into account. For example, Falkon and Chromium open `ftp`; so, IMO, `x-scheme-handler/ftp` shouldn't be added to pcmanfm-qt's desktop file — the user could assign it if needed . This problem can be solved by checking desktop files of well-known browsers.

**Comment by tsujan** [comment]
With https://github.com/lxqt/lxqt-config/pull/635, several schemes are added to `lxqt-config-file-associations` (more could be added if requested and other enhancements will be possible) and the user can associate them with pcmanfm-qt.

But, on second thought, I think we shouldn't add the above-mentioned schemes to pcmanfm-qt's desktop file. Well-known file managers (like Dolphin) don't do so because, as I mentioned in my previous comment, clashes are possible.

The situation is like that of text editors: a text editor needs to include only `text/plain` in its desktop file, although the user can also associate lots of other mimetypes to it, e.g. HTML, XML, MHTML,...

All in all, I think we should follow other file managers in this regard.

Sorry for the confusion I may have caused!
