### ISSUE TITLE
HiDPI rendering problems

### ISSUE THREAD

**Issue by KAMiKAZOW** [lxqt/pcmanfm-qt#1082]
See

![Screenshot_20200223_230150](https://user-images.githubusercontent.com/3259076/75121480-a153e580-5694-11ea-982c-0a182fd796e5.png)

##### System Information
* Distribution & Version: openSUSE TW
* Kernel: 5.5.4
* Qt Version: 5.14.1
* libfm-qt Version: 0.14.1

cc @guoyunhe

**Comment by tsujan** [comment]
pcmanfm-qt doesn't control HDPI. Qt and icon engine does.

You've used Oxygen, which doesn't work well with non-integer scale factors under KDE either. Use Breeze instead.

However, with non-integer scale factors, some Breeze icons aren't as sharp as they are with integer scale factors. That seems to be a Qt problem because it happens under KDE too.

**Comment by tsujan** [comment]
This may also be about https://github.com/lxqt/libqtxdg/issues/178. I'll try to fix it soon (before the next release).

**Comment by KAMiKAZOW** [comment]
> pcmanfm-qt doesn't control HDPI. Qt and icon engine do.

Under Linux each application must explicitly enable HiDPI support. It has always been that case ever since HiDPI support was introduced mid-cycle to Qt5. That's why https://github.com/lxqt/pcmanfm-qt/blob/master/pcmanfm/pcmanfm.cpp#L10 exists (but currently has no effect).

**Comment by tsujan** [comment]
@KAMiKAZOW You didn't read my last comment.
