### ISSUE TITLE
multiple wayland bugs

### ISSUE THREAD

**Issue by unmellow** [lxqt/pcmanfm-qt#1083]
##### Expected Behavior
I run pcmanfm-qt with QT_QPA_PLATFORM=wayland
and it works both as root and as a normal user

##### Current Behavior
if i run pcmanfm-qt with QT_QPA_PLATFORM=wayland
i can't open my right click menu or open a sub menu via clicking on eg
the "file" or "edit" buttons
also no matter what i set QT_QPA_PLATOFORM too
i can't get pcmanfm-qt to run as root on wayland
i have the same issue with pcmanfm but nemo works fine
i havent tried running as root on an x window manager

##### Possible Solution
i have no idea sorry

##### Steps to Reproduce (wayland incompatible)
1. launch a wayland window manager
2. enter "export QT_QPA_PLATFORM=wayland" into a terminal
3. run pcmanfm-qt from terminal
4. right click pcmanfm-qt or clcik a submenu opening button

##### Steps to Reproduce (can't run as root)
1. launch a wayland window manager
2. set or unset QT_QPA_PLATFORMTHEME to whatever you want
3.run pcmanfm-qt as root
4.it doesn't start if you set QT_QPA_PLATFORMTHEME=wayland you get this error
"QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0"
manually chowning /run/user/1000 to be owned by root removes that error but pcmanfm-qt still doesn't start

##### Context
i want to open folders that can only be opened by root

##### System Information

* Distribution & Version:  manjaro (has no versions i beleave)
* Kernel: 
* Qt Version: 5.14.1-1,  4.8.7-29.1
* libfm-qt Version:0.14.1-1
* libqtxdg Version: 3.4.0-3
* lxqt-build-tools Version: not installed
* Package version: 0.14.1-1

**Comment by unmellow** [comment]
i was gonna report this to the pcmanfm guys but i'm not making a source forge to submit one issue

**Comment by tsujan** [comment]
> right click pcmanfm-qt or clcik a submenu opening button

Right click menu and submenus are OK.

If you're under Weston, use:
```
 QT_QPA_PLATFORM=wayland-egl pcmanfm-qt
```
or simply 
```
pcmanfm-qt -platform wayland
```
Under KWin Wayland, you don't need to do anything.

> run pcmanfm-qt as root

Who told you that you could run a root Wayland instance? He/she lied to you ;)

**Comment by unmellow** [comment]
i am using sway and i just tested it again and menu's only work if i set QT_QPA_PLAFORM=""
witch default's to xcb
also i'm not trying to run Wayland as root just my file manager how else am i supposed to access 
folders i don't have read access to?

**Comment by tsujan** [comment]
> i am using sway

Then, you could report it to sway.

> also i'm not trying to run Wayland as root just my file manager

It's the same.

> how else am i supposed to access folders i don't have read access to?

I assure you that we (LXQt team) aren't Wayland developers. That question -- among many -- is for them to answer; they might say, "use XWayland for root."

**Comment by unmellow** [comment]
you were right about the menu thing after restarting my pc i can't reproduce the bug 
also i can't find any other qt file manager that supports runing as root on wayland so i'll just use nemo

**Comment by tsujan** [comment]
I forgot to tell you that, a year ago, I'd tried sway and, as far as I remember, under it, Qt apps didn't need any command-line to be recognized by Wayland. Either the sway version you have is too old or I have a false memory (the second is possible).

Root+Wayland is impossible everywhere. Nemo's root instance may run with XWayland.

**Comment by unmellow** [comment]
qt does work out of the box but it's using xcb which is x11 
as for root you're probably right but why wouldn't it work with xcb? it says it can't connect to display but maybe that's a qt thing and not anything you can fix

also the menu bug is a thing i made a typo before it happens whenever i use wayland mode
i'll see it their's similar problems with other qt apps

**Comment by unmellow** [comment]
all of my issues are with qt can confirm

**Comment by agaida** [comment]
@tsujan - i don't think so - at least it don't identify as xwayland

**Comment by tsujan** [comment]
None of those menu issues are Qt's, let alone LXQt's.

To test Wayland, the best option is Weston. If the latest version of Weston doesn't work well, you could be sure that something essential is wrong. If it works but Sway doesn't, you'll know that Sway has a problem.

**Comment by tsujan** [comment]
> @tsujan - i don't think so - at least it don't identify as xwayland

If you mean Gnome-shell, Qt apps run with X under it. You should try Weston or, better, a Plasma Wayland session.

**Comment by agaida** [comment]
btw - how to do i distinguish if a application under wayland runs native or as xwayland :smile:

**Comment by agaida** [comment]
Plasma wayland sucks - no root enabled for applications - and i guess i will not touch this bullshit until it is possible

**Comment by tsujan** [comment]
You use Breeze or Kvantum and see that windows can be dragged from inside them, not just from their title-bar -- a simple sign ;)

**Comment by agaida** [comment]
and no - i thought of an application that give me back if an app runs native or xwayland

**Comment by tsujan** [comment]
> Plasma wayland sucks - no root enabled for applications

I'm starting to tear off my hairs.... ;) Wayland is the enemy of root everywhere.

**Comment by agaida** [comment]
tell it to the calamares installer that running as root is evil ...

**Comment by tsujan** [comment]
Let me be straight: Wayland sucks in more than one way. I can make a list -- I think I did before.

> tell it to the calamares installer that running as root is evil ...

You could edit root files with gEdit and Kate. That doesn't mean they are opened as root -- they can't. There are other ways for that.

**Comment by agaida** [comment]
ok, i guess i will ignore wayland for another five years - maybe after that time they can do very basic things.

**Comment by unmellow** [comment]
you were right this is a sway bug idk why i refused to believe it

**Comment by tsujan** [comment]
> maybe after that time they can do very basic things.

They may say those basic things are "dangerous" or "impractical" (like placing windows with the toolkit). I've been in "danger" and did "impractical things for more than 15 years but felt safe. How stupid I am!

**Comment by tsujan** [comment]
> Gnome vs KDE: 1:0 in soccer terms.

Hi hi... it's 1:10 ;) I've given both enough time.

**Comment by agaida** [comment]
Well, i used to drive motocycle even in fall and winter. And yes, far under 0 °C and ice and snow - so i'm not affraid of placing a window with a toolkit or edit a file as root in a graphical application - they shouldn't patronize me before I go to a nursing home

**Comment by tsujan** [comment]
And don't forget the "hard" task of selecting a text and pasting it elsewhere by middle clicking. Don't we have something called "selection clipboard"? Wayland guys have never heard of it.

And...

**Comment by agaida** [comment]
Works in Gnome

**Comment by tsujan** [comment]
> Works in Gnome

Then, I should report that to them ;) They remove systray and right clicking and desktop icons and... but keep selection clipboard? Not fair.

**Comment by agaida** [comment]
Well, my gnome edition has a systray

**Comment by tsujan** [comment]
:D

**Comment by agaida** [comment]
mind if you minimize a common application to tray (hexchat, quassel, others) how to get the window back :smile:
![](https://i.imgur.com/65JrOLi.png)

**Comment by tsujan** [comment]
> mind if you minimize a common application to tray (hexchat, quassel, others) how to get the window back

Hadn't I told that I was a Gnome user and, only after Gnome 3.4, migrated away to KDE4 (and later, to LXQt)? Mouse acrobatics was only one reason among many. Gnome3 started with mouse acrobatics and has kept it until now. Previously, you could replace it with keyboard shortcuts but you had to define too many of them. At last, you reached the state of "enough is enough".

**Comment by agaida** [comment]
![](https://i.imgur.com/Po6yWE7.png)

![](https://i.imgur.com/cbOEBVO.png)

As i said - i don't know, how the Gnome guys do this - and i'm not very interested in, but as long it works it is more or less fine. And even if it is as xwayland, such an implementation in KDE and sway would pave the road for Wayland - far more than just discussion what i have to want and are allowed to as a user. The game is other way round: If a certain Desktop Environment don't fit my needs as a user, i will not use it - it's really that simple. And it seems to me that some of the Gnome guys has learned their lesson very well, it might be co-incidence that RH want to make money with Linux and business customers. And i know well how business users react if one tell them: From now on you are not allowed to do $this, just change your mindset and all your workflows. :sunglasses: - In this special case the business customers will be likely ex business customers. Not the best way to run a company.

**Comment by tsujan** [comment]
> As i said - i don't know, how the Gnome guys do this

Very simple. No joke! Really, it comes only to this directive: BE AS IMPRACTICAL AS POSSIBLE! That was an experiment that only Gnome3 was brave enough to conduct. They also call it "fast development" or "Gnome technology."

**Comment by tsujan** [comment]
@unmellow 
Do you by chance use Qt5ct? I know for sure that Qt5ct can prevent menus from showing with Wayland. If so, Sway may be innocent. Again, if so, you could disable it and use LXQt's Qt plugin (= libqtxdg + liblxqt + lxqt-qtplugin + lxqt-config) with `QT_QPA_PLATFORMTHEME=lxqt`.

**Comment by kennylevinsen** [comment]
Coming here from sway due to a bug being opened over there which caught my eye (https://github.com/swaywm/sway/issues/5040), which just pointed here.

@tsujan "Root+Wayland is impossible everywhere"

This is not true. Running GUI applications as root is a questionable activity, but works just fine. Wayland access only requires read/write access to the current $WAYLAND_DISPLAY. See the example one-liner below:

```sh
// WAYLAND_DISPLAY is relative to XDG_RUNTIME_DIR, which is a user-owned
// session-specific runtime directory. We just make the variable absolute
// to fix this.
WAYLAND_DISPLAY=${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY} sudo -E your-app
```

Tested with a few Wayland examples I had lying around under sway (I personally do not wish to run large applications as root on my machine).

The original report contains an example of Qt (like Gtk) requiring XDG_RUNTIME_DIR to be set to a session-specific runtime folder owned by the executing user—a requirement present under both X and Wayland. This can be fixed simply by creating a new folder, chown'ing it appropriately and setting the var to point to this folder before starting the application. This has nothing to do with Wayland.

-----

If you have any other questions, feel free to drop by #sway or #wayland on freenode. We're happy to help.

**Comment by tsujan** [comment]
> This is not true. Running GUI applications as root is a questionable activity,

Questionable activity?! Saying that to old Linux users...?

> See the example one-liner below

Frankly, it's yet another ritual for doing the simplest possible things. It's 2020 now.

**Comment by unmellow** [comment]
midle click paste is a thing in sway too how have i lived my life not knowing abou this?

**Comment by kennylevinsen** [comment]
> Questionable activity?! Saying that to old Linux users...?

Yes. Outside of some very special cases, there has never really been a good reason to run a GUI application as root. Tools like `sudo` exist solely to create short-lived sessions for tasks like `vi`, `cp`, etc., and it does not do the work required to fully satisfy modern GUI frameworks. Daemons also drop privileges as quickly as possible for a reason.

(I do remember back when running GUI applications as root was common for privileged tasks, but it was in a time where security wasn't much of a concern, and was never a good idea. Nowadays, DEs use PolKit to *temporarily* obtain whatever privileges are necessary.)

> Frankly, it's yet another ritual for doing the simplest possible things. It's 2020 now.

Then make it permanently absolute. It's just a file path to a standard UNIX socket with standard UNIX permissions, which is about as conventional UNIX as it can get. No arcane magic in form of xhost/xauth, just simple file permissions.

Otherwise, put it in a script. I certainly remember that you were supposed to use wrapper tools like `gksu` back in the day. You will have to set up XDG_RUNTIME_DIR at the very least anyway regardless of X or Wayland, as all modern frameworks expect it to be there and compliant (i.e. owned and accessibly only be the current user, not shared with the parent user).

**Comment by tsujan** [comment]
Go back to the last century and do this, that, this, that… and then, you could more or less work with root graphically, place and move windows in your code, etc. But, hey, these activities are questionable. Ask us, we know better...

OK. This isn't Linux. It isn't Unix either. It may be Android or Windows. I wonder who started this new cult. Apparently, it has its fanboys.

**Comment by tsujan** [comment]
This is working with root graphically:

![root](https://user-images.githubusercontent.com/981076/75252314-aed2b200-57f1-11ea-8ed6-8ddd75647d0b.png)

It make no difference whether someone calls it questionable, not a good idea, not recommended,… There's no taboo in Linux.

**Comment by agaida** [comment]
@tsujan - and i could really puke if i hear "questionable activities" - some developers should really ask developers of penetrate test systems like Kali and others - they are supposed to run live and with root as standard user :D

**Comment by tsujan** [comment]
> they are supposed to run live and with root as standard user :D

That's Linux. When I started Linux, you could easily log in as root. I never needed to do so — did it once with gnome2, out of curiosity — but I liked a system that didn't block me and didn't treat me like a fool.

> i would call only this idea questionable.

Some devs seem to spend time on making simple things impossible or difficult. This is new. It wasn't there before and then suddenly showed up, not unlike an epidemic.

Worse thing is that Windows refugees may believe that's how Linux is and quickly become gurus; hence, the vicious circle.

**Comment by agaida** [comment]
@kennylevinsen - please don't take it personal, but if i read code like that i could cry:
``` c++
#ifndef Q_OS_WIN
    // Prohibit using sudo or kdesu (but allow using the root user directly)
    if (getuid() == 0) {
        if (!qEnvironmentVariableIsEmpty("SUDO_USER")) {
            std::cout << "Executing Dolphin with sudo is not possible due to unfixable security vulnerabilities." << std::endl;
            return EXIT_FAILURE;
        } else if (!qEnvironmentVariableIsEmpty("KDESU_USER")) {
            std::cout << "Executing Dolphin with kdesu is not possible due to unfixable security vulnerabilities." << std::endl;
            return EXIT_FAILURE;
        }
    }
#endif
```
(https://github.com/KDE/dolphin/blob/master/src/main.cpp)

And it is utter crap and bullshit, these guys should leave drugs and booze alone or learn how to handle strong things - easy to demonstrate:

* case one: su vs sudo su :smile:
![](https://i.imgur.com/xJfgK0s.png)

* case two: sudo SUDO_USER='' kwrite vs sudo kwrite
![](https://i.imgur.com/GZBaPaz.png)

**Comment by kennylevinsen** [comment]
> @tsujan
> Go back to the last century and do this, that, this, that…

Uh... Linux was merely a hobby project back then. GNOME, KDE and Linux only existed for 1, 4 and 8 years of the past century, respectively, and they were *very* early in their lifetimes back then.

As for the rest of your comments, I'm not entirely sure what your current complaint is.

Running things as root *works* under Wayland, and *nothing* (Apart from the KDE team, apparently) gets in your way of doing so. That you have to make a file path absolute cannot possibly be considered a problem worth noting.

And yes, running any large application as root has certainly *not* been considered a good idea for the past two decades (well, I suppose it's three now), for *very* good reasons. However, there is no *taboo*. Everything is open source here, and your computer is *yours*—you can do whatever you want. If you want to expose a root telnet server with no password on the open internet, go ahead, it's your machine. But I do reserve the right to consider it a *very* bad idea. :)

(You mention GNOME when talking about "logging in as root"—I don't know what the situation is over there, but you can certainly start Sway as root to have a fully root Wayland session, should you wish to do so. *I* have done so, for testing purposes, and it works just fine.)

> @agaida
> @kennylevinsen - please don't take it personal, ...

I'm not author nor user of the code you link, so it would be hard for me to take it personally.

I don't think I'd *ever* want to write code that tries to protect you like that. People will find ways to do whatever they want anyway, so if they deliberately want to shoot themselves in the feet, let them. Of course, helping avoid accidents is fine (e.g. 'rm -rf /'), but there should be no hard restrictions.

I believe that instead of suggesting that the developers were drug and/or alcohol abusers, that you should simply discuss with the developers if you have any concerns. They already undid the change partially to let Kali through—which, being a very special-purpose distro not meant for normal use, usually running on throw-away hardware, does have a valid use-case—so they're apparently not super fixed on their decision. You earn the right to complain like that *after* you tried fixing it. :)

**Comment by agaida** [comment]
@kennylevinsen - well, look at the history of this special piece of code, it is worth it :) - and the discussion about will fill several books, so i wouldn't have contribute anything new. And it is not about personal feelings or thinking in terms of right or wrong - sure one has a bigger attac surface when running things as root.
Anyway, if we consider that we have educated users it might be a good idea to give them a hint that their app is running as root - should be sufficient - like this:
![](https://i.imgur.com/LOa8elt.png)
not less, not more - and if they shoot their foots knowingly, who cares - i run debian sid for over ten years and there was times when Debian Developers don't like and fight people who doing so.

**Comment by agaida** [comment]
bah - and i should change the german translation asap - some translators are really funny

**Comment by tsujan** [comment]
> and i should change the german translation asap

You mean "Wurzelinstanz"?

**Comment by agaida** [comment]
Yes, is now "Instanz mit Administratorrechten"

**Comment by tsujan** [comment]
Doesn't "Administrator" convey the meaning? There may be no need to translate "instance" in many languages.

**Comment by unmellow** [comment]
i can't run sway as root it says "[sway/main.c:195] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start"

**Comment by tsujan** [comment]
@tsujan You're torturing yourself with Sway's Wayland. No one recommends it here. You could try to ask your questions at Sway's github page. Sway's problem aren't related to LXQt.

**Comment by kennylevinsen** [comment]
> @tsujan
> You're torturing yourself with Sway's Wayland. No one recommends it here.

No need to be rude. I'd most certainly recommend *any* Wayland compositor over historical artifacts like X—a project which for all intends and purposes is abandoned. :)

> @unmellow
> i can't run sway as root it says "[sway/main.c:195] Unable to drop root (we shouldn't be able to restore it after setuid), refusing to start"

Problems running sway itself should be taken to sway's github issue or IRC channel (general questions belong in the latter—Github Issues are not for general discussion), rather than pestering pcmanfm-qt developers. Only pcmanfm-qt bugs belong here.

**Comment by tsujan** [comment]
@unmellow Please note that @kennylevinsen's words reflect *his* ideas, not what LXQt recommends.

**Comment by unmellow** [comment]
@kennylevinsen @tsujan 
i assumed it wasn't a bug sense it says it's trying to drop root
kenny said you could and i think they intentionally don't let you
i guess i could ask though
