### ISSUE TITLE
True single window mode

### ISSUE THREAD

**Issue by robschi** [lxqt/pcmanfm-qt#1094]
Is it possible to implement a true single window mode for PCManFM-Qt as choosable preference?

What I mean by that is that if for example if I press "Open Containing Folder" in Firefox, that this folder is opened in a new tab of a existing PCManFM window rather then in a whole new window.

I always end up with a ton of open PCManFM windows, but a single window would be much cleaner and especial with the possible split window mode, I don't need more windows.

**Comment by tsujan** [comment]
I'll look into it.

In the meanwhile, you could use tab DND and merge 2 or more windows.

**Comment by tsujan** [comment]
This is not only possible but — as an old part of the code implies — was also the intended default behavior. I guess the original author saw it a little odd to be the default behavior. I think so too because the window may be in another virtual desktop and we don't want clutter pcmanfm-qt's code by adding extra dependencies for virtual desktop awareness (which wouldn't work under Wayland either).

Anyway, I'll add an option for it soon (in a PR).

**Comment by tsujan** [comment]
The PR: https://github.com/lxqt/pcmanfm-qt/pull/1097

The new option:
![single-window-mode](https://user-images.githubusercontent.com/981076/79672643-439dce80-81e9-11ea-9c13-ad7b87a9d8b9.png)

**Comment by robschi** [comment]
Nice! Thank you very much!
