### ISSUE TITLE
An option to switch to newly opened tab?

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1110]
Is it really useful? Unlike in KDE, we don't want to add options for everything...

**Comment by Wobblystep** [comment]
I have some issues related to this.
Switching to newly opened tabs, be it optional or not, could simplify the fixing of some issues i will describe.

Directly related to your question, in my oppinion, the "Open in new tab" could only partially benefit from an option.
 In reality, the use cases are not either/or, one or the other. One could open in new tab for later, just like in making a note, or open and switch directly.
  A more complete way would be with a modifier and activation, but from the context menu, it depends if it can be done.
So Control and Shift are reserved for selection, again it depends if you can allow item activation with them pressed.


In the case of "single window mode":
 Browsing a folder of a newly downloaded file from a Web browser should switch to the tab.
 Also for desktop folders it should switch to the respective tab, which, being part of the same application and not an external command, you need additional code to handle the opening behaviour.
 And if it's not much trouble, the Computer shortcut as well.

Tied in to that is my main issue while in "single window mode", and fixing those would fix this:
 Opening pcmanfm-qt with the use of a global shortcut key, while it is already open, i intend to have a new tab ready for use. So with one key i could activate the app with a new active tab.
  That's the way it worked for me before i decided that single window could be easier to manage.
  So otherwise, before i hit that global key, i'd have to check if the file manager is allready running, so i wouldnt open a new background tab and cause clutter, just like i unintentionally open a second Web browser window in the same manner.
   But this one is just my use case, whatever the users want.


I guess their just some thoughts that don't tell you exactly which way to go yet.

**Comment by tsujan** [comment]
In this case, adding a new option seemed acceptable. The PR is https://github.com/lxqt/pcmanfm-qt/pull/1166 and the option is under Preferences → User Interface → Window.

**Comment by Wobblystep** [comment]
It's pretty funny. From the lack any past user activity, I didn't expect any action about this for like a year from now.
It's very welcome though Tsujan.

**Comment by tsujan** [comment]
@Wobblystep 
Your argument was convincing.

BTW, a 3/4-line comment is usually enough for a good argument; you didn't need to write more.

**Comment by Wobblystep** [comment]
Yeah i see that, sorry.
