### ISSUE TITLE
Fail to select/open single file/folder with keyboard

### ISSUE THREAD

**Issue by fulalas** [lxqt/pcmanfm-qt#1134]
If you enter in a folder with just one subfolder/file you can't select it or even open it with the keyboard.

**Comment by tsujan** [comment]
You can. Hit Space in this special case because the contained folder has focus.

In Qt, Space selects the current item (the item with focus) in a view.

**Comment by tsujan** [comment]
Of course, your libfm-qt/pcmanfm-qt should be up-to-date.

**Comment by fulalas** [comment]
Hmmm... How intuitive is that? Considering that pcmanfm-qt can change that (just like Dolphin did it), why keeping this odd behavior?

**Comment by tsujan** [comment]
We don't change things just because someone calls them "odd". The relation between Space and having focus in various widgets (buttons and combo-boxes included) is known to many and is present in GTK too.

**Comment by fulalas** [comment]
Hahahaha! You're funny, really!

**Comment by dimgel** [comment]
Couldn't have guessed about space either. "Contained folder has focus"? Which one is that? If something has focus it should be highlighted and react to Enter, none of which is the case. So actually after folder is opened, NOTHING has focus. I agree with "odd". Why don't you automatically focus first file/subfolder when folder is open? THAT would be intuitive.

**Comment by tsujan** [comment]
> I agree with "odd"

This isn't a matter of agreement or voting. The concepts of "current" (having focus) and "selected" are different from each other, not only in Qt but also in other toolkits. Please *learn* how to use the toolkit, instead of telling how it "should" be. It is what it is. Or you can tell Qt/GTK developers that you've found it "unintuitive".

"Current" (focused) items are distinguished *everywhere*, depending on the active widget style. For example, Fusion shows them by a light rectangle around the label, Breeze may draw a line under the label, Kvantum may draw a dotted rectangle around the label, etc. If you don't see that when you open a folder, either you have an old version or the style you use is suboptimal (the gtk2 style is so).

This is the last time I waste my time to explain Qt.

**Comment by dimgel** [comment]
You don't need to "explain Qt". I'm user, I don't care and must know nothing about your tools. No one must. Instead of fixing obvious usability shortcoming in YOUR app, you saying it is not default behaviour of framework you using. Pretty stubborn and idiotic argumentation, don't you think? Be you one of my workers, I'd fire you at once. But since we're talking about free application, there's nothing to complain about. You could just have said you don't care about users, it would be honest at least.

**Comment by fulalas** [comment]
@dimgel, don't waste your time with this guy. He's useless, and just like all arrogant people he favors his ego instead of his brain. ;)

**Comment by tsujan** [comment]
To prevent more irrelevant babblings, I locked this page.
