### ISSUE TITLE
preferences: option: disable the focus of the first file when the content of a file appears

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1170]
open pcmanfm-qt 0.15.1: the first file is in focus
I prefer that it is not in focus, so I can use the home-button or the arrow-right-key or rather the arrow-down-key to mark the first file, because I don‘t like to use the space-button for this; and I also don‘t like when a program makes a pre-selection without my agreement; I really don‘t like when the first file is in focus because I feel forced and I don‘t feel so free

(see also:
https://github.com/lxqt/pcmanfm-qt/issues/1169
)

what about if in the preferences (for example in the point behavior) there would be the possibility to disable the focus of the first file, for example with a checkbox:
disable the focus of the first file when the content of a file appears

I think that this should be possible because in pcmanfm-qt 0.14.1 it is like this:
I open the file manager; then I mark the image-file and I press enter:
the first file is not in focus and I can use the home-button or any arrow-key to mark the first file

please don‘t close this issue, because maybe there will be a strong demand in the future for this feature; let it open and give it the enhancement-label; maybe someone will realize it in 10 years; who knows

maybe it would be good if someone could add a like-button to this issue (I don‘t know how to do), so one can see how many people like this idea

##### System Information
Distribution & Version: Manjero LXQt
pcmanfm-qt: 0.15.1

**Comment by tsujan** [comment]
> disable the focus of the first file when the content of a file appears

Please read https://github.com/lxqt/pcmanfm-qt/issues/1072 to know why the current item was needed. Dolphin has it too.

I opened https://github.com/lxqt/pcmanfm-qt/issues/1072 after I closed https://github.com/lxqt/pcmanfm-qt/issues/1071 because the latter was a mixture of unrelated comments but contained a good point. (That also shows that we try to extract good ideas out of bad reports as far as possible.)

> Please don‘t close this issue, because maybe there will be a strong demand in the future for this feature

I'm afraid it wasn't a feature, in the first place, but a problem that was solved by https://github.com/lxqt/pcmanfm-qt/pull/1073. You should see it inside a vaster context to realize that.

> maybe it would be good if someone could add a like-button to this issue

A "like-button" may be good for Facebook. Here we try our best to follow reason, rather than likes/dislikes. Some of the reasons are explained in the links I included in the current comment.
