### ISSUE TITLE
'Computer' doesn't work in Open/Save dialog

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/pcmanfm-qt#1185]
0.15.1

Clicking on `Computer` on the left should open (or lead to opening) `/`. Instead it opens `root.link`, which is useless.

**Comment by Bydo-Spore** [comment]
Actually, it's only in Open; not Save.

**Comment by Bydo-Spore** [comment]
No, Made a mistake. It's in both Open and Save.

Clicking on `Computer` -> `File System` in either results in opening `root.link`.

**Comment by tsujan** [comment]
Correct. it's about a known issue, for which I didn't open a report (lack of time). Will open a detailed one at https://github.com/lxqt/libfm-qt/issues later (here is pcmanfm-qt's issue tracker, while the problem is in file dialog).

Closing because of the place, not the main point (which needs more details, BTW).

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libfm-qt/issues/565
