### ISSUE TITLE
Make it possible to align desktop icons right-hand side

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1189]
##### Expected Behavior

There is an option to align icons on the right-hand side of the desktop (like on the Mac) in addition to the current way of aligning icons on the desktop on the left-hand side (like on Windows).

##### Current Behavior

Icons on the desktop are aligned on the left-hand side of the desktop.

##### Possible Solution

There is a setting that allows one to have icons on the desktop aligned on the right-hand side of the desktop.

##### Context

As a longtime Mac user (since Classic Mac OS) I am looking for a desktop that works like it.

![image](https://user-images.githubusercontent.com/2480569/91662676-2a385780-eae4-11ea-88ba-7d686525d370.png)

##### System Information

* Distribution & Version: FreeBSD
* libfm-qt Version: 0.15.0

**Comment by tsujan** [comment]
Drag and drop icons anywhere you want them to be.

**Comment by probonopd** [comment]
Right-clik on the desktop, sort by type, I would expect them to be somehow automatically aligned?

**Comment by tsujan** [comment]
From your other report (https://github.com/lxqt/pcmanfm-qt/issues/1187), I guess you may want macOS here. That's OK. But please note that doing things just because some users want them leads to chaos because different users may want opposite things. This isn't just a theoretical consideration; I've seen it several times.

Adding options for them? That's reasonable but *only when what is wanted is functional*, not based on feelings or personal preferences. Otherwise, we'll have hundreds of senseless options and no one could find the practical ones. KDE's config dialogs are sometimes like that. We try to avoid it here.

I hope I've explained it clearly because I won't have time to participate in a discussion that has happened several times before.

**Comment by probonopd** [comment]
Thanks @tsujan. Yes I want pcmanfm-qt to behave Mac-like in many regards. And yes, I am not using KDE because its 10,000 checkboxes are confusing.

As far as I am concerned, one master switch "behave like a Mac" would do.
If this is not desired in this project, I will have to accept the fact. I appreciate simple code without too much configurablity myself, so I would definitely understand such a decision.

Then my best option would probably be to fork and the Mac-like behaviors there (without making them configurable for pretty much the same reasons).

**Comment by probonopd** [comment]
For the benefit of those who might come across this ticket through search, this feature has landed in https://github.com/probonopd/filer:

![image](https://user-images.githubusercontent.com/2480569/92018367-5dcde880-ed55-11ea-82b7-98007bea388d.png)
