### ISSUE TITLE
[Feature request] Support ROX-style AppDirs and GNUstep-style app bundles

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1190]
##### Expected Behavior

[ROX-style AppDirs](http://rox.sourceforge.net/desktop/AppDirs.html) and [GNUstep-style app bundles](https://www.informit.com/articles/article.aspx?p=665129&seqNum=7) show the application icon and are treated, when double clicked, like applications rather than like directories.

Similar to how `.app` bundles work on macOS.

##### Current Behavior

ROX-style AppDirs and GNUstep-style app bundles are shown like normal folders.

![image](https://user-images.githubusercontent.com/2480569/91663168-7d5fd980-eae7-11ea-99cb-57f8bdbc6401.png)

##### Possible Solution

Check how ROX-style AppDirs and GNUstep-style app bundles work. Essentially one just needs to display the correct icon and execute the application when the directory is double-clicked.

##### Context

I would like to be able to use ROX-style AppDirs and GNUstep-style app bundles from within pcmanfm-qt without having to use ROX Filer nor GWorkspace.

**Comment by probonopd** [comment]
I would possibly be willing to invest time into this if it is an acceptable/desired feature.

**Comment by tsujan** [comment]
We accept PRs though. Make a PR and it'll be reviewed for a merge.

**Comment by tsujan** [comment]
Last night, you bombarded us by your personal opinions about how things should be — in contrast to how things can be functional. Your personal opinions are respected but I explained [here](https://github.com/lxqt/pcmanfm-qt/issues/1189#issuecomment-683436739) why they can't be implemented. Only the current page seemed to be an exception to the rule. So, I kept it open because I didn't have time to think about it.

Now:

"mimetype" is a one of the most fundamental concepts in file management. If an app needs a special mimetype for doing some jobs, it should create it. When a program uses an `inode/directory` for another purpose, I'm afraid that program is weirdly nonstandard and we shouldn't make an exception for it.

Please answer this question:

Does "ROX-style AppDirs" or... treat some folders with special names as non-folders (instead of creating its own mimetype)?

**Comment by probonopd** [comment]
Without knowing (yet) the technical details of _how_ exactly  e.g., ROX Filer and GNUstep and the Mac have implemented this, I think both ways might be possible:
* Give those special directories a special MIME subtype, __or__
* Give them the normal MIME type and just treat them differently in the GUI

What I can tell is what should happen: These special folders should execute an action 
other than opening the folder when double-clicked, namely execute the contained application. (Opening them should still be possible by e.g., using the context menu.)

**Comment by tsujan** [comment]
> What I can tell is what should happen: These special folders should execute an action

For GLib/GIO, an executable `inode/directory` is like a horror film. We use GLib for file management.

Having read your other reports since yesterday, I guess you might think that pcmanfm-qt is a half-baked app that's supposed to be used for free experimentation, regardless of standards.

Again, your opinion is respected but I wouldn't invest a minute of my time in any LXQt app if I thought LXQt had no standard for development.

Forking is always possible. Closing this…

**Comment by probonopd** [comment]
> For GLib/GIO, an executable inode/directory is like a horror film. We use GLib for file management.

Not sure what you meant with that. 

Anyway, ROX-style AppDirs and GNUstep-style app bundles still have `inode/directory`. They are just treated as opaque objects in the file manager.

I have started to implement this in a fork, https://github.com/probonopd/filer/. Did not run into any major difficulties so far.

**Comment by probonopd** [comment]
For the benefit of those who might come across this ticket through search, this feature has landed in https://github.com/probonopd/filer:

![image](https://user-images.githubusercontent.com/2480569/92018367-5dcde880-ed55-11ea-82b7-98007bea388d.png)
