### ISSUE TITLE
Copy/Move Requester Accuracy

### ISSUE THREAD

**Issue by tenplus1** [lxqt/pcmanfm-qt#1196]
When copying a file from say an SSD drive to USB flash drive the requester always seems to show the percentage display at 99% as the file is read into the buffer, which isnt too accurate, so would it be possible to use the percentage of the file written instead for a more accurate display ? :)

**Comment by tsujan** [comment]
This isn't related to SSD or USB flash and can happen everywhere — with < 90% too — because the main job usually finishes before the dialog finds time to update its progress bar. It depends on several factors, like the drive, USB format and the number of files being copied.

I don't see any problem to solve. The dialog is closed when the main job is finished.

**Comment by tsujan** [comment]
To make certain, I read the code again:

It has nothing to do with reading into the buffer. For mutiple files, the total size of copied files is updated only when each copy process is finished. For each file, its copy progress is announced by GLib and recieved by libfm-qt. The progress bar shows the finished size plus the progress of the current file. So, everything is exactly as it should be.
