### ISSUE TITLE
Exclude identical extensions when sorting files

### ISSUE THREAD

**Issue by Adityashaw** [lxqt/pcmanfm-qt#1197]
Sort is "By File Name" with "Ascending" order.

If I have 3 files named `hi`, `hi_hello`, and `hi_1`. It is sorted properly as  
1. hi
1. hi_1
1. hi_hello

If the files have extensions then the *smallest* file name appears at last.
1. hi_1.txt
1. hi_hello.txt
1. hi.txt

##### Expected Behavior
The appropriate ordering should be : 
1. hi.txt
1. hi_1.txt
1. hi_hello.txt

##### Current Behavior
The current ordering is : 
1. hi_1.txt
1. hi_hello.txt
1. hi.txt

##### Possible Solution
First sort files alphabetically (lexicographically) without considering the file extension. If collision occurs, sort those collisions using their extension.

##### Steps to Reproduce (for bugs)
1.  Set Sort by "By File Name" with "Ascending" order.

##### Context
If there are many files with same prefix, I would expect the _smallest_ one to appear first. I would never expect it to be sometimes at start and sometimes at end. A consistency is what I expect.

##### System Information
* Distribution & Version: `0.15.1-1`
* Kernel: `Linux archlinux 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux`
* Qt Version: *couldn't find it*
* libfm-qt Version: `0.15.1-2`
* libqtxdg Version:  `3.5.0-2`
* lxqt-build-tools Version: `0.7.0-1`
* Package version: *don't know what's that*

*Extremely sorry for not using the github version*

**Comment by tsujan** [comment]
What you want is possible with a bit more computation (I think its extra CPU usage is negligible but I should test) and, personally, I like the idea.

However, there are two problems:

 1. I guess the current implementation is what most people expect, at least in the Qt world. Dolphin sorts files exactly as pcmanfm-qt does.
 2. Since we can't have a list of all valid extensions, we should treat everything after the last dot as an extension but, for example, it'll be weird with a folder, whose name is "my.github.projects". In other words, making an exception for the last dot just because it *may* be followed by a real extension isn't always intuitive.

I think the new behavior will be justified only if many users like it. If so, I might reluctantly agree with adding an option for it (for reasons that have been mentioned repeatedly, such options aren't good, IMO).

So, we should wait to see. A practical discussion would be welcome too.

**Comment by Adityashaw** [comment]
> 2. Since we can't have a list of all valid extensions, we should treat everything after the last dot as an extension but, for example, it'll be weird with a folder, whose name is "my.github.projects". In other words, making an exception for the last dot just because it _may_ be followed by a real extension isn't always intuitive.


I completely agree it will **not** be suitable for *folders* in any manner/situation.

My suggestion is only about _files_.

Besides, can you point me to the current source code portion where this sorting is performed, so I can understand the current implementation properly.

**Comment by tsujan** [comment]
@Adityashaw 
The implementation is not the problem; it's a piece of cake and will be done in both libfm-qt and pcmanfm-qt: I'll make 2 PRs for adding an option if others show interest in it and participate in our discussion. Although you and I like it, I'm not sure that others do too. Someone may say, "this isn't a standard way of sorting files..."

If you think that it isn't suitable for folders, then I'm afraid it may not be suitable for files either because, for example, we can have a file named as "my.important.letter".

My opinion is that, when it becomes optional (with the current implementation as the default), cases like "my.github.projects" and "my.important.letter" can be tolerated as inevitable but small side effects. Moreover, folders could be easily ignored in the code. What do you think?

**Comment by Adityashaw** [comment]
> @Adityashaw
> The implementation is not the problem; it's a piece of cake and will be done in both libfm-qt and pcmanfm-qt

I am not asking for the implementation because I want to suggest any change but for personal understanding of the current scenario.
 
> If you think that it isn't suitable for folders, then I'm afraid it may not be suitable for files either because, for example, we can have a file named as "my.important.letter".
> 

I didn't think about dots in name as I never add dots in name. I always use underscores. 
> My opinion is that, when it becomes optional (with the current implementation as the default), cases like "my.github.projects" and "my.important.letter" can be tolerated as inevitable but small side effects. Moreover, folders could be easily ignored in the code. What do you think?

I feel there's no way (other than knowing all possible "real" extensions) to implement this without side-effects. The current and the suggested methods both have their limitations and I think there isn't much gain by changing it. I think we should close the issue and wait for someone to come up with a clean idea.

**Comment by Adityashaw** [comment]
I found a difference between the sorting in `pcmanfm` and command-line `ls`
`pcmanfm` shows as : 
1. my_dod.important.letter
1. my_god.important.letter
1. my.github.projects

whereas `ls` shows as : 
1. my_dod.important.letter
1. my.github.projects
1. my_god.important.letter

I don't know which one is *more* right but just thought to point out the difference.

**Comment by tsujan** [comment]
> I think we should close the issue and wait for someone to come up with a clean idea.

New comments could be added to this page. However, I think the story is as simple as this: Add an option to exclude identical extensions with sorting and disable it by default.

Apparently, Dolphin doesn't do it but who cares? ;)  I checked SpaceFM right now; its sorting was like what is suggested here. I won't check Nautilus because it's a mess....

I think it's worth an implementation.   @yan12125, @luis-pereira,  ... ?

> ... but for personal understanding of the current scenario.

The key method is `ProxyFolderModel::lessThan()` and an optional exclusion of identical extensions can be easily added to it.

> I found a difference between the sorting in pcmanfm and command-line ls

The behavior of`ls` seems woefully counterintuitive to me.

**Comment by tsujan** [comment]
Since I saw it in SpaceFM (which shows we aren't alone), my only question is this: Should it be optional?

**Comment by tsujan** [comment]
This is all that's needed without an option (I hate so many options):

```diff
diff -ruNp libfm-qt-orig/src/proxyfoldermodel.cpp libfm-qt/src/proxyfoldermodel.cpp
--- libfm-qt-orig/src/proxyfoldermodel.cpp
+++ libfm-qt/src/proxyfoldermodel.cpp
@@ -187,6 +187,17 @@ bool ProxyFolderModel::lessThan(const QM
         default: {
             QString leftText = left.data(Qt::DisplayRole).toString();
             QString rightText = right.data(Qt::DisplayRole).toString();
+            // exclude identical file extensions for a more intuitive sorting
+            if(!leftInfo->isDir() && !rightInfo->isDir()) {
+                int leftEnd = leftText.lastIndexOf(QLatin1Char('.'));
+                if(leftEnd > 0) {
+                    int rightEnd = rightText.lastIndexOf(QLatin1Char('.'));
+                    if(rightEnd > 0 && leftText.mid(leftEnd) == rightText.mid(rightEnd)) {
+                        comp = collator_.compare(leftText.left(leftEnd), rightText.left(rightEnd));
+                        break;
+                    }
+                }
+            }
             comp = collator_.compare(leftText, rightText);
             break;
         }
```
I saw no difference when I opened a huge folder like `/usr/bin`.

**Comment by yan12125** [comment]
> I think it's worth an implementation.

No objection from me.

Actually, for me both sorting results (considering/not considering file extensions) are fine as I never remember the ASCII codes for symbols, so I never name my files like that :P

**Comment by tsujan** [comment]
@yan12125 
With Qt's default behavior, the sorting can be very counterintuitive — like in @Adityashaw's example. The method that's suggested here treats the last dot as the extension separator. People may abuse the last dot and name their files like "my.important.letter" but that's an exception to the rule, without serious side effects.

Therefore, I think adding an option would be an overkill. Instead, we need to adapt `QCollator` for file management, as in the above code.

**Comment by tsujan** [comment]
I'll use it for a while and will make a PR if no problem arises.

**Comment by tsujan** [comment]
LOL! I encountered an interesting logical paradox:

Suppose we have two files with names `a-.z` and `a.y`. Definitely, `a-.z` should come before `a.y` because `-` is "less" than `.`. Now we add the file `a.z`. Where should it be? If we compare it with `a.y`, it should come after it and we should have:

`a-.z` → `a.y` → `a.z`

But if we compare `a.z` with `a-.z`, according to the rule of identical extensions, the former should come before the latter and we should have:

`a.z` → `a-.z` → `a.y`

In practice, the patched libfm-qt sometimes shows the second order but switches to the first one after the folder is reloaded. Everything depends on which pair is used first for comparison and that's random.

I admit that this self-contradiction wasn't obvious to me until I encountered it. I don't know if other developers of file managers are aware of it but the above example shows that the logical sorting is necessary, although it may look counterintuitive with file extensions.

**Comment by Adityashaw** [comment]
> Suppose we have two files with names `a-.z` and `a.y`. Definitely, `a-.z` should come before `a.y` because `-` is "less" than `.`. Now we add the file `a.z`. Where should it be? If we compare it with `a.y`, it should come after it and we should have:
> 
> `a-.z` → `a.y` → `a.z`
> 
> But if we compare `a.z` with `a-.z`, according to the rule of identical extensions, the former should come before the latter and we should have:
> 
> `a.z` → `a-.z` → `a.y`
> 

I don't know if I am interpreting it right or not but as per my logic it should be 
`a.y` » `a.z` » `a-.z`

> In practice, the patched libfm-qt sometimes shows the second order but switches to the first one after the folder is reloaded. Everything depends on which pair is used first for comparison and that's random.
> 

2 different results from same sorting algorithm? How's that possible?

**Comment by tsujan** [comment]
> 2 different results from same sorting algorithm?

Actually 3. In your comment, you first compared `a.y` and `a.z`. As I said, the result depends on which strings are compared first — and that's wrong.

A self-consistent sorting is based on a [transitive relationship](https://en.wikipedia.org/wiki/Transitive_relation). The extension-based relationship is NOT transitive. In your example, from `a.y < a.z` and `a.z < a-.z`, it doesn't follow that `a.y < a-.z`. In fact, since the integer value of `.` is 46 and that of `-` is 45, `a.y` should come *after* `a-.z`.

**Comment by tsujan** [comment]
BTW and for future reference:

Your suggested sorting, `a.y → a.z → a-.z`, will be possible if we give priority to the extension. But add `b.y` to the list. Where should it be? The best place would be after `a.y`, so that we would have `a.y → b.y → a.z → a-.z`. Now, take a look at the middle relationship, namely `b.y → a.z`. It's simply absurd.

The logical sorting is `a-.z → a.y → a.z → b.y`.

Therefore, it's better to stick with the logic of string comparison and forget about extensions.

**Comment by Adityashaw** [comment]
> BTW and for future reference:
> 
> Your suggested sorting, `a.y → a.z → a-.z`, will be possible if we give priority to the extension. But add `b.y` to the list. Where should it be? The best place would be after `a.y`, so that we would have `a.y → b.y → a.z → a-.z`. Now, take a look at the middle relationship, namely `b.y → a.z`. It's simply absurd.
> 

No, never. I think I have not been able to explain my logic.

> The logical sorting is `a-.z → a.y → a.z → b.y`.
> 

As per my logic, it should be `a.y` » `a.z` » `a-
.z` » `b.y`.

> Therefore, it's better to stick with the logic of string comparison and forget about extensions.

That's fine.

>
> A self-consistent sorting is based on a [transitive relationship](https://en.wikipedia.org/wiki/Transitive_relation). The extension-based relationship is NOT transitive. In your example, from `a.y < a.z` and `a.z < a-.z`, it doesn't follow that `a.y < a-.z`. In fact, since the integer value of `.` is 46 and that of `-` is 45, `a.y` should come _after_ `a-.z`.

I never meant such a sorting method. Even my original post and title didn't intend to mean that. Sorry, for the confusion.

**Comment by tsujan** [comment]
> As per my logic, it should be a.y » a.z » a-.z » b.y

That's the same mistake gain ;) You *first* compared `a-.z` with `a.z` and got the above result. You could *first* compare it with `a.y` instead and get `a-.z → a.y → a.z → b.y`. That means randomness, as explained above.

The fact that different *first comparisons* may give different results is a consequence of a non-transitive relationship — in a transitive relationship, the first comparison isn't important.

There's no escape from mathematical logic ;)

**Comment by Adityashaw** [comment]
> > As per my logic, it should be a.y » a.z » a-.z » b.y
> 
> That's the same mistake gain ;) You _first_ compared `a-.z` with `a.z` and got the above result. You could _first_ compare it with `a.y` instead and get `a-.z → a.y → a.z → b.y`. That means randomness, as explained above.
> 

Even if `a-.z` is first compared with `a.y`, certainly `a.y` should come first.

> The fact that different _first comparisons_ may give different results is a consequence of a non-transitive relationship — in a transitive relationship, the first comparison isn't important.
> 
> There's no escape from mathematical logic ;)

What sorting algorithm is being used in pcmanfm-qt? Selection sort? Insertion sort? Merge sort? Or something else? I have never learnt any sorting algorithm whose result is undefined.

**Comment by tsujan** [comment]
> Even if a-.z is first compared with a.y, certainly a.y should come first.

No, the opposite is true. When you use the words like "should" and "certainly", you can't rely on your feelings but need to define an algorithm. `a.y < a-.z` is wrong (→ https://github.com/lxqt/pcmanfm-qt/issues/1197#issuecomment-700047406).

> What sorting algorithm is being used in pcmanfm-qt?

The logical sorting. pcmanfm-qt doesn't reinvent the wheel: https://doc.qt.io/qt-5/qstring.html#localeAwareCompare

**Comment by tsujan** [comment]
> What sorting algorithm is being used in pcmanfm-qt?

A more technical answer:

In the end, it's C++ → `std::wcscoll` (see https://en.cppreference.com/w/cpp/string/wide/wcscoll). It's called by `QCollator::compare(QStringView s1, QStringView s2)` (in Qt → `qcollator_posix.cpp`), which is called by `QCollator::compare(const QString &s1, const QString &s2)` (in Qt → `qcollator.cpp`).

**Comment by Adityashaw** [comment]
> > Even if a-.z is first compared with a.y, certainly a.y should come first.
> 
> No, the opposite is true. 

I think you're ignoring my original issue and the _"possible solution"_ I mentioned at the very beginning of this issue. `a` will definitely come before `a-` because the **sorting** must be performed _without_ the extension.


When you use the words like "should" and "certainly", you can't rely on your feelings but need to define an algorithm. `a.y < a-.z` is wrong (→ [#1197 (comment)](https://github.com/lxqt/pcmanfm-qt/issues/1197#issuecomment-700047406)).
> 

True but here I am only trying to explain the issue and how I expect it to work. If it's not working like that currently or will not be made to work like this is a separate issue (and you're the one to decide that). Well, it's alright if it cannot be changed to how I expect.

**Comment by Adityashaw** [comment]
> > What sorting algorithm is being used in pcmanfm-qt?
> 
> In the end, it's C++ → `std::wcscoll` (see https://en.cppreference.com/w/cpp/string/wide/wcscoll)

Thanks for the link but couldn't understand what would make `a` greater than `a-` to make it appear latter when comparing `a-.z` with `a.y`. 😕

**Comment by tsujan** [comment]
> I think you're ignoring...

Sorting cannot be performed without extension. You can at most ignore *identical* extensions, as I did in my PR. When it comes to comparing of `a.y` and `a-.z`, you have two different extensions and you can't put `a.y` before `a-.z` just because you like it.

> True but here I am only trying to explain the issue and how I expect it to work.

What you expect results in a random sorting, which is a bug. Only when you put an intuitive concept into mathematical/logical form, you may start to see its flaws. Coding is all about logic.

> hat would make a greater than a-

You mean "`a.` is greater than `a-`"? I explained it at https://github.com/lxqt/pcmanfm-qt/issues/1197#issuecomment-699995613 (the numbers 46 and 45).

**Comment by Adityashaw** [comment]
> Sorting cannot be performed without extension. You can at most ignore _identical_ extensions, as I did in my PR. When it comes to comparing of `a.y` and `a-.z`, you have two different extensions and you can't put `a.y` before `a-.z` just because you like it.

That wasn't what I actually wanted. So, the doubt is clear for me – we two were talking about different algorithms. 
 

> > what would make a greater than a-
> 
> You mean "`a.` is greater than `a-`"?

No, I strictly meant without the dot. But I have understood we cannot strip the extensions before sorting the whole list. Everything is clear now, thanks man for bearing me!

**Comment by tsujan** [comment]
> thanks man for bearing me!

Actually, I should thank you because, without your suggestion, I wouldn't become aware of all this.

**Comment by tsujan** [comment]
@Adityashaw, 
You were right when you said, "... we two were talking about different algorithms." I threw the baby out with the bathwater. My bad!

After a good sleep, I tried to save the main idea in another way and opened https://github.com/lxqt/pcmanfm-qt/issues/1201.
