### ISSUE TITLE
Relogin is needed to see the changes by kvantum and qt5ct

### ISSUE THREAD

**Issue by ansgoati** [lxqt/pcmanfm-qt#1199]
When i change a theme on kvantum and next apply it on qt5ct i need to relogin in order to see the effects. 

##### Expected Behavior

Apply the changes on qt5ct and then see the changes also on pcmanfm-qt.

##### Current Behavior

Apply changes on qt5ct and then i need to log out and relogin to see that changes on pcmanfm-qt.

##### Steps to Reproduce (for bugs)

1. Go to Kvantum Manager, click on  "Change/Delete Theme", Select a theme, click on "Use this theme".
2. Go to Qt5 Configuration Tool, Appearance -> Style: kvantum. Click on "Apply" click on "OK"

##### Context

In a day of customization, the needed of relogin everytime to see the effects in pcmanfm-qt consumes a lot more of time.
(Just a mention, on Dolphin File Manager the changes are seeing immediately)
I don't know if it's a bug or simply a configuration thing that i'm missing but better to report it to be sure.

##### System Information

* Distribution & Version: Artix Linux (lxqt)
* Kernel: 5.8.10
* Qt Version: 5.15.1-1
* libfm-qt Version: 0.15.1-3
* libqtxdg Version: 3.5.0-3
* lxqt-build-tools Version: Not installed
* Package version: 
pcmanfm-qt 0.15.1-1
kvantum-qt5 0.16.1-1
qt5ct 1.1-1

**Comment by tsujan** [comment]
Neither kvantum nor qt5ct is related to LXQt or pcmanfm-qt. Kvantum is developed by me independently of LXQt and qt5ct isn't needed with LXQt because, like KDE, LXQt has its own Qt plugin.

If you opened this issue at Kvantum's bug tracker, I'd give the following short explanation:

Due to the complexity of Qt styling, a running Qt app may never reflect all the details of a changed Qt theme, whether LXQt Appearance Configuration, qt5ct or KDE's systemsettings5 is used to apply the new theme. The latest git version of LXQt Appearance Configuration will work fine with the latest release of Kvantum if you change the theme from Kvantum to Fusion and conversely while changing the "Window Color" appropriately (a new feature in git) but still, some details (like translucency, blurring and symbolic icon colors) need app restart. The same is true with KDE's System Settings.

**Comment by tsujan** [comment]
BTW, no re-login is needed. It's enough to restart pcmanfm-qt from LXQt Session Settings (stop and start "Desktop").

> on Dolphin File Manager the changes are seeing immediately

Not completely true. You need to close and reopen Dolphin. The difference is that Dolphin exits when its window is closed but pcmanfm-qt is running in the background to draw desktop — unless it's explicitly stopped in LXQt Session Settings.

**Comment by ansgoati** [comment]
LXQt Appearance does not work for me to change Widget Style or Icons Type, i need to put something in Environment Variables ?? Also, the changes that i do with Kvantum and qt5ct is not reflected on LXQt panel until relogin, and on QTerminal i need to reopen the terminal or go to preferences and put apply. Is necessary to open an issue on QTerminal and LXQT panel ??

**Comment by ansgoati** [comment]
Ohhhhh, Check. So, i need to restart pcmanfm-qt and lxqt-panel from the LXQt Session Settings (stop and start "Desktop" and "Panel"). Thank you.

**Comment by tsujan** [comment]
> LXQt Appearance does not work for me to change Widget Style or Icons Type,

Because you have given the control to qt5ct. Only one Qt plugin works at a time.

> i need to put something in Environment Variables

By default, `QT_QPA_PLATFORMTHEME` is set to `lxqt` but you've changed it in order to use qt5ct.

> Also, the changes that i do with Kvantum and qt5ct is not reflected on LXQt panel until relogin

Again, no re-login is needed. Stop and start LXQt Session Settings → Panel

> Is necessary to open an issue on QTerminal and LXQT panel

No!. *Every running Qt app needs to be restarted*.

If there is an issue, it's in Qt itself.

**Comment by tsujan** [comment]
BTW. I've seen many users who think qt5ct belongs to Qt. **It doesn't.** Qt5 does NOT have a configuration tool; instead, it allows desktop environments to have their own "platform integration" by using their own plugins. If you use use qt5ct, you'll disable the platform integration by changing `QT_QPA_PLATFORMTHEME`.
