### ISSUE TITLE
Symlinks to not yet existing folders aren't refreshed

### ISSUE THREAD

**Issue by mantinan** [lxqt/pcmanfm-qt#1203]
I'm using Debian Buster, so version 0.14.1, and I have found this issue on pcmanfm-qt and pcmanfm.

I'm having on the Desktop a symlink to ../thinclient_drives/GUACFS a folder that apache guacamole uses for sharing stuff between clients and the server. The problem is that sometimes pcmanfm-qt is started by lxqt before the thinclient_drives folder is mounted, so as the target doesn't exist, it is represented as a file and even though later it is mounted, this is never updated.

The problem is that you cannot open the link folder by clicking on it, you can only open if if you navegate on a pcmanfm to the desktop and do a reload there.

This may not be a bug but a feature request, that symlinks are monitored.
I don't think this is related to issue #607 but I see that symlinks are also having trouble there, so maybe?

Maybe the solution to this really is nonsense, so feel free to close it if you feel so, I'll try to workaround this some other way.

Regards.

**Comment by tsujan** [comment]
The feature you want is quite valid theoretically and I vaguely remember that I mentioned it somewhere.

The problem is that monitoring symlink targets isn't practical; even if the needed code was simple (which can't be), its extra resource usage couldn't be justified, especially when you consider the possibility of symlinks of symlinks of.... Maybe for the same reasons, Dolphin and Nautilus doesn't do it either.

Reloading is the only way of knowing the status of changing targets.

BTW, this isn't related to your report but 0.14.1 is outdated.
