### ISSUE TITLE
pcmanfm-qt does not respect theme (or it is unclear how to set the theme)

### ISSUE THREAD

**Issue by spease** [lxqt/pcmanfm-qt#1217]
Does not respect theme set in "Appearance" control. Unclear where the theme setting is.

##### Expected Behavior

Setting LXQt theme or GTK theme in appearance should change theme. Or there should be some indication in Appearances control panel for LXQt to change LXQt-associated application themes.

##### Current Behavior

No change.

##### Context

Trying to use night theme on applications to minimize white light in the evening.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: Linux excalibur 5.9.1-arch1-1-g14 #1 SMP PREEMPT Mon, 26 Oct 2020 03:57:23 +0000 x86_64 GNU/Linux
* Qt Version: 5.15.1-3
* libfm-qt Version: 0.15.1-3
* libqtxdg Version: 3.5.0-3
* lxqt-build-tools Version: N/A
* Package version: pcmanfm-qt 0.15.1-1

**Comment by tsujan** [comment]
pcmanfm-qt isn't different from other apps with regard to styling: it doesn't have any hard-coded theme.

If you change your *gtk* theme, you shouldn't expect pcmanfm-qt to see it because it's a Qt app. If you use Qt's gtk2 style and change your gtk theme, you should restart pcmanfm-qt (like any other Qt app). pcmanfm-qt draws desktop in the background; so, you need to restart it from LXQt Session Settings.
