### ISSUE TITLE
double use of shortcut: undo, part 2

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1241]
this issue is based on <a href="https://github.com/lxqt/pcmanfm-qt/issues/1228">#1228</a>;

what about this: example:
esc OR F3, so both keys can be pressed individually to undo (so users who are used to esc can still use esc to undo);
I think to program esc or F3 should be not that much work; some minutes to program with a benefit in speed

same for F2, F3, ctrl+a, ctrl+f, ctrl+i, ctrl+l (and maybe for some more shortcuts)

double use of shortcut: undo:
it is incredible fast and it is a pity that it is at the moment only available for F6 and F9

##### System Information
Lubuntu 20.10; pcmanfm-qt version: 0.15.0

**Comment by tsujan** [comment]
@ralf3u, I hope you find some time to read this -- you seem too busy with opening pages.

Do not open another instance of the same report by saying, "this issue is based on,,,"! If you can't help adding more comments, add them to the pages that already exist.

This is an issue tracker, not a forum. It's used to organize work, not to chat.

**Comment by ralf3u** [comment]
I'm sorry; I thought that when an issue is closed, I can't add comments;
now I know that I can add comments even if an issue is closed
