### ISSUE TITLE
"Open tab as admin" abort loops

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1306]
Selecting "open tab as admin" and cancel the action opens many information windows before exiting definitevely.

##### Expected Behavior

Click "cancel" and it's over.

##### Current Behavior

It results in opening first "authentication failed" info window, then again the authentication window, depending clicking ok or cancel again, at some point the "permission denied" window, at some point I manage to close all and the "open tab in admin" is greyed out.

##### Steps to Reproduce (for bugs)

1. Click Tools > "open tab in admin" 
2. Hit "cancel
3. Try out different clicks on cancel, ok, closing info windows

While trying to get the logic I ended up here:

![schermata-19-58-26](https://user-images.githubusercontent.com/10681413/107558279-de352700-6bda-11eb-89ca-8c248853ab75.png)

##### System Information

* Distribution & Version: latestgit, arch

**Comment by tsujan** [comment]
Yes, I saw that peculiar behavior when I was implementing the feature but the cause wasn't clear and I didn't have enough time to dig into the code to find it.

**Comment by tsujan** [comment]
The logic is as follows:

 1. pcmanfm-qt requests a mount, shows Polkit's prompt, *and tells `libfm-qt` to retry to load the folder after Polkit's prompt is closed*.
 2. If the password is correct, the above-mentioned retrying will result in loading the folder.
 3. If the password is incorrect or Polkit's prompt is cancelled, the retrying will result in asking the password again (because Admin's mount is unusual -- read below), while pcmanfm-qt tells `libfm-qt` not to try anymore.

So, there is no loop; only one more password dialog.

GIO doesn't distinguish between entering a wrong password and cancelling Polkit's prompt: in both cases, it only says `G_IO_ERROR_PERMISSION_DENIED`.

On the other hand, although with usual mounts we can know whether a mount is added and then load its folder, the admin backend is different: apparently, it doesn't emit the signal "mount-added" and so, we don't have a way of knowing if it's mounted.

I didn't find a solution or trick without adding dependencies but might think about it later.

**Comment by tsujan** [comment]
OK, I found a simple and clean solution by making an exception for Admin :)  It's reasonable to treat Admin separately because, as I mentioned in my previous comment, it isn't an ordinary mount.

Will make a PR soon.
