### ISSUE TITLE
[Enhancement] Optional "Recurse Folders" for wallpaper slideshow

### ISSUE THREAD

**Issue by raekuul** [lxqt/pcmanfm-qt#1338]
I have a collection of wallpapers that, for organizational reasons, need to remain separated into various subfolders of a given folder (the parent folder is synced across multiple machines using a popular cloud-based platform, and some machines are only permitted to use certain subfolders while others are allowed to use all of them). I would like to have a "recurse folders" option for the wallpaper slideshow so that the machines allowed to use "all of them" can actually pull from any and all of the subfolders instead of only pulling from the parent.

**Comment by tsujan** [comment]
This was requested and closed before. An unlimited recursive search could be resource-unfriendly and adding an option for a limit would be an overkill.

**Comment by stefonarch** [comment]
I never use slideshow as wallpaper (mostly open windows cover my desktop so it's clueless), but in xscreensaver I like it very much (gslideshow), there is not even an option but it  includes all subfolders by default. 
Would limit it to 2 or 3 levels by design also be an issue for resources? Add a warning as tooltip if yes?

**Comment by tsujan** [comment]
I use pcmanfm-qt's slide-show but not xscreensaver. If I correctly remember, there are a limited number of screensaver files. You can't have 10,000 screensavers but you can easily have 10,000 JPEG/PNG/SVG/BMP/... images in subfolders. Each time a file is picked by `DesktopWindow::pickWallpaper()`, all of them should be scanned (because some files may have been removed/changed/added). That may be good for an app specialized in showing images but, IMO, it isn't practical for the desktop manager of a lightweight file manager.

**Comment by tsujan** [comment]
Oh, I said, "all of them should be scanned". My bad. I should have said, "all of them should be found and scanned". The app should find image files that are supported.

**Comment by stefonarch** [comment]
Thanks for explaining. 
No idea how xscreensaver's slideshow does this, but it picks  here from a directory with 2 levels of subfolders - 89Gb  and 24k files.
