### ISSUE TITLE
Focus to the new view (F6)

### ISSUE THREAD

**Issue by dglent** [lxqt/pcmanfm-qt#1380]
Hello

I propose to focus to the new split view (the right side view)when pressing F6
Actually when press F6 to split the view, the focus remain on the left view.

Maybe other users find this behaviour more comfortable.

**Comment by tsujan** [comment]
Thanks for your comment. These things are about personal preferences and are too personal to worth adding options for them (too many options would clutter the GUI).

Keeping the focus on the original view is the most natural way of splitting, especially because it may contain multiple tabs. You could use the `Tab` key to change the focus; the GUI clearly shows which view is focused.

**Comment by dglent** [comment]
The tab key to change focus is good idea

Thanks
