### ISSUE TITLE
drag&drop scrolling is too slow in icon view

### ISSUE THREAD

**Issue by bsduck** [lxqt/pcmanfm-qt#1417]
##### Expected Behavior
When dragging a file/folder inside a window, the window content should scroll down when the dragged item reaches the bottom of the window, so the item can be dropped in a folder located further down.

##### Current Behavior
It does, but in the icon view this happens at such a slow pace that it's almost unusable. The scrolling speed is much better when using list view.

##### System Information
* Distribution & Version: FreeBSD 13.0
* Qt Version: 5.15.2
* libfm-qt Version: 0.17.0
* libqtxdg Version: 3.7.1
* lxqt-build-tools Version: 0.9.0
* Package version: 0.17.0

**Comment by tsujan** [comment]
Confirming. It shouldn't be so slow.

**Comment by tsujan** [comment]
I didn't find anything in our code that causes it. Probably Qt has no way of changing the auto-scroll speed according to the grid size. If so and because the code of auto-scrolling is deep inside `QAbstractItemView`, I don't think we can do anything without adding a great amount of code, which isn't acceptable.

That being said, I leave this report open, hoping that a trick will be found. Dolphin does it smoothly; its code may contain an acceptable solution for us.

**Comment by toscompliantname** [comment]
That feature exists? wow
What do you need it for?

**Comment by bsduck** [comment]
This works fine on LXQt 1.0.
Closing this bug, thank you.
