### ISSUE TITLE
Moving files from read-only folder should be greyed out

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1419]
Selecting and DND a file or folder from a readonly folder /eg /etc) opens the "copy|move|link" dialog. When selecting "move" an error is displayed and copy starts. 
EDIT: true is also the opposite: all actions are "active" when dragging to a readonly folder like /etc
##### Expected Behavior

Action is greyed out from start
##### Current Behavior

It looks possible but is not.

##### Context

Not a big issue but would be cleaner.
##### System Information

* Distribution & Version: all&all

**Comment by tsujan** [comment]
> Not a big issue but would be cleaner.

I agree.

It may not be as simple as it seems because actions depend on both drag source and drop target.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/libfm-qt/pull/706

Notes:

 * Because, in cases like dropping into Trash, we don't want to show impossible actions, showing and disabling them wasn't a good approach. Instead, if no drop action is possible, the DND menu will have only one item that says, "Cannot drop here" (a new translatable string).
 * When a file can be dropped but cannot be moved, the "Move here" action is still there because it copies the file without an error message. That's how `libfm-qt` works and I saw no reason to change it.
 * In special cases (related to GVFS), we don't know which actions are impossible before doing the DND.

All in all, the feature had no cost and didn't clutter the code. Please test it.

**Comment by stefonarch** [comment]
Looks good. Am I right that now "move" will not switch again to copy when impossible?
Found a weird thing, new bug? 
DND some file to `menu://applications/`, select "move" and it disappears in nowhere, did that with a special file `xyztest` , `updatedb` and tried `locate xyztest`, it looks like really deleted.

**Comment by tsujan** [comment]
> Am I right that now "move" will not switch again to copy when impossible?

There's no difference in its behavior (my second note above was about that).

> DND some file to menu://applications/...

Not touched by this PR.

> All other locations tested show "can't drop here".

You mean only locations where can't accept a drop; don't you?

**Comment by stefonarch** [comment]
I remember 

> You mean only locations where dropping is impossible; don't you?

Sure, sorry was in hurry.

Looks like the error message I meant when DND and "move" is selected is only shown when some file permissions aren't met in some subfolder (eg moving /boot/), otherwise it always switches to "copy" with no message. 

Tested also root and admin instances, good.

**Comment by tsujan** [comment]
> Looks like the error message I meant when DND and "move" is selected is only shown when some file permissions aren't met in some subfolder (eg moving /boot/),

Oh, the message is about copying, not moving, because there are files (in /boot/) that can't be copied without root permissions.

Thanks to the tests! Let's use it for a while before merging it.

**Comment by stefonarch** [comment]
The message arrives also when trying to move. Actually move or copy are identical in those case.

**Comment by tsujan** [comment]
> Actually move or copy are identical in those case.

Correct. I mentioned that in https://github.com/lxqt/pcmanfm-qt/issues/1419#issuecomment-880445649 ("When a file can be dropped but cannot be moved....").
