### ISSUE TITLE
Closing target window while pasting from Edit menu closes file operation dialog (no crash)

### ISSUE THREAD

**Issue by drum445** [lxqt/pcmanfm-qt#1462]
##### Expected Behavior

Closing pcmanfm-qt during a copy/move action should not crash the dialog

##### Current Behavior

Closing pcmanfm-qt during a copy/move action crashes the dialog
Please note, the bug only occurs when closing the pcmanfm-qt window of where the file is being copied to (the destination)

##### Possible Solution

An unelegant solution, but better than it crashing, would be to disallow closing the destination instance till the action has completed

##### Steps to Reproduce (for bugs)

1. Open pcmanfm-qt
2. Copy a large(ish) file or directory
3. Open another pcmanfm-qt window
3. Paste the copied file/directory into this new window
4. Close the new pcmanfm-qt window before the copy has completed
5. Notice that the copy/move dialog has now crashed

##### Context

This is a daily issue as copying/moving files and directories around is a common task

##### System Information

* PcManFm-qt version: 0.14.1
* Distribution & Version: Lubuntu 21.04
* Qt Version: 0.14.1
* liblxqt Version:

**Comment by tsujan** [comment]
Found it: https://github.com/lxqt/libfm-qt/pull/604 (contrary to its title, it isn't only about emptying trash). Since it was merged on Dec 27, 2020, it should be in 0.17. We'll release LXQt 1.0.0 in November.

I think that the next Ubuntu should have 0.17, at least. Sorry, I don't know much about Ubuntu/Lubuntu; I just know that their latest versions are one release behind.

**Comment by tsujan** [comment]
The problem with closing the operation diialog on closing the window, when pasting was done by `Ctrl+V` or from Edit menu, is fixed in https://github.com/lxqt/pcmanfm-qt/pull/1463.

Most probably and unfortunately, the fix won't be in the next version of Ubuntu but it'll be in the November release. However, until the fix comes to Ubuntu (maybe they could backport it), if you paste by right clicking or with DND in 0.17, the operation dialog won't be closed on closing the window.

Thanks again for the report!
