### ISSUE TITLE
Right-side Info Panel [Feature request] 

### ISSUE THREAD

**Issue by maverick74** [lxqt/pcmanfm-qt#1482]
I've searched and didn't thing anything related to this as a request.

I think it would be nice to have an **_option_** to have a **_Right-side Info Panel_** (like in Dolphin, for example) that would show relevant information, thumbnails, sizes, etc.

Naturally, this would be good only if it would not affect performance to much :)

**Comment by tsujan** [comment]
Thanks for your suggestion! I reply quickly because I'd thought about it a long time ago.

It has two problems. First, it's in the opposite direction of keeping the app lightweight. Whenever we've added a feature, we've been careful about that.

Second, it bloats the GUI for no good reason. The relevant info is shown on the status-bar, tooltip or, if the user wants more, in the detailed list mode.

**Comment by maverick74** [comment]
@tsujan Thanks for being so fast and for the clarifications.

For sure we do not want to loose the lightweight factor in any way. For that we have Plasma,for example.

I suggested it only in the hope it would not be "_too heavy_".

Again, thanks for clarifying :)

**Comment by tsujan** [comment]
> I suggested it only in the hope it would not be "too heavy".

I understand.

A feature may not be too heavy by itself. But if we add features that are a little heavy one after the other, after a while, we'll lose control and reach a point where the app isn't lightweight anymore. Of course, many features have been added but none of them has affected the lightness — I have an obsession with that ;)

**Comment by maverick74** [comment]
> I have an obsession with that ;)

LOLOL Well, what a nice obsession to have in a project such as this. LOL 

Be sure to never loose it!!! XD

**Comment by tsujan** [comment]
BTW, and in case the same idea has come to your mind, I also tried to implement audio/video preview in pcmanfm-qt by using `QMediaPlayer` and `QMediaPlaylist`, thinking that it couldn't add to the resource usage. When I tried the code, I saw a huge memory leak that wasn't in it. Later, I found out that the leak was in `QMediaPlayer` and nothing could be done about it. Moreover, bad bugs in `QMediaPlayer` could affect pcmanfm-qt too.

**Comment by maverick74** [comment]
I have no idea of what _i'm_ talking about but... what about **[mpv](https://mpv.io/)** does it have anything that could help you do the trick?

**Comment by tsujan** [comment]
Adding dependencies like mpv would be too much. I didn't like `qt5-multimedia` as a new dependency either but was curious about the implementation.

I didn't stopped there. Another possibility was using a detached process with a minimal player like `ffplay` and without any extra dependency. At first it felt good but later, a hidden hang happened in `ffplay` and the preview didn't work anymore. It wasn't acceptable because users had right to think that the problem was in pcmanfm-qt (although it wasn't). That's a general problem with detached processes.

At last, I made a minimal audio/video previewer with `qt5-multimedia` — as a separate app —  and called it from pcmanfm-qt by using a detached process when an audio/video file was selected and the user pressed "/" or "F1". The player stopped and exited whenever the selection was changed or the tab was closed. Also, the above-mentioned leak was worked around. It worked and I sometimes use it just for the fun of it but it's a dirty patchwork I can't add to pcmanfm-qt ;)

**Comment by tsujan** [comment]
The above-mentioned previewer (its window is centralized on the screen):

![preview](https://user-images.githubusercontent.com/981076/140954808-c8697879-34ef-47f1-bbf8-c7955806b89f.png)

**Comment by maverick74** [comment]
Yeah... i see!!! 

It's for sure preferable not to have a feature than have a broken one that will only bring in more problems!!!

If you don't take me bad: i don't like that approach (from you last post)! It's surely preferable to open an actual video player!

**Comment by tsujan** [comment]
> i don't like that approach (from you last post)!

I don't like it either. It was the last resort.

**Comment by tsujan** [comment]
> It's surely preferable to open an actual video player!

It's a real audio/video player (with time info, pause, backward/forward, full-screening, screensaver disabling,...). Its GUI changes on mouseover. However, I can never recommend this approach.

**Comment by maverick74** [comment]
> However, I can never recommend this approach.

yeah, i totally agree with you on that!!!
I think it one of those Disney's "let it go" thing...

I, personally, really like how LXQt is ATM and have about a 5 working machines with it.
(however those pt-pt things we talked are an ugly badge on in LOL )
