### ISSUE TITLE
Recent Documents

### ISSUE THREAD

**Issue by slipttees** [lxqt/pcmanfm-qt#1483]
It could have an option in the Pcmanfm Menu>Files>Recent Documents for a list of opening recent files.

This was a big help to my dad and mom use computer for basic use when they used gnome-classic.

I miss that!

Image for example!
![unnamed](https://user-images.githubusercontent.com/25433004/140982663-e07cfa35-18d8-42e5-a723-ae006bc13bd7.png)

Bye folks

**Comment by tsujan** [comment]
Actually, having "Recent Files" as an option (disabled by default) is a tempting idea to me. Its contents can be written to a separate file inside `~/.config/lxqt/` or, perhaps, somewhere in `~/.local/share/`; then, for example, LXQt Panel could "see" it too and could have a "Recent File" plugin in future.

These are just untested thoughts. In reality, it should be much more complex than that and serious obstacles aren't impossible. So, IMHO, it needs more votes.

**Comment by stefonarch** [comment]
Actually I never used it, but I would like to see it, thinking other people will  use it.

**Comment by tsujan** [comment]
OK, out of curiosity, I'll get my hands dirty.

**Comment by tsujan** [comment]
It was easier than I'd thought. Will make a PR soon.

My idea about adding a plugin to Panel wasn't good practically because it required writing to the config file each time a file was opened by pcmanfm-qt. IMHO, we should be careful about these things; otherwise we might damage LXQt's lightness after a while.

**Comment by palinek** [comment]
> adding a plugin to Panel wasn't good practically because it required writing to the config file each time

How about adding D-Bus API (1 signal, 1 query method) to PCManFM. The org.pcmanfm.Application interface is already exposed to D-Bus.

**Comment by tsujan** [comment]
> How about adding D-Bus API

Yes, that's possible.

**Comment by stefonarch** [comment]
> My idea about adding a plugin to Panel wasn't good...

A menu entry would have the same issues?

**Comment by tsujan** [comment]
> A menu entry would have the same issues?

There's no issue, as @palinek suggested. But I first forget about the Panel and write the code. Later, when the new feature is merged and tested, it should be easy to make changes if we really want to add a Panel widget. I shouldn't have thought aloud ;)

Anyway, after testing a preliminary implementation, I found an obstacle, which I think can be removed: `libfm-qt` isn't ready for this. Some changes are needed in it for a consistent implementation. I'm trying to minimize the amount of changes — there should be just a few.

Therefore, it might take longer.

**Comment by tsujan** [comment]
It'll be like this:

![screenshot](https://user-images.githubusercontent.com/981076/141347563-a6204863-4ae0-4ea2-ab35-597c06a7c7c4.png)

It contains non-folder, native files that are lauched by using pcmanfm-qt in any way: clicking, hitting `Enter/Return`, right clicking and using "Open With...", or on Desktop. The paths are elided at middle if they're too long and icons are added if mimetypes can be guessed from file names. If an item is clicked, its corresponding file will be opened by its default app and it'll go to the top of the list.

As far as I've tested, its extra resource usage is negligible — I haven't noticed any change but it should be tested more. By default, it's disabled.

And this is the option:

![option](https://user-images.githubusercontent.com/981076/141349107-50d4758b-7b47-408e-84a4-b197a85b23ae.png)

https://github.com/lxqt/libfm-qt/pull/749 needs to be merged before the main PR is made.

**Comment by stefonarch** [comment]
Ok, thought I was missing something. Will there  be a bookmark, or an item in the sidebar?

**Comment by tsujan** [comment]
> Will there be a bookmark, or an item in the sidebar?

No. The list only consists of launched paths, like in many other apps that have "Recent" menus. We don't need the virtual directory `recent:///` or GVFS for this. I'm not sure how `recent:///` works but I know that it isn't related to launching.

If a deleted path is clicked, `libfm-qt` will show its generic error message. I preferred not to remove deleted paths (after clicking) because they might be useful to someone — who knows? The user might want to restore or just to know about them.

**Comment by slipttees** [comment]
> It'll be like this:
> 
> ![screenshot](https://user-images.githubusercontent.com/981076/141347563-a6204863-4ae0-4ea2-ab35-597c06a7c7c4.png)
Great work!!!
I can open file for menu entry?
But you can put this menu entry right below new window?

**Comment by tsujan** [comment]
> I can open file for menu entry?

Maybe, later. This is for pcmanfm-qt, while Main Menu belongs to Panel: two different and unrelated apps.

> But you can put this menu entry right below new window?

If you mean the menu-bar, it is there. In my screenshot, I've removed the menu-bar (`Ctrl+M`). If you mean the side-pane, I answered that in my previous comment.

**Comment by tsujan** [comment]
The PR is made here: https://github.com/lxqt/pcmanfm-qt/pull/1485. It needs tests.

As I said in the PR's commit, you need the latest git libfm-qt to test it.

**Comment by stefonarch** [comment]
Works fine!  My wishlist:
* a shortcut
* maybe another position in the menu "File" more on the top, after "create new".

**Comment by tsujan** [comment]
@stefonarch
Thanks for testing it so quickly!

> a shortcut

It already has a shortcut. On opening File menu, you'll see that "i" is underlined in "Recent Files" (you might need to pres Alt to see it if you don't use Fusion). Of course, translators might drop it.

> maybe another position in the menu "File" more on the top, after "create new".

IMHO, the bottom of the File menu is the most appropriate place because, first, it's about files and, second, the user can reach it more easily with mouse.

Please also test its various properties, like increasing/decreasing the number of recent files in Preferences, setting it to zero, or clearing the list.

**Comment by tsujan** [comment]
BTW, I found it useful already. I'd opened a file. Then I closed it. But soon, I needed it. Instead of going to its nested directory, I simply used "Recent Files" :)

**Comment by stefonarch** [comment]
Didn't find any issues, clearing and changing value.


> It already has a shortcut

I mean something _real_ ;) like cltr+r
Personally I hardly use those accelerators and I think I'm not alone with that (here alt+f for file is mapped for featherpad - alt+application I'm using for many apps, maybe not the best choice but I'm used to it).

**Comment by tsujan** [comment]
> I mean something real ;) like cltr+r

Menus and sub-menus are opened only by accelerators (or mnemonics; sometimes loosely called "shortcuts"). Ordinary shortcuts are for actions. I don't think you could find a case of opening a sub-menu with an ordinary shortcut.

> Personally I hardly use those accelerators 

Me too. But many people use them. I guess it's a matter of habit.

> here alt+f for file is mapped for featherpad...

The `Alt` that I was talking about is just for temporarily showing the underlines with some widget styles. Then, you could release it and press the underlined letter.

Very unrelated to this: I always use `Meta` in my global shortcuts. `Meta+F` for FeatherPad, `Meta+T` for QTerminal, etc. Because apps usually don't use it in their shortcuts.

**Comment by tsujan** [comment]
@stefonarch 
After using "Recent Files" for a while and being happy with it, I think your suggestion about its place (`maybe another position in the menu "File" more on the top, after "create new"`) is more logical than my argument (`IMHO, the bottom of the File menu is the most appropriate place because ... the user can reach it more easily with mouse.`).

If there's no objection, I'll put it after "Create New".

**Comment by stefonarch** [comment]
I'm fine with that :)

**Comment by tsujan** [comment]
Done.
