### ISSUE TITLE
Have a way to tell which split-view side is currently in use

### ISSUE THREAD

**Issue by roryyamm** [lxqt/pcmanfm-qt#1507]
I moved to PcManFm-Qt a while ago to replace an older manager called Xfe. When I switched, I brought over my tendency to use file managers in split view, as well. However, I keep getting confused as to which side of the split view I'm working on - which, when I go to use the common navigation buttons, or open a terminal, can lead to mistakes. Xfe solved this in its split view mode by having a green indicator for each pane light up when you were using it. Would it be possible to implement a similar indication feature into PcManFm, such as greying out the address bar of the side not currently in use?

**Comment by tsujan** [comment]
It has been there from day 1, with all view modes and all widget styles:

![split](https://user-images.githubusercontent.com/981076/146695212-315f1077-21b0-41f3-af38-1765c086cb58.png)

**Comment by stefonarch** [comment]
Somehow I agree - it's not always well clear to me too (and with some palette colors it's can be  even less evident) and could be improved.
Not sure if i would like a green signal. Using palette highlight  colors in tab button or address bar?

**Comment by roryyamm** [comment]
Turns out the issue was my theme not supporting selected-but-unfocused colors, or having that color be the same as the selected-but-focused color. Still, I don't think this functionality should be dependent on theme.

**Comment by tsujan** [comment]
The background color of the inactive split view is made by mixing the background and text colors with a proportion of 9 to 1. I can change that proportion (e.g., make it 8.5 to 1.5) but it works with almost all palettes, without rendering the inactive view unreadable or hard to read.

Yes, the difference may not be very clear in extreme cases. For example, if the background color is pitch-black (0,0,0), the inactive background color might not have a good contrast with it, but extreme cases have other problems too.

Please also note that we aren't free in changing palette colors in our code. I did it based on my experience in working with `QStyle`, so that all widget styles are covered.

**Comment by tsujan** [comment]
@stefonarch 
If you want to test other proportions, you could change these lines:

https://github.com/lxqt/pcmanfm-qt/blob/e5160d1406befeaff4301ea021e0d28b732dd121/pcmanfm/mainwindow.cpp#L427-L430

The sum should be 1.0.

In FeatherPad, I needed to do a similar thing. To cover extreme cases, I used a quadratic equation there but, IMO, it was an overkill for pcmanfm-qt.

**Comment by tsujan** [comment]
> Turns out the issue was my theme not supporting selected-but-unfocused colors

@roryyamm, you may have encountered this Qt bug about updating widgets: 

https://github.com/tsujan/Kvantum/blob/54cc21cb3cf26632d1c774d827098ccae1891a06/Kvantum/style/polishing.cpp#L1374-L1376

**Comment by stefonarch** [comment]
I played around with 0.8/0.2 and 0.85/0.15 but the effect is then too strong IMO.
But I wonder if the active tab button could be get more evidence somehow (always a red close button active? It's with dark palettes hard to see often which tab is open,

![schermata-12-20-10-54](https://user-images.githubusercontent.com/10681413/146748797-8a55be50-d4a6-479a-8267-eee8a28a12e1.png)

**Comment by tsujan** [comment]
> It's with dark palettes often hard to see which tab is open

That's not related to pcmanfm-qt. A widget style like Fusion or Breeze may have these problems with some dark palettes. The reason is that nothing but the palette can be changed with such styles (shapes are the same and border colors as well as gradients are made out of the palette).

I remember a bug report that I made against Oxygen many years ago. It was about dark palettes and the lack of enough contrast. They closed it, saying that Oxygen did its best with dark palettes. And they were right.

Compare it with Kvantum, in whose themes almost everything can be adjusted:

![kv](https://user-images.githubusercontent.com/981076/146758606-cf142c3c-8734-4355-bbff-128a88913265.png)
