### ISSUE TITLE
Copyright in the about dialog is outdated

### ISSUE THREAD

**Issue by RDKRACZ** [lxqt/pcmanfm-qt#1550]
![Screenshot from 2022-03-14 10-54-55](https://user-images.githubusercontent.com/43277609/158149000-7800a3f5-ea3b-4d16-8973-fe9601b6be0a.png)

**Comment by tsujan** [comment]
According to https://www.gnu.org/licenses/gpl-howto.en.html:

"For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage."

So, I don't think we need to update `X` in `2009-X` each year.
