### ISSUE TITLE
No error message before exit if D-Bus is not active

### ISSUE THREAD

**Issue by GravisZro** [lxqt/pcmanfm-qt#1562]
##### Expected Behavior
If PCManFM is unable to contact D-Bus then an error message or warning should be printing before resuming and/or exiting.

##### Current Behavior
PCManFM will happily exit without any feedback at all when it is unable to interface via D-Bus.

##### Possible Solution
In Application::parseCommandLineArgs() you should check QDBusConnection::isConnected() and QDBusInterface::isValid() before using them.

##### Steps to Reproduce (for bugs)
1. Kill the D-Bus daemon
2. Run pcmanfm-qt

##### Context
I had a config issue where D-Bus refused to start (circular inclusion) and I had no idea why PCManFM simply wouldn't run at all.  I finally built/launched a debug enabled version and tracked down the cause.

**Comment by galaxyhaxz** [comment]
I believe this same issue also happened to me. If D-Bus is misconfigured then trying to open a folder as root will not launch without any error message. After fixing D-Bus it opens properly.

**Comment by tsujan** [comment]
Problems in D-Bus should be announced by D-Bus.

**Comment by GravisZro** [comment]
@tsujan
The problem with DBus **is announced by the D-Bus interface** but it's not being checked.

In [application.cpp, line 293](https://github.com/lxqt/pcmanfm-qt/blob/master/pcmanfm/application.cpp#L293) a D-Bus connection is opened and but never checked if it's valid.
```cpp
        QDBusConnection dbus = QDBusConnection::sessionBus();
        QDBusInterface iface(QLatin1String(serviceName), QStringLiteral("/Application"), QLatin1String(ifaceName), dbus, this);
```
This should be something like:
```cpp
        QDBusConnection dbus = QDBusConnection::sessionBus();
        if(dbus.isConnected()) {
            QDBusInterface iface(QLatin1String(serviceName), QStringLiteral("/Application"), QLatin1String(ifaceName), dbus, this);
            if(iface.isValid()) {
```

If D-Bus isn't running then how is it supposed to tell your it's not running if you don't check the interface?

**Comment by tsujan** [comment]
> It will enable you to print out that there is a problem with D-Bus.

It won't. You kill dbus-daemon, systemd starts a synchronous process, and a freeze state happens (you can't start any app) until dbus-daemon is started again.

> If D-Bus is misconfigured then trying to open a folder as root

Read Preferences → Advanced → Programs → Examples

**Comment by GravisZro** [comment]
I don't use Systemd, so nothing like what you claim happens.

**Comment by GravisZro** [comment]
If you fix this then the worst case scenario is you add a couple condition statements that print a message that very few people will see.

**Comment by khumba** [comment]
Hello, and thanks to tsujan and the maintainers for their hard work on pcmanfm-qt and LXQt.

I would like to request that this bug be reconsidered.  I am in the process of digging into the pcmanfm-qt code to figure out why "Open Tab in Root Instance" is not working on Debian bookworm, and a bunch of initial time could have been saved if pcmanfm-qt had been verbose about it not being able to connect to DBus.

Specifically, the assumption that `QDBusConnection::registerService()` returns false because the service is already registered is not always correct.  With some additional logging:

    Application::Application(int& argc, char** argv): ... {
        ...

        QDBusConnection dbus = QDBusConnection::sessionBus();
        qDebug() << Q_FUNC_INFO << "Connected to session bus: " << dbus.isConnected();
        if(dbus.registerService(QLatin1String(serviceName))) {
            qDebug() << Q_FUNC_INFO << "Service registered successfully";

            // we successfully registered the service
            isPrimaryInstance = true;

            ...
        }
        else {
            qDebug() << Q_FUNC_INFO << "Service NOT registered successfully";
            qDebug() << Q_FUNC_INFO << "DBus error: " << dbus.lastError().name() << ": " << dbus.lastError().message();

            // an service of the same name is already registered.
            // we're not the first instance
            isPrimaryInstance = false;
        }

This outputs:

    PCManFM::Application::Application(int&, char**) Connected to session bus:  false
    PCManFM::Application::Application(int&, char**) Service NOT registered successfully
    PCManFM::Application::Application(int&, char**) DBus error:  "org.freedesktop.DBus.Error.Disconnected" :  "Not connected to D-Bus server"

which is not a duplicate name error as the comment suggests.

The "Open Tab in Root Instance" failure seems to be caused by SuCommand defaulting to `lxqt-sudo %s` rather than `lxsudo dbus-run-session -- %s` (the latter of which is used in my testing on Tumbleweed, Gentoo), and that's as far as I've had time to look into that issue at the moment.  I'm not sure why the default (former) string in settings.cpp doesn't match the default (latter) string in settings.conf.in...  Should settings.cpp be fixed so that the default is to always call `dbus-run-session`; or if it's not correct to always call, maybe pcmanfm-qt should use a wrapper that calls it when necessary?

In any case, back on the topic of connecting to DBus, what you do think about clarifying the error handling so that duplicate name errors are checked accurately, and/or unexpected errors are reported on the command line?  A failed start with exit code 0, no output, and nothing to say "go change SuCommand" is confusing to say the least.

Thanks!
