### ISSUE TITLE
Make option to disable smooth scrolling work in all modes

### ISSUE THREAD

**Issue by galaxyhaxz** [lxqt/pcmanfm-qt#1564]
Per the initial commit here https://github.com/lxqt/pcmanfm-qt/commit/4297d6c77427a25683c1a44a3b9d83164966721f it doesn't apply to the icon modes. I personally dislike smooth scrolling and have it disabled on all programs that have it. It is objectively faster to scroll from A->B in one single frame than to force it to animate over multiple frames. I'd also suggest changing the option to say "Enable smooth scrolling" to keep consistent with other programs like Firefox.

And thanks for all the hard work on LXQt! I'm transitioning from Windows 7 to Linux and wanted a fast DE without all the fancy effects. I hope the project will continue its design of minimalism and lighter resource usage and not go down the Gnome 3 rabbit hole. Would love to get involved in development once I'm setup (:

**Comment by tsujan** [comment]
> I personally dislike smooth scrolling and have it disabled on all programs that have it.

Personal preferences are respected but can't be a reason for making changes.

**Comment by galaxyhaxz** [comment]
I get that but linux is supposed to be about customization to your liking. Maybe a second option explicitly for the list modes would be more suitable? I can try poking the code myself. The lack of freedom in changing things is exactly why I'm leaving Windows, because I don't like stuff like narrow hiding scroll bars and wobbly effects.

**Comment by tsujan** [comment]
More specifically, options aren't added based on personal preferences of devs or users but for practical reasons. Because of a problem in Qt, smooth scrolling might cause a slowdown in switching to the list mode under special circumstances. That isn't the case for the icon mode.

**Comment by galaxyhaxz** [comment]
> Contrary to KDE, we don't add options for everything in LXQt.

But unlike KDE, LXQt has far less bloat and is much speedier. So adding an option to disable smooth-scrolling (which uses more CPU and adds bloat) should align with the project's goals.

**Comment by tsujan** [comment]
> which uses more CPU and adds bloat

We care for CPU, I/O and memory in a reasonable way.

> ... See which one is faster...

The user could middle/left click the scrollbar (depending on the used Qt style) or turn the mouse wheel on the scrollbar if he/she wants faster/jumpy scrolling. The implementation is flexible.

Smooth scrolling isn't an "eye candy".

**Comment by galaxyhaxz** [comment]
> The implementation is flexible.

Which is why you refuse to add an option for those who prefer direct scrolling without having to move the mouse and click the scroll bar every time. And if it wasn't for the problem Qt has it would probably be forced in list modes as well.

With the cleanup you did to add the option for list modes, I'm going to estimate it would take less than 10 lines of code to solve this in a way everyone can be happy...

**Comment by rieje** [comment]
FWIW, I find found smooth scrolling to be disorientating and difficult to see the text until the animation is stopped, especially since the duration/speed of the smooth scrolling is longer than any apps I've tried smooth scrolling on.

In general smooth scrolling is imprecise as well. It seems weird to have the option to disable smooth scrolling available for some views but not Thumbnail View--I would think for that reason alone the option to disable it would be of interest to have consistency in terms of options and user experience. I've come across this issue having tried pcmanfm-qt for a couple of minutes and failing to find the option to disable smooth scrolling.

Smooth scrolling is prevalent in mobile phones because a simple tap of a thumb stops the scrolling immediately so you land exactly where you want. Requiring the user to use the scroll bar for precision as the only alternative is at best a workaround. Mouses have scroll wheels so we don't need do that.

If the smooth scrolling duration/speed can be configurable, then that is also fine, but in that case simply offering the option to smooth scrolling for Thumbnail View *like it is already offered in other views* seems like an obvious choice.

> Because of a problem in Qt, smooth scrolling might cause a slowdown in switching to the list mode under special circumstances. That isn't the case for the icon mode.

How is that supporting the argument for not providing the same option for Thumbnail View? I've never come across an application that offers smooth scrolling to also not offer the ability to disable it. And the fact that many apps don't support smooth scrolling (i.e. it is "disabled by default") means it's a popular choice. Withholding the option to disable smooth scrolling is the opposite of flexible implementation.

**Comment by tsujan** [comment]
For readers of this page not to be mislead by the above comment:

Smooth scrolling isn't a culprit of anything.

The rest is already answered.

**Comment by rieje** [comment]
> Because of a problem in Qt, smooth scrolling might cause a slowdown in switching to the list mode under special circumstances. That isn't the case for the icon mode.

The ability to disable smooth scrolling for certain modes was provided *because* there were issues with smooth scrolling on Qt.

This is literally what you've said.

**Comment by tsujan** [comment]
That amount of misinformation in your long comment was surprising; hence the short reply.

For more details → https://github.com/lxqt/pcmanfm-qt/wiki#mouse-wheel-scrolling

**Comment by enoryw** [comment]
@galaxyhaxz @rieje  If you want a file manager with sane behaviors, just stick with the original pcmanfm using GTK that pcmanfm-qt is based on. Can actually disable smooth scrolling everywhere (in fact, that's the default, because we are on a PC interacting with other applications like terminal emulator that avoid smooth scrolling to prevent headaches 🤣. Alternatively, I found it bearable to enable smooth scrolling in certain apps like Firefox where you can configure the speed to be really fast so it's subtle and text and position where you land is clear.

No self-imposed limitations by the devs. There are [tips](https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications) to make it uniform with your Qt applications). Good luck!

**Comment by roryyamm** [comment]
> The user could middle/left click the scrollbar (depending on the used Qt style) or turn the mouse wheel on the scrollbar if he/she wants faster/jumpy scrolling. The implementation is flexible.

I'm only on 0.16 (Debian package maintainers dragging their feet as usual), so this may have changed, but turning the mousewheel on the scrollbar does not save me from smooth scrolling.
> More specifically, options aren't added based on personal preferences of devs or users but for practical reasons

I'd understand that if this was some minor graphical detail - KDE does go overboard with their options - but in a file manager like this one, much of what you do is scrolling through views. The act of scrolling is a core element of this program, and I believe it is natural to expect some ability to tune it to one's preferences - even if that tuning is just 'smooth scroll everywhere/smooth scroll nowhere'. Icon sizes are similarly significant to the program, and they get four menus for choosing a variety of sizes for each view. I don't see how these options are any more 'practical' in nature than scroll behavior. 

> just stick with the original pcmanfm using GTK that pcmanfm-qt

'Just use something else' doesn't work when the program you're suggesting an alternative for IS the 'something else'. What if someone came to -qt specifically to get away from the original version?

**Comment by enoryw** [comment]
> 'Just use something else' doesn't work when the program you're suggesting an alternative for IS the 'something else'. What if someone came to -qt specifically to get away from the original version?

It wasn't meant to be a solution, it's only a workaround when the dev here fails to provide a good reason for not implementing the ability to disable smooth scrolling and even goes as far as to imply that they are not like KDE so they would rather limit their product and not provide the option to users who want the feature, i.e. "if you want to disable smooth-scrolling, use KDE". It's just terrible mindset so your best bet is to use a more reasonable product instead of hoping for something that will never happen.

I agree that the option to disable smooth scrolling is essential and a core feature of any application--there's a reason why terminals and many file managers including the most popular ones don't have smooth scrolling enabled by default (most don't even have the option to enable it). As someone said here, it makes it difficult for your eyes to follow the text and it's not easily predictable where you end up after scrolling. I've tried pcmanfm-qt for a few hours and immediately found this thread because I couldn't believe smooth scrolling is the default, let alone there is no option to disable it.

**Comment by stefonarch** [comment]
Done in https://github.com/lxqt/libfm-qt/pull/875
