### ISSUE TITLE
Issue with multiple selection, automatic selection is active always

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1625]
With single click deactivated and 0,60 sec delay greyed out multiple selection of files using ctrl is unusable.

##### Expected Behavior

The 0,60 sec setting is deactivated without single click as text says
##### Current Behavior

It is active, files are selected with 0,60 sec delay.

##### Steps to Reproduce (for bugs)

1. Single click unchecked, default setting 0,60 sec is greyed out and cannot be modified
2. Try selecting multiple file using ctrl
3. Hover on a file, it will be selected after 0,60s

##### Context

Found only out on a new installation for a friend
##### System Information

* PcManFm-qt version: 1.1.0, current git
* Distribution & Version: arch, debian

**Comment by tsujan** [comment]
That's because the DE setting is still single-click in your case — as the tooltip says, the DE setting will be used if you uncheck "Open files with single click". Once you change the DE setting to double-click, 0.6 won't have any effect.

But, theoretical reasoning aside, yes, this behavior isn't good in practice. We should either not disable the spin-box or, preferably, not consider it when disabled.

Thanks!

**Comment by tsujan** [comment]
Fixed now.

**Comment by stefonarch** [comment]
> That's because the DE setting is still single-click in your case

No, it was in double click then. Nice that it's fixed thanks+

**Comment by tsujan** [comment]
> it was in double click then.

`libfm-qt` considers auto-selection only with single clicking. If you see it when you have to double click items to open them, please report it.
