### ISSUE TITLE
Doesn't open non-executable scripts with root executable flag

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1717]
### Version
* pcmanfm 1.3.2

### Description
- Clicking on a script at "/usr/share/haskell/unregister" does nothing.
- But the "open with..." dialog does.
- Copying the script into the user home allows the script to be opened by clicking on it.

**Comment by tsujan** [comment]
Which script exactly?

**Comment by es20490446e** [comment]
Oh yes, sorry, I saw the wrong package. But I'm actually using the QT version.

All the scripts in "/usr/share/haskell/unregister" don't open by clicking on them, but they do with the "open with" menu option.

Weirdly I can open the scripts in "/usr/bin", probably because those have exec permissions for all users.

**Comment by tsujan** [comment]
I installed `ghc-libs`, `haskell-silently` and `haskell-split` to have some scripts inside `/usr/share/haskell/unregister`, and all of them are opened by FeatherPad. So, the problem is not reproducible.

Would you please attach screenshots of `File Properties` (in the right-click menu) → `General` as well as `File Properties` → `Permissions` for one of those scripts?

**Comment by es20490446e** [comment]
![1-General](https://user-images.githubusercontent.com/9594332/214467905-9756b7c3-79ac-41ac-b3b1-d1e096791992.png)

![2-Permissions](https://user-images.githubusercontent.com/9594332/214467913-72d9aede-ce7f-4950-9377-9f8eb680f9b2.png)

**Comment by tsujan** [comment]
Thanks. Everything is exactly like here. This is getting strange!

Answering the following questions might help — some of them may sound weird, but the problem is weird too.

 1. Correct me if I'm wrong: by "opening" you mean opening in FeatherPad, **not** executing; don't you?
 2. Where do you use pcmanfm-qt? Under LXQt?
 3. Are you sure that the script isn't opened in a FeatherPad window that's already running in **another** virtual desktop? I ask because, for example, under Wayland, apps aren't activated and you may not notice that the file is actually opened.
 4. Please tell me which version of pcmanfm-qt you have. With a recent version, you could see its number in Help → About.

**Comment by es20490446e** [comment]
1. If I click on a script I cannot select if to open or to execute. Simply put no dialogue appears.
2. The desktop is KDE Plasma.
3. There's only one virtual desktop and screen active, checked.
4. Version 1.2.1.

**Comment by tsujan** [comment]
> Simply put no dialogue appears.

That's the strangest part.

> The desktop is KDE Plasma.

It may be related, having what is called "activities"...

I don't know which LXQt components you have but, as a harmless test, please stop all `pcmanfm-qt` processes and run it with `export XDG_CURRENT_DESKTOP=LXQt && pcmanfm-qt` from a terminal (e.g., Konsole). Does the problem happen again?

**Comment by es20490446e** [comment]
Same result, and no errors on the terminal.

**Comment by tsujan** [comment]
OK. Some piece of info is definitely missing. I have no more guess for now.

If you have more info, please add it.

**Comment by es20490446e** [comment]
I will investigate 🔍

**Comment by tsujan** [comment]
> I will investigate

Also, check what happens when you select the item and press ENTER. Do everything inside a terminal to see probable messages (add them to your comment if any).

**Comment by es20490446e** [comment]
Pressing enter does nothing too, with one or multiple files.

No messages.

**Comment by tsujan** [comment]
> Pressing enter does nothing too, with one or multiple files.

At least the magic is self-consistent ;)

Think of any unusual setting in your system — by "unusual" I don't mean "wrong".

**Comment by es20490446e** [comment]
It also happens on the Manjaro KDE Live USB.

I will check with another Manjaro desktop.

**Comment by tsujan** [comment]
I have Manjaro, but I use my own packages, build from the latest git sources.

If the problem is about packaging, there shouldn't be any difference between Manjaro and Arch because the former takes its packages from the latter.

**Comment by es20490446e** [comment]
I tried with Manjaro XFCE, with the same result.

So it doesn't seem to be related with activities as, as far as I know, XFCE doesn't have that.

I will try with something completely different. Lubuntu for example.

**Comment by tsujan** [comment]
What about other kinds of script —python, for example — do you see the same problem with them? There are many in /usr/share/.

**Comment by es20490446e** [comment]
Okay, I figured it out 😉

It does happen only if two conditions are met. That the file:
- Has a shebang
- Is only executable by root

You won't normally notice this bug because it's rare that files meet both conditions. As usually a file that is executable by root, and readable by users, is also executable by users.

Aka people just do:
chmod +x [file]

But rarely:
chmod u+x [file]

It is also reproducible in Lubuntu 22.10, with pcmanfm-qt 1.1.0.

**Comment by tsujan** [comment]
As I said in https://github.com/lxqt/pcmanfm-qt/issues/1717#issuecomment-1402994170, I checked exactly the files you mentioned (did more tests later) and didn't see a problem. They satisfied those conditions but could be opened by clicking here.

So, there should be something else.

**Comment by tsujan** [comment]
A video:


https://user-images.githubusercontent.com/981076/215358344-57e56640-5560-4cc7-a785-ec90fe49b898.mp4

**Comment by es20490446e** [comment]
I'm out of ideas.

Maybe try reproducing from the live USB, and see if it happens to you.

To discard that I'm doing something wrong myself.

**Comment by tsujan** [comment]
OK, I did this:

 1. I installed the latest `manjaro-xfce-XXX.iso` in VirtualBox and saw the problem. It was exactly as you described.
 2. Then, I uninstalled libfm-qt and pcmanfm-qt and compiled and installed them from their 1.2.1 sources. The problem persisted.
 3. Then I compiled and installed them from git. The problem persisted again.
 4. Finally, I got angry and compiled and installed them from the sources I have here. They're a little different from the git sources. **This time everything was OK!**

A video that shows this in VirtualBox:

https://user-images.githubusercontent.com/981076/215366909-a1a5d1cf-d644-409a-b1b9-0b8ab658af3f.mp4

I haven't applied any patch for this problem to my sources because, obviously, I didn't know about the problem. But, by chance, one of my personal patches fixes it! I'll find it soon.

**Comment by tsujan** [comment]
Found it: it was a small patch that I'd applied to my libfm-qt source for a totally different reason: for opening non-executable files whose mimetypes were subclasses of `application/x-executable`. Someone had told me about opening AppImage files by using Arqiver, and I needed that patch for testing :)

Will make a PR soon; should only find a good PR comment.

Thanks a lot for your report and also your persistence!

**Comment by es20490446e** [comment]
Thanks to you! 🏆💪

**Comment by stefonarch** [comment]
I'm late to the show but could just reproduce this bug.

**Comment by tsujan** [comment]
> I'm late to the show but could just reproduce this bug.

I should have asked you for a test from start. Will do in future.
