### ISSUE TITLE
Auto-select incorrectly activates via specific inputs

### ISSUE THREAD

**Issue by joepatricio** [lxqt/pcmanfm-qt#1799]
##### Expected Behavior
Auto-selection should be disabled if auto-select delay is set to 0.
Auto-selection should be disabled if single click open is disabled.

##### Current Behavior
Opening directories via specific inputs occasionally activates auto-selection, regardless of configuration.

##### Steps to Reproduce
1. Open a directory.
2. Use the buttons in the top directory bar to move back from the directory.
3. Open a different directory from Step 1.
4. Repeat Step 2.
5. Repeat Steps 1-4 as necessary.

##### Context
I occasionally use only my mouse to navigate the file system. Keyboard navigation works fine, but it's nice to have options.

##### System Information
* PcManFm-qt version: 1.3.0
* Distribution & Version: Gentoo Linux (Rolling release)
* Qt Version: 5.15.10
* liblxqt Version: None, lxmenu-data 0.1.5 https://packages.gentoo.org/packages/x11-misc/pcmanfm-qt/dependencies

Gentoo does have an unusual installation method, so I'm sorry in advance if this happens to be distro-specific.

**Comment by tsujan** [comment]
This isn't auto-selection. When the user comes back to the parent directory, the child directory will be selected for the user to know from which directory he's come there.

**Comment by joepatricio** [comment]
That's not what I meant. I mean that sometimes it's difficult to open directories in succession this way because it becomes selected instead of being opened. My main problem is that the behavior is inconsistent. Sometimes the file/directory is opened, and sometimes it's selected. Only one of these should be the intended behavior.

https://github.com/lxqt/pcmanfm-qt/assets/75157862/4a65f046-6d31-471d-84e9-d771f10f97c7

**Comment by tsujan** [comment]
Side note: GitHub may have removed my comment because of a problem in it. I add it again:

I use exactly the same settings for years but have never encountered auto-selection.I also repeated what you did in your video several times and didn't find a problem.

If you think there's a missing info, please add it as a separate comment.

Auto-selection selects the next item and deselects the previous ones, unless Ctrl is pressed. Therefore, if you didn't press Ctrl while recording the above video, the issue may about something else. Are you sure that your mouse is OK?

**Comment by tsujan** [comment]
The more I see your video, the more I think it can't be about auto-selection.

First, the above-mentioned argument about Ctrl holds: auto-selection doesn't add to the current selection by itself; like a normal selection, it needs Ctrl for addition.

Second, even if there was an auto-selection, it wouldn't interfere with opening of a folder because auto-selection doesn't involve clicking; it selects an item *on mouseover*, and if the user clicks, the item will be opened.

Hence, I think some piece of info is missing. To make sure that the problem isn't in compilation, you could recompile and re-install `libfm-qt` and `pcmanfm-qt` in this order, and then stop `pcmanfm-qt` from LXQt Session Settings and start it again (or log out and log in).

**Comment by joepatricio** [comment]
I have an incorrect idea of what auto-select does. Sorry for the confusion. What I do mean is the "Control-selection" of the files even when I didn't hold down Control on my keyboard. I have tried using a different mouse. I also tried removing the keyboard and seeing if that's the problem. I still have the issue. I'll try to recompile `libfm-qt` and `pcmanfm-qt` per your suggestion, and report back.

**Comment by tsujan** [comment]
> What I do mean is the "Control-selection" of the files even when I didn't hold down Control on my keyboard.

Yes, that's what I deduced from the video, and it's very strange.

**Comment by tsujan** [comment]
Also, the window manager you use may be relevant. What is it?

**Comment by joepatricio** [comment]
I'm using dwm.

**Comment by joepatricio** [comment]
Recompiling `libfm-qt` and `pcmanfm-qt` did not fix my issue, but it did bring to light how "non-standard" Gentoo's installation is. Somehow, the Gentoo installation is still using `lxmenu-data` instead of the modern `lxqt-menu-data`. With that in mind, and the fact that the issue could not be reproduced, I'm happy to settle this issue here.

**Comment by tsujan** [comment]
Two questions:

 1. What will happen if you click again on an item that is selected instead of being opened?
 2. Do you see the problem with another WM?

**Comment by joepatricio** [comment]
1. Clicking on a selected item deselects the item
2. I could not reproduce this in Openbox.

**Comment by tsujan** [comment]
OK, at last we have a meaningful piece of info. Somehow, dwm doesn't let the correct cursor position be retrieved (it's also called "mouse tracking").

Unfortunately, I didn't find any bug tracker for dwm to see if its users have encountered similar issues. But I consider it very likely that the above-mentioned conclusion is correct: `viewport()->mapFromGlobal(QCursor::pos())` gives a wrong result under dwm.
