### ISSUE TITLE
Unable to merge/overwrite folders on same volume

### ISSUE THREAD

**Issue by robohappy** [lxqt/pcmanfm-qt#1816]
##### Expected Behavior
Folders with identical names should be able to merge together with the cut and paste command or drag and drop.

##### Current Behavior
When attempting to combine folders with identical names, when clicking the overwrite button, I receive a message "Can't move directory over directory" if folders on on the same volume/hard drive. If folder is created on volume 1 and then combined with folder on volume 2 the behavior works correctly and the folders merge. Bug is present with or without liblxqt.

##### Steps to Reproduce (for bugs)
1. Create two folders with identical names on the same volume.
2. Cut and paste or drag drop folder into area with identical folder name.
3. When window appears, press overwrite.
4. Folders do not merge and error message appears.

##### System Information
* PcManFm-qt version: 1.3.0-1
* Distribution & Version: Manjaro KDE Plasma 5.27.8 Unstable Branch
* Qt Version: 5.15.10
* liblxqt Version: 1.3.0-2

![Screenshot_20231008_094246](https://github.com/lxqt/pcmanfm-qt/assets/112583688/8272ec2b-4b2a-492d-9d60-ebcf794789da)

**Comment by tsujan** [comment]
That's how GLib works — that message belongs to GLib, not to libfm-qt.

The folders will be merged if you *copy* the first one, instead of cutting it.

If the first one is cut, they will also be merged when they are on two different volumes, only because, in that case, libfm-qt circumvents GLib by first copying and then deleting the first folder. The reason is the complications that might arise in the target volume: it can be anything, even a Google drive. However, in the case of the same volume, libfm-qt lets GLib do the job; hence that message.

You might want to report it to GLib.

**Comment by Nazosan** [comment]
Sorry to necro this, but this is kind of a serious problem.  Is there really no way to implement some kind of workaround?  I have to keep both pcmanfm and pcmanfm-qt solely for this one single reason, but pcmanfm has a lot of interface differences and for some reason a different set of features missing a few things I kind of need that pcmanfm-qt has.  Clearly GLib isn't going to fix it on their end.

**Comment by tsujan** [comment]
A workaround for this GLib obstacle is merged in git now: https://github.com/lxqt/libfm-qt/commit/6bdec327f23bc408d8f1512d327ef1fd98c8326b
