### ISSUE TITLE
[Feature request] "Open with..." in the context menu of the open folder.

### ISSUE THREAD

**Issue by adrianwk94** [lxqt/pcmanfm-qt#1830]
When I used Dolphin, a very convenient option was to be able to access the "open with..." menu in the folder I had open, simply by right-clicking on an area where there were no files.

In pcmanfm-qt this option is not available, and it forces me to go back and open the folder with the program I want to use (e.g. helix or vs code).

**Dolphin**
![dolphin](https://i.postimg.cc/FsDXX17c/dolphin.png)

**PcManFM-qt**
![pcmanfm-qt](https://i.postimg.cc/zXJYQTX8/pcmanfm-qt.png)

I don't know how difficult it would be to add the option "open with..." in that context menu, but at least for me it would be very useful.

Sorry for my english, I have used DeepL for the most difficult parts.

Greetings and thanks for your time.

**Comment by tsujan** [comment]
While your preferences are respected, this is about different apps, different designs, and so, different habits. I'm afraid, what you suggest is at odds with the an explicit choice made here, i.e., an uncluttered GUI.

In PCManFM-Qt, "Open With..." is for items, not for the folder that's already opened. Unlike what's done in Dolphin and many other KDE apps, we prefer an uncluttered GUI, to prevent confusion (but not as "uncluttered" as GNOME's GUIs).

An "Open With..." menu-item inside an empty area may not feel cluttering or confusing to you because you've got used to KDE GUIs, which may contain lots of widgets. KDE knows no limit in this regard; LXQt does.

Also, to keep our config dialogs manageable, we don't add an option for every possible change.

**Comment by tsujan** [comment]
> I wonder if a custom action is possible for the current folder.

Yes, of course. A custom action can be anything.
