### ISSUE TITLE
[Feature request] Option to copy real paths on gvfs filesystems

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1855]
**Is your feature request related to a problem? Please describe.**

Not all apps are hooked into gvfs or support URLs transparently.

**Describe the solution you'd like**

An option to copy real FS paths instead of URLs.

I.e. when copying a file from an SMB share, one would get:
With copy real paths off (current behavior):
`smb://srvname/share$/subdir/file`
With copy real paths on:
`/run/user/1000/gvfs/smb-share:server=srvname,share=share$/subdir/file`

**Describe eventual alternatives you've considered**

**Comment by tsujan** [comment]
We can rely only on GVFS to give us the info, through the function `g_file_query_info`, and there's no guarantee that it does (for example, it doesn't in the case of Trash sub-directories). So, an option for copying "real path" would be very ugly — it may or may not work.


`libfm-qt` already guarantees that GVFS-related files could be opened *as far as possible* by apps that aren't aware of GVFS. So, I don't see how adding an ugly option can be justified.

**Comment by tsujan** [comment]
Oh, sorry, I'd forgotten this when writing my previous comment:

`g_file_query_info` can block I/O, and its asynchronous counterpart isn't of use in this case because we want to have the path by clicking a Qt action. So, this is not only ugly but also impractical, if not dangerous.

In the case of file opening, the assigned app is launched detached, such that it could wait to load a remote file — or fail — without affecting pcmanfm-qt.
