### ISSUE TITLE
Can not focus a sole item in a dir

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1856]
##### Expected Behavior

When descending into a dir (by keyboard) focus is kept somewhere on the list, preferably on the first item in newly visited dir, or on item previously focused in that dir.

##### Current Behavior

Focus is on the first item, but inactive. Hitting enter key again will not activate the item. Moving focus with arrows will make the focus active again. This is annoying, but is not the main problem.
The main problem is that when there is only one item in the dir, moving focus with arrows is impossible, so it is impossible to select the item with keyboard.

##### Steps to Reproduce (for bugs)

1. Enter a dir containing a single item
2. Try activating this item with keyboard

##### System Information

* PcManFm-qt version: 1.4.0
* Distribution & Version: Debian Sid
* Qt Version: 5.15.10
* liblxqt Version: 1.4.0

**Comment by tsujan** [comment]
Focus is always on the first item. Use space to select it; that's the case with all focused items/widgets, whether in Qt or in GTK.

**Comment by tsujan** [comment]
This is Qt's behavior:

 * `Space` selects the current ("focused") item, while `Ctrl+Space` selects/deselects it. (GTK does that too.)
 * Arrow keys change the current item and select the new one. (in GTK, the first Arrow selects the current item.)

 Activating an unselected (current) item by hitting Enter/Return was a bug that was fixed ages ago.

Your problem is probably about the different behaviors of the first Arrow key in Qt and GTK. If any change is needed, it should be made by Qt devs, not in this or that Qt app; otherwise, the user would experience an inconsistency in Qt apps. Why this small difference exists, I have no idea.
