### ISSUE TITLE
Remote FS: inconsistent permissions and no way to open text files without extension

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1865]
##### Expected Behavior

Files on remote FS (smb:// FS via gvfs in my case) have `rw-` permissions by default (`-rw-r--r-` or `-rw-------`). So nothing is mistaken for a script, and files without extensions can be interpreted as plaintext, so an option to try and open them in a text editor is always available.

##### Current Behavior

Remote files appear to have 000 perms in GUI and no owner/group
![image](https://github.com/lxqt/pcmanfm-qt/assets/4061903/60292cda-0e91-4415-ae5f-3357e70eec63)
But `ls` shows: `-rwx------` and current user and group. Why make remote files executable? Does pcmanfm have any way to influence gfvs mount default permissions? Sadly there is no mention of perms in gvfsd-fuse manual.

Files without extension are labeled as application/octet-stream. So in order to open them in a text editor via GUI one has either to select application manually every time or make an association of application/octet-stream with a text editor which would be unwise.

##### Steps to Reproduce (for bugs)

1. mount smb share
2. inspect a text file without extension

##### Context

Just more woes from SpaceFM migrant who is used to real mounted filesystems.

##### System Information

* PcManFm-qt version: 1.4.0
* Distribution & Version: Debian Sid
* Qt Version: 5.15.10
* liblxqt Version: 1.4.0

**Comment by tsujan** [comment]
> files without extensions can be interpreted as plaintext,

No file is "interpreted"; files have MIME types.

> Does pcmanfm have any way to influence gfvs mount default permissions?

No.

**Comment by Vladimir-csp** [comment]
> No file is "interpreted"; files have MIME types.

Same file on a local FS is recognized correctly as plaintext. So I assume it has to do with avoiding extra reads on remote FS, which means that the issue here is default assumptions about mimetypes without inspecting file content.

**Comment by tsujan** [comment]
> Same file on a local FS is recognized correctly as plaintext.

I know what are you talking about. And you apparently know we have no control over GVFS. Let me expand on it just a little:

libfm-qt does the job of file management based on GLib, and its only GLib that calls GVFS if present. I'm not defending GVFS here, but it has to deal with all kinds of things — from Trash, emblems and "trusted" state to SMB, Google Drive, "admin", "recent://" (this one is useless to us), etc. IMHO, it does that nicely, in spite of its drawbacks. I see it as a gift: you don't have to deal with it directly; you just use GLib.

Apart from that, when a file is on a local FS, its MIME type may be found relatively fast by checking its contents (not by us, but by GLib), while if it isn't on a local FS, that shouldn't be done because, otherwise, it could be seriously interfering.
