### ISSUE TITLE
Shift does not bypass Trash in context menu

### ISSUE THREAD

**Issue by BoannWasHere** [lxqt/pcmanfm-qt#1866]
When I hold Shift and try to delete a file from its context menu, PCManFM-Qt wants to move the file to the trash instead. I thought this convention was not implemented at all, but later discovered that Shift+Delete on the keyboard works fine, bypassing the trash as expected, and it also works correctly from the Edit menu on the main menu bar. It seems to be only the context menu that's not working as expected.

PCManFM in LXDE works elegantly here, changing the visible context menu item between "Move to Trash" and "Remove" in real time as the Shift key is pressed and released.

##### System Information
* PCManFM-Qt version: 1.2.1
* Distribution & version: Debian 12.5
* Qt version: 5.18.5
* liblxqt version: 1.2.0

**Comment by tsujan** [comment]
Shift+Delete is the shortcut. Shift is never intended to do anything with a menu-item.

> PCManFM in LXDE works elegantly here

Not relevant.

**Comment by tsujan** [comment]
> It works perfectly in PCManFM-Qt on the main menu

It's not related to the main menu itself. That action has `Delete` as its shortcut, so that when you press `Shift`, `Shift+Delete` is activated automatically. The context menu doesn't have any shortcut because it belongs to libfm-qt and shouldn't interfere with shortcuts of apps that may use the library.
