### ISSUE TITLE
Emptying trash progress bar is always 100%

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1904]
![immagine](https://github.com/lxqt/pcmanfm-qt/assets/10681413/7e25097d-b775-41b2-9785-832ac2e39c17)

https://github.com/lxqt/pcmanfm-qt/assets/10681413/466ce9d0-9be8-4490-886c-b1564cdd6ac8

##### Expected Behavior

Progress bar grows
##### Current Behavior

Also with many small files it's immediately at 100%
##### Steps to Reproduce (for bugs)

1. Trash some git repository
2. Empty trash

##### System Information

* PcManFm-qt version: 2.*

https://github.com/lxqt/pcmanfm-qt/assets/10681413/466ce9d0-9be8-4490-886c-b1564cdd6ac8

**Comment by tsujan** [comment]
I'm sure I've explained it somewhere a long time ago ;) But here is a detailed explanation:

When you empty Trash with N folders in it, the files that should be processed consist of Trash plus N folders, i.e., N+1. But since each folder can contain many files, the real number of files can be much greater. If we calculated the latter before starting the deletion, a lot of CPU time might be wasted; so, it's calculated on the fly, while files are reached and deleted.

That's also the reason why "100%" is shown: all top-level folders are taken into account instantly.
