### ISSUE TITLE
--execute zsh dont get saved on terminal field

### ISSUE THREAD

**Issue by icf20** [lxqt/pcmanfm-qt#1911]
##### Expected Behavior

get saved

##### Current Behavior

did not get saved
##### Steps to Reproduce (for bugs)

1.
![image](https://github.com/lxqt/pcmanfm-qt/assets/17784575/56461647-e725-438b-a6c7-1c9265ff2dd4)

2.press ok
3. open again
4. is gone

##### Context

i just want to start zsh 

##### System Information

* PcManFm-qt version:2
* Distribution & Version:arch
* Qt Version:6
* liblxqt Version:2

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/issues/1870#issuecomment-1969259717

**Comment by tsujan** [comment]
xfce4-terminal is already supported by libfm-qt, and that's why nothing is saved:

```
[xfce4-terminal]
open_arg=-x
noclose_arg=--hold -x
desktop_id=xfce4-terminal.desktop
```
Of course, you could right click and choose "Open user-defined list" to manually set `open_arg` to `--execute` or `-e`, but that really changes nothing. Anything other than that will make "Execute in Terminal" fail because that argument is only about execution in terminal.

**Comment by isf63** [comment]
Unrelated to LXQt but if you want to change the user shell, run `chsh -s /usr/bin/zsh`. This should open Zsh in any launched terminal emulator.
