### ISSUE TITLE
Backspacing through a search filter loses focus and navigates up

### ISSUE THREAD

**Issue by ssipos90** [lxqt/pcmanfm-qt#1918]
Hi,

I'm having an issue with the directory quick filter (simply start typying to filter).

##### Expected Behavior

When holding down backspace to clear a directory filter, I expect nothing to happen after the last character is removed.

##### Current Behavior

When holding down backspace to clear a directory filter, after the last character, it navigates up.

##### Possible Solution

A way of disabling the behaviour or changing/removing that key shortcut.

##### Context

I often enough search in dirs by starting to type. if I want to clear that search by holding backspace down, after the text is gone, it closes that bottom input and starts navigating up, ending 3-4-5 levels up or even at root.
I couldn't find a way of removing that shortcut in Help > Secret shortcuts 

* PcManFm-qt version: 2.0.0
* Distribution & Version: Manjaro 24.0.1
* Qt Version: Qt 5.15.14
* liblxqt Version: liblxqt 2.0.0-1

**Comment by tsujan** [comment]
See https://github.com/lxqt/pcmanfm-qt/issues/1827, and especially https://github.com/lxqt/pcmanfm-qt/issues/1827#issuecomment-1979386468

**Comment by stefonarch** [comment]
I've to say it happens to me a lot too, still on the way to learn to use Esc instead.

**Comment by tsujan** [comment]
> still on the way to learn to use Esc instead.

Yes, pressing` Esc` is the easiest way, at least much easier than holding backspace.

**Comment by morfikov** [comment]
@tsujan I've also hit this issue. It's not really about the other shortcuts that allow you to close the search. It's more like clearing the text in order to start writing a new one. 

Two cases here to consider:

1. You press the backspace key to remove letters, and you're left with just one letter. What happens if you accidentally press the backspace key two times?

2. People usually don't pay attention to how many characters are in the search box. They just hit the backspace key 'till the box is cleared. I bet you do that too, especially when you use a terminal or some text editor. :smile:

**Comment by tsujan** [comment]
> I've also hit this issue.

There's no issue.

> … especially when you use a terminal or some text editor.

It's neither a text editor nor a terminal, but a transient filter-bar, which you usually don't see in other apps. Just press Esc instead of Backspace.

If you don't want to change your habit, you could use a permanent filter-bar instead.

**Comment by morfikov** [comment]
It's not really a habit, it's rather the common behavior known from other applications (terminals/text editors/whatever has something to do with some text). I know that a file manager is not a text editor, but you operate on text in a text field, so some text rules should apply similar to those in a text editor, like typing the text or removing it -- it should be more or less the same here and there. Imagine, when you press the backspace key one more time in a text editor, and it closes because there's no more text to remove. I think people would start complaining about this. :smile:

**Comment by ssipos90** [comment]
> There's no issue.

I disagree, backspace shouldn't close a text field. Loosing focus, pressing escape, clicking an `(x)` button if there's one is common UX.

**Comment by stefonarch** [comment]
I've to say I agree: backspace shouldn't make you go up folders here. It still happens to me,  as I use it everywhere else to clear search forms and I fail to learn to use Esc for it.

**Comment by tsujan** [comment]
> backspace shouldn't close a text field

And it doesn't. The transient-bar is closed as soon as it's emptied, and it doesn't matter how it's emptied.

> Loosing focus… is common UX.

The transient filter-bar doesn't have focus, to lose it later. And it isn't a "common" thing.

> Imagine, when you hit the backspace key in an empty search box in firefox…

Not relevant. Backspace isn't hit inside the transient filter-bar when it changes the dir to parent.

From now on, I'll reply only to comments that don't include obvious fallacies.

**Comment by ssipos90** [comment]
it's fine to say you don't want to do this because of backwards incompatibility (arguably) and it's your package to maintain and whatever, but all your other arguments are not solid.

if the cursor is inside a text box, it's focused, regardles of whatever cheap technicality you've got going in there and you're using to back your statement. From a user's perspective, the field is focused.

and the fact that people who expect that behaviour comment here and open issues, kind of makes it common.

**Comment by morfikov** [comment]
> > Imagine, when you hit the backspace key in an empty search box in firefox…
> 
> Not relevant. Backspace isn't hit inside the transient filter-bar when it changes the dir to parent.

Like with the CPU -- it runs only one process at a time, but what we (the people) see is thousands of running processes at the same moment in real time... It doesn't really matter where the backspace key is hit (obviously on my keyboard), but the key goes to pcmanfm-qt and when a user holds the key down, it switches (transparently to the user) the context of operation -- first we had removing the text and all of a sudden we get dir path switch... That's madness... We are people not machines...

**Comment by stefonarch** [comment]
Afaik it wasn't notified here:
https://github.com/lxqt/pcmanfm-qt/pull/1999#event-15893632978_
