### ISSUE TITLE
External thumbnails not generated for relative symlinks

### ISSUE THREAD

**Issue by linnabraham** [lxqt/pcmanfm-qt#1934]
I am using the [tmsu](https://tmsu.org/)  program which can show files that are tagged using a keyword as a separate directory.
Tmsu allows to do this command `tmsu mount <mount-point>` which shows a directory within which there are symlinks to actual files. But thumbnails are not shown for the pdf files inside the folder, which are basically symlinks. 

However, Nautilus correctly generates thumbnails.

##### Expected Behavior
Thumbnails are generated

##### Current Behavior
A placeholder image is shown 

##### Steps to Reproduce (for bugs)

1. Install the `tmsu` program
2. Tag any file using any keyword
3. Run the `tmsu mount <mount-point> ` command to show the directory
4. Open the directory using pcmanfm-qt

##### Context

I have files scattered around in multiple directories when I am using Zotero for managing files. I would like to see for example all my books in a single directory. This is because I can quickly identify books using their covers.

##### System Information

* PcManFm-qt version: 2.0.0
* Distribution & Version: ArchLinux
* Qt Version:
* liblxqt Version:

**Comment by tsujan** [comment]
libfm-qt (the library behind pcmanfm-qt) doesn't generate thumbnails for PDF files internally but shows the thumbnails generated by a PDF thumbnailer (see https://github.com/lxqt/pcmanfm-qt/wiki#thumbnails). So, you might want to check which thumbnailer you use and how it makes thumbnails.

Does it happen with PNG or JPEG images too?

**Comment by tsujan** [comment]
> I am wondering if it could be that the mimetype of symbolic links are inode/symlink which is not listed among the mimetypes listed in the thumbnailer file.

libfm-qt automatically handles symlinks by using their targets, but only if their targets are local and not empty.

**Comment by linnabraham** [comment]
By local you mean not on a remote machine right? 

I checked within .cache/thumbnails and could'nt see the thumbnails being generated.
So I guess this might be because of the nature of the symlink or something else. I have filed an issue with TMUS 
https://github.com/oniony/TMSU/issues/287

**Comment by tsujan** [comment]
>  By local you mean not on a remote machine right?

Yes. The internal thumbnailer has no problem with them though.

I've kept the report open because I haven't found time to reread the code and remember its every detail. Although not related directly, it reminded me of https://github.com/lxqt/libfm-qt/issues/643.

**Comment by tsujan** [comment]
OK, I found time to reread the code.

With its internal thumbnailer, libfm-qt uses `g_file_read`, which can handle some non-native paths (e.g., through GVFS). But with external thumbnailers, libfm-qt gives them a native path made out of the URI, because there's no reason to assume that they can handle non-native paths. That path is empty with a non-native URI.

Now, it may also be possible to find native paths for some non-native locations, but that requires using of `g_file_query_info`, which can considerably slow down creation of external thumbnails for non-local files. Since keeping libfm-qt/pcmanfm-qt as fast as possible is a priority, we don't do that. As a result, non-native paths (even when they're local, like inside `trash:///`) don't have external thumbnails.

I don't know how TMSU works, but apparently it gives non-native paths as the targets of symlinks. A file manager like Nautilus may use `g_file_query_info` or a similar function in that case, while libfm-qt doesn't, for the above-mentioned reason.

**Comment by linnabraham** [comment]
Thanks for your comments.  I couldn't follow everything you said but I think I got the gist. So is there any workaround that you could suggest. Or are my only options - 1. Have TMSU return native paths. or 2. Use something like Nautilus?

**Comment by tsujan** [comment]
>  So is there any workaround that you could suggest.

Actually, your report made me play with the code a little last night, and I made an offline change to libfm-qt for testing non-local thumbnails. It worked with SFTP, and I think it should work with SMB too, but I wasn't impressed and don't think it's a good idea, for two reasons:

 * Making PDF and video thumbnails with SFTP was too slow, especially with files > 10MiB (I mentioned that in my previous comment); and
 * I realized that there was already a `%u` option (no explained in https://github.com/lxqt/pcmanfm-qt/wiki#thumbnails), which is for thumbnailers that can supposedly handle non-local files (I don't know of any).

Since most users aren't interested in wasting time for thumbnail making with non-local files, I didn't make a PR. Moreover, knowing nothing about TMSU, I wasn't sure it would work with TMSU either.

So, yes, a workaround is possible in the code, but I really doubt it's worth the required changes.

As for a workaround by users, I can only say that there is `%u`, which can be used instead of `%i` with external thumbnailers that can handle non-local files, if any.

**Comment by tsujan** [comment]
In pcmanfm-qt/libfm-qt, only the target is important, whether the path is relative or not.

**Comment by linnabraham** [comment]
Oh...So I guess the thumbnail generators must be treating it differently.

**Comment by tsujan** [comment]
> So I guess the thumbnail generators must be treating it differently.

Wow, you're right! It's all a matter of relative vs. absolute symlinks. The problem wasn't related to TMSU or non-local files at all :D

I'm changing the title and reopening the report....

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/1002

Thanks a lot for your responsiveness, without which I might not find the issue. Although I had lots of relative symlinks, all of them where handled by the internal thumbnailer.

**Comment by linnabraham** [comment]
Hey.. I am equally thankful to you for being this responsive otherwise I might have given up on the issue.

>  Although I had lots of relative symlinks, all of them where handled by the internal thumbnailer.
  
  Thanks for the clarification. I was wondering if such a basic thing might not have been caught long ago. :-D

**Comment by tsujan** [comment]
> I was wondering if such a basic thing might not have been caught long ago

People usually make symlinks by drag-and-drop, which results in absolute paths.

The issue will be closed automatically when its linked PR is merged; hence reopening it.
