### ISSUE TITLE
After a system upgrade the SD-card is not automatically mounted after rebooting the computer

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1971]
In Lubuntu 24.04 the SD-card was automatically mounted after each reboot of the computer. I could see it in PCManFM-Qt by the eject-symbol in the Side Pane.

After upgrading from Lubuntu 24.04 to Lubuntu 24.10, PCManFM-Qt does not mount automatically the SD-card after each reboot of the computer. When I want to open PCManFM-Qt, then there is first this dialog-box:
```
! Error when getting information for file "/media/...": No such file or directory
OK
```
If I click on OK, then PCManFM-Qt appears, but the SD-card is not mounted because there is no eject-symbol in the Side Pane. If I click in the Side Pane on the SD-card, then appears an eject-symbol. An then the SD-card is mounted.

**Remark I**
After each reboot, before to open PCManFM-Qt, there is in the Panel in "Removable Media" on the right side of the SD-card an eject-symbol.

**Remark II**
After each reboot, before to open PCManFM-Qt, in the file-manager nautilus the SD-card is mounted automatically because there is in the Side Pane the eject-symbol.

**Remark III**
After each reboot, before to open PCManFM-Qt, if I open the editor Geany it seems to be that the SD-card is not mounted because the last opened tabs, that are located on the SD-card, are not shown.

**Preferences**
Both checkbox are activated in Volume:
Mount mountable volumes automatically on program startup
Mount removable media automatically when they are inserted

**System**
Lubuntu 24.10
PCManFM-Qt 2.0.0

**Comment by tsujan** [comment]
> After a system upgrade...

Nothing has changed in libfm-qt/pcmanfm-qt in this regard. Your problem may have another reason.

Make sure you've installed all gvfs packages and checked all options in Preferences → Volume.

**Comment by tsujan** [comment]
I don't have a Debian-based system, but you could find all Ubuntu packages on https://packages.ubuntu.com/. A search showed me that you should install ` gvfs-backends`, which is suggested by the package `gvfs`.

I remember that `gvfs` had a bug in Arch, but now it's fixed in its latest stable version 1.56.1. Ubuntu "noble" has only 1.54.0.

**Comment by ralf3u** [comment]
> A search showed me that you should install  gvfs-backends, which is suggested by the package gvfs.

I did this:
sudo apt install gvfs
And I did this:
sudo apt install gvfs-backends

But both are already installed.

**Comment by tsujan** [comment]
Then the problem isn't there.

As far as PCManFM-Qt/libfm-qt is concerned, an SD-card isn't different from a USB stick or an external hard drive — we don't (and shouldn't) have a single line of code about SD-cards, because their handling is the job of GLib+GVFS.

So, the common sense dictates that the cause of your problem should be somewhere else. Hence closing the report.
