### ISSUE TITLE
An option for the kind of drag&drop

### ISSUE THREAD

**Issue by Baltasarq** [lxqt/pcmanfm-qt#220]
Whenever I _drag&drop_ a file in another **pcmanfm-qt**, a menu is shown (see below) asking whether I'd like to copy, move or create a symbolic link. And that's probably great for some users.

For me, I like the old behaviour (**pcmanfm-gtk2**?) in which dragging and dropping a file would just move it. If done while pressing Ctrl, then pcmanfm would copy it. And I think that doing that while pressing Ctrl+Alt would create a symbolic link.

![pcmanfm-qt](https://cloud.githubusercontent.com/assets/201012/9678844/8195606a-52e9-11e5-9ec1-b09ea1db4e78.png)

Is this already configurable? I think it is not.
Can then this be added as a new functionality?

**Comment by pmattern** [comment]
This would indeed be pretty helpful. Notes:

Feature is already available in PCManFM (GTK).
![pcmanfm_dnd-default-action](https://cloud.githubusercontent.com/assets/9860801/9680798/c1afdea4-52f9-11e5-8554-63782e708b20.png)

Regarding PCManFM-Qt the current behaviour is not limited to d&d between different windows but can also be seen while moving within the right pane pane (copying / moving from left to right pane or the other way around is still [not possible](https://github.com/lxde/lxqt/issues/446)).

To my knowledge the commonly used shortcuts are `Ctrl` to enforce copying, `Shift` to enforce moving and `Ctrl`+`Shift` or `Alt` to create a symbolic link, each superseding the current default behaviour.

**Comment by tsujan** [comment]
Closing because that menu is necessary. An option for its removal wouldn't be a feature but might confuse the use.

**Comment by bennta** [comment]
Maybe I am confused here, but that menu isn't present in the QT version, is it? Right now the default behaviour seems kind of clunky, with no option to configure it (the menu would allow this).

**Comment by tsujan** [comment]
This useful menu doesn't obstruct anything:

![menu](https://user-images.githubusercontent.com/981076/32145992-4619f104-bce6-11e7-96de-b2278acb0753.png)

There are `Ctrl+C`, `Ctrl+V` and `Ctrl+X` for those who don't want to see it.

**Comment by Baltasarq** [comment]
It should be configurable, at least.

**Comment by tsujan** [comment]
> It should be configurable, at least.

I don't think so but reopen this in case someone wants to implement an option for it.

**Comment by aramazano** [comment]
I am, for one, against copying/moving *without* a menu. Because, when there is no menu (and a default action) then the copy/move operation should use heuristics for sensible defaulting. And using heuristics leads to both user confusion and, more importantly, occasional hiccups (wrong defaulting). Doing these file operations without a menu is a "you asked for it, you got it" approach. While this approach may be acceptable in other fields, it can potentially wreak havoc in file management, in the hands of a less experienced user.

For instance;

* You wouldn't *likely* want to copy/move a very large file between different filesystems - more likely you would want to make a symlink. But occasionally you would really mean to copy/move it.

* You wouldn't want to move a critically located file from its directory (for instance some config file) but you *probably* mean to copy it when you DND. So heuristics again should be used.

The list of "probably" and "likely" situations goes on and on. And heuristics are always bound to hiccup now and then. If heuristics are not used, i.e. if DND *always* moves, then you have to count on user diligence, which may not be always there. If you consider all these in file management arena, menu-less file operations are an invitation for unlucky results (particularly for inexperienced, "trigger-happy", or occasionally blank-minded users).

IMHO, "you asked for it, you got it" approach is not suitable for file management.

May be DND menu can be disabled in settings, so that keen users can DND with Ctrl and Alt modifiers (without a menu). But I believe DND menu should be presented as default behavior.

**Comment by tsujan** [comment]
> Doing these file operations without a menu is a "you asked for it, you got it" approach....

I completely agree. It would be a bad "feature".

**Comment by p8q** [comment]
Some consider this menu useful, some annoying.
Depends on the individual workflow.

Nevertheless no one requests removal, but possibility to configure:
drop_default_action={auto; copy; move; ask}

**Comment by tsujan** [comment]
Practically, no user just wants to copy/move/link a file but wants to do one of them at a time. Configuration is wrong in this case.

**Comment by pbvie8956** [comment]
The option to set the default behaviour would be of convenience to people who want to move a lot of files selectively 

For example, I want to sort my music playlist and divide it in several folders. To do that I'm listening to a song and then move it into folder 1, then I listen to the next one and move it to folder 2, et cetera 

In large playlists the time to choose the option 'move' in the dropdown menu adds up really quickly, and it would be convenient to just set the default behavior to 'move' so the user doesn't have to perform an additional action every time, even if it is just to press shift

**Comment by stefonarch** [comment]
For no selection popup there is  `shift+DND `for move, `cltr+shift+DND `for link and `ctrl+DND` for copy.  It's mentioned in Help > hidden shortcuts.

But while testing I see that ctrl+DND opens here a selection area instead of drag and copying. It loks like due to "open files with single click"

**Comment by pbvie8956** [comment]
While holding shift is an option, I can't see the reason why the user wouldn't want to just set it as default

As I noted, holding shift is still an additional action that people might want to avoid while doing a lot of dragging files around, especially since it makes it impossible to only use mouse without having to also use the other hand to press a button on the keyboard

**Comment by tsujan** [comment]
> But while testing I see that ctrl+DND opens here a selection area instead of drag and copying.

It doesn't. You probably didn't press the left mouse button on an item but inside an empty area.

@pbvie8956, as it has be said repeatedly, no option will be added because of personal preferences or habits.

**Comment by tsujan** [comment]
@stefonarch, since I know you use Wayland, I should explain a Wayland annoyance to you:

Under X11, you could press `Ctrl` or `Shift` *after* dragging and immediately before dropping. That's the correct way of doing it, because if you press those modifiers before dragging, they will change the selected items.

Unfortunately, Wayland doesn't "see" any key press after dragging and before dropping (= during DND). So, under Wayland, you have to press a modifier before dragging and mess with your selected items.

So far, I haven't found a workaround for it.

**Comment by tsujan** [comment]
Found a workaround for Wayland :) Will make a PR.

**Comment by stefonarch** [comment]
That's true in wayland, but only when `ctrl` is involved, `shift` works fine.
> You probably didn't press the left mouse button on an item but inside an empty area.

Looks so, after more carefully doing it it works.

We could use middle click for DND and move directly, as it has no action for files.

**Comment by tsujan** [comment]
I also changed "Drag+..." to "Drop+..." in https://github.com/lxqt/pcmanfm-qt/pull/1701 to emphasize that it's better to press modifier(s) before dropping — if they're pressed before dragging, they might easily mess with item selection (I think *that* was what you saw), and not only in pcmanfm-qt but also anywhere in any app.

**Comment by tsujan** [comment]
> Looks so, after more carefully doing it it works.

That's my point: there's no need to do it carefully :) It's enough to press modifier(s) before dropping.

**Comment by mtroberts** [comment]
Hi, I appreciate this is closed, but I would add to the discussion, that almost every other file manager moves files by default and does not show a popup. 

I understand your reasoning for different default behaviour but I do think there should be an option to enable the "standard" user experience. The extra click is really is quite a nuisance and needing to hold a modifier key is far from ideal when I'm working with archives in particular.

**Comment by David96cz** [comment]
Hi, I am also one of those who would totally appreciate a configuration option which would turn this menu down in X11 LXQt. Basically any other file manager on Linux, same as Windows or macOS works simply this way: When drag&dropping a file between directories on the same drive, it moves the file. When drag&dropping between directories being on a different drive, it makes a copy. As simple as that... Idc how deep in pcmanft-qt settings it would be to avoid users from accidentally turning the menu off, but I think there should be an option. Thanks!

**Comment by stefonarch** [comment]
I would be +1 for an option too. 
With touchpad, tap and drag and draglock enabled there is no way to use ctrl|shift+DND: the popup opens always up. It does work only with the  left button pressed on the touchpad which is quite acrobatic.
