### ISSUE TITLE
Using DND to add bookmarks does not work sometimes.

### ISSUE THREAD

**Issue by PCMan** [lxqt/pcmanfm-qt#299]
As title.
Adding bookmarks via DND does not work sometimes.
This needs further checks.

**Comment by r-a-v-a-s** [comment]
It never works for me. Is there a case where it consistently works?

**Comment by pmattern** [comment]
It seems drag & drop to topic "Bookmarks" in the left pane in "Places" view is only working when at least one bookmark is already preexisting.

(In addition some fiddling may be needed in order to get the item to be added into the right position which seems to be depicted by a horizontal line:)
![pcmanfm-qt_bookmarks-vs-dnd](https://cloud.githubusercontent.com/assets/9860801/15806947/ddd23300-2b4f-11e6-9f0c-f63cba5a7228.png)

Same findings running recent VCS checkouts on Arch Linux as well as release 0.10 on Debian stretch or openSUSE Tumbleweed from OBS repository `X11:LXQt`.

**Comment by r-a-v-a-s** [comment]
Ah yes... It requires very precise placement for the single line to appear.

**Comment by r-a-v-a-s** [comment]
Is a file or folder supposed to be transferred to the bookmark when it is framed?
Nothing seems to happen.

**Comment by tsujan** [comment]
@PCMan 
Here, bookmark DND works when the drop point is *not* on an already existing bookmark; if it is on a bookmark, nothing will happen. I don't see this as a bug but if you do, which behavior do you expect instead? Should another bookmark be created below/above the target or a copy/move dialog be shown?

**Comment by tsujan** [comment]
Superceded by https://github.com/lxqt/pcmanfm-qt/issues/987
