### ISSUE TITLE
Trouble with consecutive searches

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#456]
When search is done consecutively in the same tab (by changing the search string manually and hitting Enter, for example), there is no way to return to the original tab other than by clicking the back button multiple times.

That's while in Dolphin (without baloo), the tab can be restored after consecutive searches by clicking the close button.

**Comment by pmattern** [comment]
I'm just wondering whether I understand what you have in mind here.
If so, the problem is already manifest after the first search, isn't it?
Also, it is possible to return to the "original tab" by hitting `Alt+Left` one or more time(s) as well, no? (Obviously this wouldn't fix the problem you're pointing out here.)

On a side note I for one still stick with the proposals made [in the PR introducing the search feature](https://github.com/lxde/pcmanfm-qt/pull/193#issuecomment-121016470).
Refraining from closing the search window upon performing a search, see section "general", could basically represent a way to fix the problem discussed here, too.
(The other items should probably go into one or more issues on their own.)

**Comment by tsujan** [comment]
Let me explain it step by step:

(1) Open a directory and search a text in it.
(2) Change the search string in the path bar and hit enter.
(3) Repeat (2) several times.

Now, you can't return to the directory unless you click the Back button several times.

When coding, I need to find strings in the code again and again. Of course, I can open the directory in question twice (and that's what I did) but the way pcmanfm-qt handles searches isn't practical.

In contrast, Dolphin's search is really handy. After consecutive searches, I just click the Close button on the search bar and the directory will be shown. And this is just one example.

**Comment by tsujan** [comment]
libfm-qt's search is handy but has basic problems -- like the lack of file monitoring. Until another way of searching is found, this won't change.
