### ISSUE TITLE
Option to retain previous state

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#467]
An option to retain previous state (tabs and last opened directory) would be a fine convenience.

**Comment by MggMuggins** [comment]
Definitely need to be configurable, so that it wouldn't do this by default. Are there appropriate files to store this data already?

**Comment by tsujan** [comment]
This is ambiguous because, in the case of pcmanfm-qt, several windows can be opened at the same time. There's a desktop mode too. In another context and for a text editor, I solved the problem by saving the list of all opened files in all windows but here, with a file manager, I don't think it's a good solution.

Moreover, the question arises as to whether a list should be saved automatically when a window is closed, or when all windows are closed, or only the user should save it.

**Comment by AcarBurak** [comment]
The last closed window's state should be retained I guess. SpaceFM has it as well as the desktop mode and I've used it with the desktop mode without any issue or confusion. It's a simple feature of it. yefm had it as well if I recall correctly.

**Comment by tsujan** [comment]
"window's state" is ambiguous in this report -- as said before. Window geometry? It can be saved already. The folders opened in the last window? Now that we have a split view, it'll be very complex and I don't think it'll be worth the effort.

If you find a clear description, without referring to elementary apps like SpaceFM, please open another issue.
