### ISSUE TITLE
Rubber-band selection is missing from Compact/Detailed views

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#521]
that is not part of the displayed  row.

Reason: try to mark some files in detailed view with mouse only :)

**Comment by tsujan** [comment]
I don't get it. This is the detailed list view and it seems OK to me:

![dlv](https://user-images.githubusercontent.com/981076/27771929-477fa7bc-5f6e-11e7-81c3-d709838d0990.png)

**Comment by agaida** [comment]
maybe a video helps https://youtu.be/Gfdv0rgrjrg

**Comment by tsujan** [comment]
Got it but it doesn't seem to me as a problem because although the selection can't be done in that way in the detailed view, SHIFT and CTRL can be used without problem. On the other hand, IMO, adding an empty space to the right or left (if possible at all) would give the detailed view a weird and unprofessional look.

**Comment by tsujan** [comment]
Anyhow, my opinion isn't important in this case because I never use the detailed list view ;)

**Comment by agaida** [comment]
![empty_space](https://user-images.githubusercontent.com/1162845/27773116-ba97d7fc-5f72-11e7-8ff6-cd0f1165ad14.png)

Thinking about something like that

**Comment by agaida** [comment]
and i didn't see it as a bug and top priority - but when one has an idea to implement it and there is nothing important to do left - why not, a little bit polishing wouldn't hurt. To be honest, it was a bug in the debian tracker - and i closed because of the points you mentioned. a) it is possible b) the implementation is not so lucky (aka horrible) at this point. But there is no bug.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853201

**Comment by tsujan** [comment]
Dolphin does it with small spaces above and below each item but those spaces aren't easy to use at all -- SHIFT is easier.

I'll think about it but no promise, because there are lots of things more important than this.

BTW, this kind of selection can be called "selection with rubber-band" (ubber-band = that translucent, resizable rectangle).

**Comment by tsujan** [comment]
I use this opportunity and propose a list of what is better to be done, IMHO, before implementing features like this (not necessarily in the order of their relative importance):

● Fixing important bugs like https://github.com/lxde/pcmanfm-qt/issues/508;
● Inline renaming (ready for a PR -- https://github.com/lxde/pcmanfm-qt/issues/468);
● Custom actions order (ready -- https://github.com/lxde/pcmanfm-qt/issues/438);
● Better search dialog settings (almost ready);
● Custom folder icons (ready);
● Bookmark icons to custom folder icons (ready);
● Graying out cut files (https://github.com/lxde/libfm-qt/pull/88 -- a good work that should be reviewed and tested);
● Complete independence from libfm and menu-cache;
● Miller columns (not started yet and perhaps, *very difficult* -- https://github.com/lxde/pcmanfm-qt/issues/465);

And who knows what else?

**Comment by fulalas** [comment]
@tsujan, I would like to also suggest these:

- Shorcuts can't be typed as soon as session is loaded (critical IMO) https://github.com/lxde/lxqt/issues/1301
- Search results dialog isn't refreshed after removing files https://github.com/lxde/pcmanfm-qt/issues/491
- Give option to stop deletion of files if an error occurs https://github.com/lxde/pcmanfm-qt/issues/512
- Spacing between files in 'Detailed List' view is incoherent https://github.com/lxde/pcmanfm-qt/issues/516
- Default settings/visual improvements (especially items 2, 5 and 6) https://github.com/lxde/pcmanfm-qt/issues/493

**Comment by tsujan** [comment]
@fulalas Thanks! I'll use this page as a reminder.

Yes, there are lots of work to do, some of which aren't as simple as their descriptions. Also, there are lots of work already done but wait for previous PR's to be merged.

**Comment by tsujan** [comment]
@agaida

With a simple change, it's quite possible to let the user do as in the following screenshot whenever he/she wants to select items (there's an optional space on the right, as you suggested):

![screengrab-20180416-235109](https://user-images.githubusercontent.com/981076/38830776-9a0b8fc2-41d2-11e8-8069-f079e0f8e360.png)

But, unfortunately, the selection behavior will be erratic and, I think, that's because of a Qt bug. Theoretically, it should be possible to fix the problem in our subclass but how much work would be required, I still have no idea.

**Comment by agaida** [comment]
its a start :)

**Comment by tsujan** [comment]
Important note:

Actually, this is more than a simple feature request and reveals a deeper problem: We have no rubber-band selection (= the rectangle that's created by pressing the left mouse button and moving the cursor) in compact and detailed list views. Dolphin has them everywhere.

**Comment by tsujan** [comment]
Now that the problem of column customization is solved, back to this:

The compact view does it without needing a rubber-band (although a rubber-band would be nicer with the compact view). So, the problem is either in Qt's tree view or in ours -- other views are list views (`QListView`). This old bug report exists: https://bugreports.qt.io/browse/QTBUG-3042 (with the Out-of-scope "resolution" -- weird term) . But it doesn't mean that we couldn't have a rubber-band. It needs more investigation.

**Comment by tsujan** [comment]
Update:

It seems possible. This is with a very inefficient fast-food code:

![selection](https://user-images.githubusercontent.com/981076/52153957-37cff600-2691-11e9-8781-e651afea881a.png)

When I'll find time to change this proof-of-concept to a usable code, I don't know.

**Comment by tsujan** [comment]
@agaida Because you opened this:

I succeeded in implementing an effective rubberband selection. But:

(1) The code is somehow complex but not big (actually, it's relatively small). It couldn't be made simpler. The reason was that Qt didn't support that kind of selection for this kind of view and so, I had to enforce it (an entertaining challenge; nothing more).

(2) Even if it goes into the official source, there will be a problem. Adding a right margin to the detailed list view would make it ugly and untidy. Still, with previous PR's, the user could choose custom column resizing and add a right margin easily. So, rubberband selection will be limited to the latter case.

Now, my question: Is it good to add it?

**Comment by tsujan** [comment]
Answering my own question:

The rubber-band selection can be added to the detailed list view because it's cool, its code is adapted from Qt itself, and it's limited to specific functions dealing with mouse events, so that it could be removed easily if it's implemented in Qt > 5.

**Comment by agaida** [comment]
Cool - but a bit nitpicking - what if we leave a right margin with auto-resize?

**Comment by tsujan** [comment]
It would be ugly. Contrary to appearances, the problem wasn't about that margin but the lack of rubber-band selection with tree-views (yes, contrary to appearances again, the detailed list is a tree-view). But I'll think about it later.

Now we have a nice rubber-band where others don't; one problem at a time ;)

**Comment by agaida** [comment]
as i said - nitpicking :P

**Comment by tsujan** [comment]
> as i said - nitpicking :P

It's really a design problem to solve. A right margin or a configurable space between rows. It might not be easy to implement but should be investigated.
