### ISSUE TITLE
Remember user-set column sizes and hide columns in detailed list view globally

### ISSUE THREAD

**Issue by kargaroc** [lxqt/pcmanfm-qt#623]
In PCManFM (both versions), columns in the detailed list view don't remember their size if I have resized them, and all it takes to make it forget is to move a different directory.  Restarting also makes it forget.

The ideal behavior should be to remember the settings globally, just like all of the other options.

Also, this should also apply to https://github.com/lxde/pcmanfm-qt/issues/622

**Comment by tsujan** [comment]
The columns widths are chosen so that the longest strings be visible as far as possible and with regard to the window size. They may be different for different folders.

However, since Dolphin has this feature, I see no reason why we shouldn't have it (although I still don't know how easy/hard its implementation might be).

**Comment by zombiehoffa** [comment]
I would love to see this as well, as it also resizes whenever you delete something in the directory, which gets kind of irritating when cleaning out old directories with lots of files.

**Comment by tsujan** [comment]
OK, this isn't as easy as it seems and will take some time because, unlike Dolphin, we don't (want to) add an extra empty column (it's ugly). It can be divided into these tasks, at least:

 1. Allow custom sizes for columns in the code.

I did it with hard-coded sizes and its seems to work.

  2. Add code for saving and restoring custom sizes.
  3. Add a right-click menu to the header or an option to pcmanfm-qt for automatic vs. custom sizes.

**Comment by tsujan** [comment]
Update:

None of the tasks mentioned in my previous comment is a problem. The real problem is *the flickering header-bar on changing directory*. It already happens with the detailed list view (texts may jump) and I don't know why it isn't reported (I don't use that view). So, far, I tried several methods for suppressing it but to no avail :(

**Comment by tsujan** [comment]
The part related to libfm-qt is done. It has effect on a single window:

![columns](https://user-images.githubusercontent.com/981076/51828505-f641f280-2300-11e9-82a4-3e48d4c75a84.png)

The pcmanfm-qt part will be straightforward: save and restore hidden/widths settings.

**Comment by tsujan** [comment]
The PRs wiil be made together because the first one will be incomplete without the second one. It might take a while because I should make another PR related to LXQt config.

**Comment by tsujan** [comment]
Advanced users could apply these patches, with this order, and test custom columns:

https://github.com/lxqt/libfm-qt/pull/352
https://github.com/lxqt/libfm-qt/pull/355
https://github.com/lxqt/pcmanfm-qt/pull/888
https://github.com/lxqt/pcmanfm-qt/pull/889
