### ISSUE TITLE
Distinguish hidden files/folders visually

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#632]
For instance, "disabled normal text" palette colour or "(active or inactive or disabled) less bright" palette colour etc.

**Comment by tsujan** [comment]
Yes, this feature makes sense but its implementation might not be as straightforward as it seems ;) It might need to be done at a deep level.

Will look into it.

**Comment by tsujan** [comment]
And please note that many people use dark themes/styles! So, we should be cautious about "less bright".

Also, the question arises as to whether we should change the text color (cautiously) or we should gray out icons. Since we already gray out icons for cut files, the second method would be tricky.

**Comment by AcarBurak** [comment]
I too use dark colours, or rather semi-dark ones, but I understand that it would be not as straightforward. It would be for me, since I use qt5ct and I can set "less bright" as anything I'd like. Thanks for consideration.

**Comment by tsujan** [comment]
@AcarBurak I really don't know if changing the text color alone would be practical. The text already starts with `.`, so that the user knows which item is hidden and which one is not by looking at its text.

I'm thinking about giving the painter a little translucency -- as in Dolphin -- but in that case, cut files couldn't be distinguished from hidden files. Dolphin really *grays out* cut files while we make their icons translucent.... That was why I said it wasn't straightforward.

**Comment by tsujan** [comment]
@AcarBurak What do you think about this: Drawing hidden items *as if* they're disabled? A screenshot that shows a part of my home directory with hidden files (some of which are included in the file `.hidden`):

![hidden_as_disabled](https://user-images.githubusercontent.com/981076/34461949-f6a4bade-ee4d-11e7-8fc7-5ccd1ad70a1d.png)

**Comment by AcarBurak** [comment]
Looks fine.

> I really don't know if changing the text color alone would be practical. The text already starts with .
Right, but it makes a difference; I know that from the old qtfm and maybe spacefm too. Icon translucency may be fine too. This is a minor enhancement as you know better, so please don't bother if it's troublesome.

**Comment by tsujan** [comment]
On second though. people may like to see their hidden files by default and showing them as disabled items would be weird -- if not annoying -- in that case.

What about italic font for hidden files? Another screenshot:

![italic](https://user-images.githubusercontent.com/981076/34462146-116f8160-ee52-11e7-8502-bf0a1abbe1f8.png)

> This is a minor enhancement as you know better, so please don't bother if it's troublesome.

This is a good feature, IMO. I always thought about it but other jobs didn't let me implement it. I see this as an opportunity to not forget it again ;)

**Comment by AcarBurak** [comment]
Italics mignt be a good compromise; how does it look in column view?

**Comment by tsujan** [comment]
> Italics mignt be a good compromise;

Good. I'll go with it.

> how does it look in column view?

It' independent of the view: hidden file names are in italic.

**Comment by AcarBurak** [comment]
> It' independent of the view: hidden file names are in italic.

:) Sure; I meant the subjective visual experience. Anyway, thank you.

**Comment by tsujan** [comment]
Two screenshots with other views:

![1](https://user-images.githubusercontent.com/981076/34462623-1ecfca58-ee5d-11e7-9513-4654bfeabad4.png)
![2](https://user-images.githubusercontent.com/981076/34462625-23fe1e26-ee5d-11e7-8c51-2158fccc61fa.png)

**Comment by tsujan** [comment]
I think that making the text or icon pale/translucent presupposes that users never show hidden files by default. IMHO, an italic font is the best choice but if anyone has an objection, please tell me!

**Comment by AcarBurak** [comment]
Thank you. Well… to my eyes, not sure if it's worth –to be honest.

**Comment by tsujan** [comment]
> not sure if it's worth –to be honest.

On the one hand, the code is very simple. On the other hand, hidden files should be distinguished in a neutral way. As I said above, using pale/translucent text isn't neutral, IMO. But that's just *my* opinion ;)

**Comment by AcarBurak** [comment]
Some Qt palette colours (Bright, Less bright, Dark, Less dark, Bright text) seem to my noob eyes to be playing very minor roles, so I've thought hidden file/folder text could be set to one of them. Not good?

**Comment by tsujan** [comment]
>  I've thought hidden file/folder text could be set to one of them. Not good?

There are `QPalette::Light`, `QPalette::Midlight`, `QPalette::Dark` and `QPalette::Mid`. The problem (IMO) is:

(1) We should first check if the style is dark or light -- we shouldn't use `QPalette::Dark` with a dark style, for example. This extra check doesn't seem good to me.

(2) In some styles, those palettes may be either too pale or not very different from `QPalette::Text`.

(3) We can use text translucency instead of a different palette but that could result in texts that wouldn't be very readable for all users or with all styles (some styles --  some Kvantum themes, for example -- may already have semi-transparent texts, so that a translucent text couldn't be recognized as such).

That's while italic is always italic. After a while, the user will get used to the idea that italic names are about hidden files -- as I have, after 15 min. ;)

**Comment by AcarBurak** [comment]
Sorry, forgot all such things.

**Comment by tsujan** [comment]
> Sorry, forgot all such things.

Don't be sorry! I encountered them in practice ;)

**Comment by palinek** [comment]
Just a thought after reading this all... can it be that the default font iz already italics? Or the used font doesn't support ifalics at all?

**Comment by tsujan** [comment]
> can it be that the default font iz already italics?

Very rare and a bad choice for a theme.

> Or the used font doesn't support ifalics at all?

Again, that would be a bad font to use. We shouldn't take responsibility for bad designs by others, IMO.

**Comment by aramazano** [comment]
I don't have a clear idea as to how hidden files should be distinguished (so far, making them italic sounds fine). But whichever way it is done, I think it should be done with minimum amount of added code.

I belive some design challenges of lxqt surpasses that of KDE in this regard, mainly because lxqt has an additional challenge that KDE misses. That is, a lean design with minimum footprint.

For KDE, it is rather an easy design decision of adding whatever code that's deemed appropriate, but for LXQt it is much harder a compromise, when you have to KISS (keep things simple) and curb the bloat too.

**Comment by tsujan** [comment]
@aramazano Thanks for your comment!

Making hidden files look disabled or making their texts italic are both easy to code and neither adds to pcmanfm-qt's weight/CPU usage. However, for the reasons I mentioned above -- and especially for the sake of readability and compatibility with all styles -- I think the italic text is the best choice. If it weren't for cut files, I'd propose a little translucency. Removing icon colors would add a lot of extra code and wouldn't be worth the result, IMO.

As @AcarBurak mentioned, this isn't an important feature. If the session font is italic or if the font doesn't have an italic variant (almost never the case), no disaster will happen.

**Comment by tsujan** [comment]
Back to this with a new perspective:

After encountering and discussing a bad code in Qt Creator elsewhere, I think making hidden items look disabled would be a big mistake. Qt GUI programming should follow Qt standards laid down in the Qt doc as far as possible (although some Qt devs contradict them); otherwise, it would be a mess -- as it is in some apps. The disabled look is for disabled widgets/items, i.e., the elements with which the user can't have any interaction.

A grayed out cut file is acceptable in that it shows a pending operation. A grayed out hidden file isn't so.

**Comment by AcarBurak** [comment]
Agree. Besides, seemingly it's not worth the trouble as no one else asks for it as well.

**Comment by tsujan** [comment]
@AcarBurak There's no trouble at all. The patch is ready, it's simple, and I'll  make a PR soon. My point was that italicizing was the bast choice for yet another reason.

**Comment by AcarBurak** [comment]
All right, thanks.

**Comment by tsujan** [comment]
Interestingly, pcmanfm-qt has a disabled option about icons of hidden files:

![hidden](https://user-images.githubusercontent.com/981076/40459640-c3e33a2c-5f17-11e8-9ce3-31a048bbcc0e.png)

I think, by "shadows", something like https://github.com/lxqt/pcmanfm-qt/issues/632#issuecomment-354604624 was meant.

Although I still think it's wrong to do so, an optional "mistake" may be harmless. So, reopening...

**Comment by AcarBurak** [comment]
Haven't got the latest pcman in the Arch repo yet.

**Comment by tsujan** [comment]
It's a very old option that's made hidden in the code, with this comment:
```c++
// FIXME: Hide options that we don't support yet.
```
I added support for a similar option today (full names -- still a PR); so, I thought why not supporting this one too?

**Comment by AcarBurak** [comment]
Thank you:)

**Comment by tsujan** [comment]
To justify it, I reply to [one of my previous comments](https://github.com/lxqt/pcmanfm-qt/issues/632#issuecomment-375828126):  Take it easy! The text isn't disabled but italic. Moreover, cut files have semi-transparent icons but this is about icons with disabled look.

**Comment by tsujan** [comment]
Second update:

It became possible with small changes and as an option. The hidden icons look disabled but (unlike in Dolphin) the texts are enabled to show that this isn't about the disabled state. With Fusion:

![hidden_shadowd](https://user-images.githubusercontent.com/981076/40516486-120037ce-5fc6-11e8-8d63-12e813d490b9.png)
![hidden_shadowd1](https://user-images.githubusercontent.com/981076/40516495-16dfd768-5fc6-11e8-9988-9ecf3e10a983.png)

I'll test it for a few days before PRing.

**Comment by AcarBurak** [comment]
Seems fine.
