### ISSUE TITLE
Reduce the space between folders and files in list view

### ISSUE THREAD

**Issue by hollysheep** [lxqt/pcmanfm-qt#713]
Hi,

i'm on pcmanfm-qt 0.12.0 on xubuntu 18.04. is it possible to reduce the space between files and folders in list view (or general)? when i highlight some files and/or folders there is a little space between the highlightes files. until now i used dolphin, here there is no space between the files. i think this is space-wasting, or? in the settings i can only set up something for the symbol view.

**Comment by tsujan** [comment]
> s it possible to reduce the space between files and folders in list view

This means you want a more compact list view, which is impossible because, contrary to what you said, there's no space between items in the list view -- not even in the old version you have.

Actually, users might want a space between items to select them more easily (https://github.com/lxqt/pcmanfm-qt/issues/521).
