### ISSUE TITLE
pcmanfm-qt path-button switching

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#732]
if switching from buttons to textfield it will mark the text - can be considered bad.

Reason: Try to paste a longer sftp, davs or smb path into - bingo will not work, because everytime i leave the entry field it switch back to path buttons - and every time i re-enter the entry field the content i was about to paste is overridden.

**Comment by tsujan** [comment]
I don't agree.  Pasting can be done by using the clipboard selection and it isn't good to remove a useful feature because of our habits.

**Comment by agaida** [comment]
try to use this with qlipper ...

**Comment by tsujan** [comment]
Clicking inside the path bar copies the path to the primary selection. Removing that feature to paste from the primary selection would mean that we remove pasting in one case and add it to another, while there's no reason to see the second usage superior to the first one. We can say it's simply a matter of habit.

**Comment by agaida** [comment]
just don't put it into the primary - make a copy button for it or make this optional - and again: I want to be able to enter the control and just paste the content of my primary selection into it - second choice: Don't replace the component with the buttons if i leave the window - in that case i could stay in the path component, fill my primary selection with the things i want and paste it into. In the current state the path component is nearly useless and break common workflows.

**Comment by tsujan** [comment]
> Don't replace the component with the buttons if i leave the window

There's an option for showing the location bar instead of path buttons.

> In the current state the path component is nearly useless and break common workflows.

On the contrary, it's quite useful because you could paste the path quickly into, for example, a terminal -- that's what I do a lot: habits again ;)

> or make this optional

That may be the best compromise, IMO. The only obstacle is that it should be done in libfm-qt's level first.

I think, if there's an option for not copying path to the primary selection, it should also prevent selecting the path in the first place; otherwise, it'll be counterintuitive (in Linux, when a text is selected, it's supposed to be copied to the primary selection).

**Comment by agaida** [comment]
There's an option for showing the location bar instead of path buttons. - Where?

**Comment by agaida** [comment]
Ok, found it - well hidden

**Comment by agaida** [comment]
but an option for the copy behaviour would still be useful

**Comment by tsujan** [comment]
> but an option for the copy behaviour would still be useful

It could be done by 2 PRs. I added it to my TODO list for pcmanfm-qt.
