### ISSUE TITLE
Double-clicking on the Places separator should auto-adjust it

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/pcmanfm-qt#735]
When double-clicking on the divider/separator for the Places pane, like many other apps, it should auto-adjust to the containing text.

Optionally, a config option which automatically adjusts all the time based on the text would be great too.

Thanks.

**Comment by tsujan** [comment]
> .... like many other apps, it should auto-adjust to the containing text.

Qt has no such property. Actually, most apps don't implement it for the following reasons:

First of all, the user could move the handle and pcmanfm-qt will remember its place.

Second, in your case, the items may have short names. In other cases (mine included), some of them have very long names and it isn't good at all to add such a mechanism.

I think this can be closed because the requested feature doesn't add anything useful.
