### ISSUE TITLE
Folder-Properties: Right-click -> “Properties” does not show number of files in folder?

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/pcmanfm-qt#776]
When right-clicking on a folder and selecting `Properties`, the old `PCManFM` (without Qt) was showing the number of contained files inside this folder.

However, in `Properties` the new `PCManFM-Qt` does only display the size of the marked folder (including its content), but **not** the number of included files (what is important as well).

Is there any option to activate displaying of the number of files? In best case even regular files and hidden files as separated amounts (see screenshot)?

![screenshotnew](https://user-images.githubusercontent.com/38689554/45598109-d64f0980-b9c5-11e8-96d6-ebaf8a2089ba.png)

Thanks a lot for your great efforts!

**Comment by tsujan** [comment]
This will be a good feature if it doesn't require a lot of CPU time. I should first know why PCMan didn't implement it here.

**Comment by tsujan** [comment]
I took a look at libfm-qt's `TotalSizeJob`; it already has the method `fileCount()`. So, adding the numbers of files shouldn't require extra resources. I think it was just forgotten.

Adding the number of hidden files might also be possible later but I don't think it's a good idea because:
 * All files may be shown in pcmanfm-qt (`Show Hidden`), while the Properties dialog is not limited to pcmanfm-qt;
 * Hidden files aren't limited to those whose names start with a dot and that can complicate things; and
 * IMHO, it isn't so important to be worth the effort.

Of course, this is *my* opinion; moreover, it could change later -- although that isn't so likely ;)

**Comment by EarthlingX** [comment]
Thanks a lot for your quick reply! :-) You are right: When thinking about it the number of hidden files is not necessary that much... :-)

**Comment by tsujan** [comment]
Happy to know you agree :)

BTW, "Number of files" may not be a good label. The user may ask, "is the right-clicked folder is taken into account too?" IMO, "Contains: 201 files", for example, may be better.

**Comment by softwaresale** [comment]
Is this feature going to be implemented? I'd be willing to take a stab.

**Comment by tsujan** [comment]
Actually done:

![filenumbers](https://user-images.githubusercontent.com/981076/45599150-f0a3da00-b9fb-11e8-84cc-2f666e49df5d.png)

However, because of the way `TotalSizeJob` works, it shows the total number of files/folders -- subfolders and their files included. That's acceptable to me but is it what we want?

**Comment by tsujan** [comment]
OK, I think it's reasonable to show the number of all files because this info isn't shown elsewhere and if the user wants to know the number of *immediate* files, he/she could open the folder. The PR is made.

**Comment by softwaresale** [comment]
Sounds good. I like that idea.

**Comment by baptx** [comment]
In which version of LXQt was this feature added? I am using LXQt version 0.13.0 in Ubuntu 18.10 and I cannot see the number of files in the properties.

**Comment by tsujan** [comment]
> I am using LXQt version 0.13.0 in Ubuntu 18.10 and I cannot see the number of files in the properties.

You're joking... Lubuntu has the best LXQt support on the planet -- perhaps, in the whole solar system.

**Comment by agaida** [comment]
Only for the records - no, i didn't capture @tsujan :P

**Comment by tsujan** [comment]
Yes, I'm here. A nice property of facts is that they're independent of the person who tells them.

**Comment by baptx** [comment]
So does anybody have an idea for my question? It has nothing to do with Ubuntu I guess...

**Comment by baptx** [comment]
I guess it has been added in version 0.14 so it has nothing to do with Ubuntu...
