### ISSUE TITLE
Minor issues with Desktop Icons and Empty trash

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#811]
We should have a second look at:

![image](https://user-images.githubusercontent.com/1162845/48162383-36cf3880-e2dd-11e8-9ecf-d8aecb3b32cb.png)

![grafik](https://user-images.githubusercontent.com/1162845/48162436-5fefc900-e2dd-11e8-8fb3-80d9c2c763ba.png)

![grafik](https://user-images.githubusercontent.com/1162845/48162598-cffe4f00-e2dd-11e8-89ca-f4d7370fcf19.png)

![grafik](https://user-images.githubusercontent.com/1162845/48162844-6599de80-e2de-11e8-9f65-e75b834a0ba4.png)

![image](https://user-images.githubusercontent.com/1162845/48162962-b4e00f00-e2de-11e8-9a32-f65d4264ae6e.png)

Finally all things are good :D

**Comment by tsujan** [comment]
I don't think this can be related to desktop; it should happen from pcmanfm-qt's window too because the trash is emptied exactly in the same way.

However, those error messages shouldn't be shown once the user clicks "Ignore". I'm not sure that they are needed at all when the trash is emptied correctly in the end.

**Comment by agaida** [comment]
i had to click several times - so yes, trash seems to be empty now, we should leave it in until we are dead sure to know whats going on.

**Comment by tsujan** [comment]
I'm sure I've seen it before trash on desktop.

In theory, the trash on desktop shouldn't have any difference from the trash on the side-bar except for how its appearance is updated, which depends on a few factors related to desktop (very different from the side-bar). But the job is the same and it's done in the same way.

However, theory and practice aren't always the same. A black magic -- as you call it --- can happen ;)

**Comment by tsujan** [comment]
As for "black magic", I really saw one when making the PR: I pasted a desktop file on desktop -- I'm 120% sure it was there because checked it in the terminal and Dolphin -- but pcmanfm-qt didn't show anything, not even after a restart. I don't know the real cause but concluded that Qt file removal methods should not be used in pcmanfm-qt/libfm-qt (added a comment to the code about that).

**Comment by agaida** [comment]
the reason could be Hidden or ShowIn or ShowOnlyIn - didn't know if we check it

**Comment by tsujan** [comment]
I tested with hundreds of files and the desktop trash was very inefficient. The reason is that the number of writes to the desktop shortcut can be too high (the desktop updates don't show that). I should find a way to reduce that number considerably -- in every 200 ms, for example.
