### ISSUE TITLE
Remember custom positions of deleted desktop items until next session

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#819]
and how to mess it up

### Fine:
https://youtu.be/5o3NTqWHuMo

### Not so fine:
https://youtu.be/Blcvjk_1J_A

**Comment by tsujan** [comment]
I don't see a bug here.

(1) If you mean those shortcuts can be moved to Trash, yes, they can but they will be recreated when pcmanfm-qt starts again.

(2) If you mean those backslashes inside Trash, that's a mystery and, as you know, it doesn't happen here.

(3) But if you mean the the positions aren't preserved after deleting, that happens with all Desktop icons. We remove custom positions after a file is deleted from Desktop (in `DesktopWindow::onRowsAboutToBeRemoved`) because if we didn't, we would have to answer these questions: (1) How many deleted positions should we remember? (3) When should we forget those virtual positions? (3) What if a real file is put in one of those positions? Should we still preserve the position in case the deleted file is restored?. In short, remembering the positions of deleted files would create complications.

The real question is why the positions are remembered  in your "good" video. I should think about it (although I think I knew that answer before).

**Comment by agaida** [comment]
hmm - i would expect maybe the the the pcmanfm-qt would accept that  i deleted the icons for a reason and reflect it in the settings - really, as a windows- or kde- or $somewhat-user i would do :P

**Comment by tsujan** [comment]
> i would expect maybe the the the pcmanfm-qt would accept that i deleted the icons for a reason and reflect it in the settings 

"Reason" is a human concept; fortunately, scientists haven't succeeded in reducing it to 0 and 1 :D 

We should either forget about deleted positions (as is done currently) or remember all of them and forget them only on exiting or better, on starting. The latter is quite possible and I'll experiment with it. Good idea!

But let me first see why those damn positions aren't forgotten in your "good" video. I'm sure I knew it...

**Comment by tsujan** [comment]
I reopened it because it contained a feature that may be implemented.

**Comment by agaida** [comment]
kwin?

**Comment by tsujan** [comment]
> kwin?

?

**Comment by agaida** [comment]
Idea: start with the simple things we might need before the release

**Comment by tsujan** [comment]
I can't do anything with deadlines ;) One of my personality flaws.

**Comment by agaida** [comment]
https://youtu.be/I6KjuJkb9gc - i guess it is a regression

**Comment by tsujan** [comment]
Please open a feature request for that! But first, you'll have to find an understandable title for it.

**Comment by tsujan** [comment]
OK, update:

It's very easy to remember "dead positions", so that if the file is restored, it'll be put in its previous position. All dead positions should be removed when or before the next session starts (we can't have dead positions forever). However, if cleaning is done at startup, there will be a considerable delay (a long delay if the previous session was continued for weeks and many sticky files were deleted -- I checked with 100 files and saw a delay) and we don't want that. The same could happen at the session end; the delay could be annoying.

I checked KDE; it doesn't have this property: custom positions aren't remembered after deletion, maybe for the same reason that I explained above. I think this can be closed.

But KDE does preserve relative positions of dragged desktop items. So, I'll open a feature request for that.

**Comment by tsujan** [comment]
Opened https://github.com/lxqt/pcmanfm-qt/issues/821

**Comment by agaida** [comment]
right now it works just fine - cool

**Comment by tsujan** [comment]
You mean https://github.com/lxqt/pcmanfm-qt/issues/821. Yes, it should have been made that way from start. Good that you mentioned it; previously, I thought in terms of drag cursor image and wanted to look into Qt source to know how it's drawn but the solution was much easier.

**Comment by agaida** [comment]
@tsujan - is #821 ready?

**Comment by tsujan** [comment]
@agaida Yes, https://github.com/lxqt/pcmanfm-qt/pull/823 is ready.

**Comment by tsujan** [comment]
In short:

Remembering the positions of deleted desktop items is possible but not when we want to have a lightweight file manager.
