### ISSUE TITLE
Not all mouse interactions are passed to the window manager

### ISSUE THREAD

**Issue by dwrl** [lxqt/pcmanfm-qt#928]
Mouse button's 6 and 7 aren't passed onto the window manager.

In desktopwindow.cpp, lines 1410 - 1426, it seems only buttons 1 to 3 are handled, excluding for example my scrollwheel (buttons 4 to 7), which I use to switch desktops (on the window manager side of things).

I know the button handling in  QT is a bit... [special](https://doc.qt.io/qt-5/qt.html#MouseButton-enum), but it would be really great to support all buttons.

The problem I see is how QT seemingly doesn't count the mousewheel as a button, while X seemingly does, so a simple for loop through the enum wouldn't be enough, and somehow one needs to guess how the buttons are mapped (e.g. is Qt::BackButton now button 4, 6 or 8, depending on the occurrence and type of mousewheel...? Does Qt::ExtraButton4 come before or after...?).

Maybe above-mentioned problem is no problem at all or already solved (I'm not into X stuff, but this must be something that already needed solving).

On solution (cheap in terms of logic, probably a bit of work implementing) would be to have the user press the buttons he want to be delegated during configuration, as is done with keyboard shortcuts.

**Comment by tsujan** [comment]
Please be more specific and, at least, fill in the template. No one can do anything with this report.

Desktop isn't scrollable.

**Comment by dwrl** [comment]
Done.

**Comment by tsujan** [comment]
Reopened to be completely read.

**Comment by tsujan** [comment]
I explain it with 2 over-simplified examples.

KDE has KWin. It also has a "Plasma desktop". Turning the mouse wheel on Plasma desktop makes KWin rotate its desktop cube if that's enabled in KDE's systemsettings5 -- probably by using a signal-slot connection (I haven't read the KDE codes).

KWin can also be used under LXQt, as I'm using it right now, but KWin isn't connected to any signal from LXQt's desktop. So, nothing happens when I use the mouse wheel on LXQt's desktop.

On the other hand, Compiz-reloaded can also be used under LXQt, as I use it once in a while (because I enjoy its fancy effects). Compiz-reloaded "knows" that what pcmanfm-qt draws on the screen is the desktop (through X11). It also "knows" when the mouse wheel is turned and whether it's turned when the cursor is immediately over the desktop. Therefore, contrary to KWin, Compiz-reloaded rotates its desktop cube.

All of this is related to WM and out of pcmanfm--qt's control.

**Comment by dwrl** [comment]
I guess we misunderstood each other here.

Coming from fvwm, fluxbox and the like, I'm used to be able to bind window manager functions to mouse buttons by their xlib/xcb names, so I'm also used to simply think of wheel up, down, left as right and buttons 4 to 7.

Since this didn't work with the pcmanfm-qt desktop, I checked and saw that in 'desktopwindow.cpp' in the function 'forwardMouseEventToRoot' only passes buttons 2 and 3, e.g. middle and left, and asked buttons 4-7 to be added.

_What I didn't realize_ was that QT doesn't treat the wheel that way, so of course from a QT developers perspective my request made absolute no sense, since on the QT side we are talking about completely different things... :P
Sorry for that.


I created a [repo here](https://github.com/dwrl/pcmanfm-qt) and implemented the changes I suggested, e.g.:
- User can optionally also have mouse wheel events passed through the desktop to the root window, for his window manager to catch and interpret.
- This option is user configurable in the desktop settings dialog, disabled by default, like the option to pass mouse buttons to the root window.

**Comment by tsujan** [comment]
The goal was switching desktop by wheeling up/down. Unless I'm mistaken about the goal, theoretically, an X11 WM is able to achieve it without any change to pcmanfm-qt -- Compiz was a proof. So, I don't think there was a misunderstanding.

**Comment by dwrl** [comment]
I think Compiz doing something isn't exactly representative of most other window managers, which in practice need the events passed to the root window (e.g. fluxbox, openbox, fvwm etc).

For exactly this reason there already is the 'forwardMouseEventToRoot' function in desktopwindow.cpp, to accommodate those kind window managers and enable them to show their menu.

I simply extended this existing functionality to optionally handle the scroll wheel to, if the user so chooses.
Since I already implemented this, and the changes won't affect users not using the feature, nor do really increase code complexity, [would you please have a look](https://github.com/dwrl/pcmanfm-qt)?

It's not that I just throw a request to have something implemented, the work is already done, it just needs to be sighted.

**Comment by tsujan** [comment]
> would you please have a look?

Personally, I don't like complicating the current X11 code just for specific WMs, whether they do something in a similar way or not. Wayland is the future.

However, since you've written your code, you could make a PR, so that we (you, me or other devs) could discuss it there. Just by a glance:

(1) In lines 1591 and 1592, returning `true` is skipped but it's needed.
(2) Don't replace `showWmMenu_` with `passButtonsToRoot_`; that isn't backward compatible.
(3) Please follow the current code style (change `} else` and `if (`).
