### ISSUE TITLE
folder copy via mtp not supported

### ISSUE THREAD

**Issue by marpagno** [lxqt/pcmanfm-qt#959]
I'm using the pcmanfm-qt shipped with lubuntu 19.04, system updated 

I notice that copying from my phone (Android 7, also tested on android 4) to the desktop via drag and drop doesn't work any more: "copy here" popup appears, but nothing else happens (I choose copy, the file isn't copied).

workaround: select the file, explicitly "copy", click on desktop, explicitly "paste"

however also this workaround seems not to work for folders (I'm trying to download the whole DCIM folder on my phone): even if I do a ^C or a right-mouse click+"copy" on the folder in pcmanfm-qt , then select the desktop folder and  paste, only an empty folder is created.

Of course, it's always possible to select all the files on the phone directory and copy them - but it's harder to explain to my daugther, who used previously pcmanfm (gtk) without any trouble.

###
connect a android phone via usb cable, 
open its archive in pcmanfmqt, 
click on a folder (like DCIM), 
drag and drop to the desktop 
choose copy here from popup
nothing happens

**Comment by marpagno** [comment]
by the way, pcmafm-qy version is 0.14.1

**Comment by agaida** [comment]
already fixed. https://github.com/lxqt/libfm-qt/pull/386

Please read the issue template next time carefully - there is nothing we can do, it's a not so simple downstream thing. For Lubuntu bugs please use launchpad instead of upstream - we don't know if it is possible to port back the existing fix, thats up to the lubuntu team.
