### ISSUE TITLE
Full (desktop) file names aren't shown on Desktop

### ISSUE THREAD

**Issue by Katarn** [lxqt/pcmanfm-qt#979]
##### Expected Behavior
All icons on desktop must use application settings. I are talking about these settings "Always show the full file names".

##### Current Behavior
Application settings are not used. Moreover, it seems hardcoded. For example, all icons always have just one line of file name. While in Explorer mode, up to three lines are displayed.

**Comment by tsujan** [comment]
As for "Always show the full file names", yes, there's an inconsistency that should be fixed (hence changing the title).

> For example, all icons always have just one line of file name.

That's not the case.

**Comment by Katarn** [comment]
> That's not the case.

But will it be customizable? I have half of the icons have a cropped name.

**Comment by tsujan** [comment]
> I have half of the icons have a cropped name.

Not reproducible. When you encounter an issue, you should provide a step-by-step way of reproducing it (the template is there for that reason). And please don't mix two issues in one and the same report!

**Comment by tsujan** [comment]
This will be fixed by https://github.com/lxqt/pcmanfm-qt/pull/981

Now, a little mind reading (considering [your other report](https://github.com/lxqt/pcmanfm-qt/issues/980)):

You misunderstood the meaning of "Always show the full file names". It's for desktop entries and has nothing to do with showing *the whole names* when they're too long (full name ≠ whole name -- whole names are shown in bold on tooltips in the latest git pcmanfm-qt).

Maybe a better tooltip could be added to that option but the above-mentioned misunderstanding hadn't happened before.
