### ISSUE TITLE
Can't copy recursive into a open pcmanfm-qt window from a samba share by drag and drop

### ISSUE THREAD

**Issue by Coresam** [lxqt/pcmanfm-qt#995]
Hello,

I use Lubuntu in Version 19.04 (encrypted HD) with the default LXQt/PCManFM-qt 0.14.1 Version on this distro.

I like to copy a folder with some files inside by drag and drop or copy/paste from a sambaservers share to a local folder. But every time only the parent folder will be copied. The files inside the folder are not. If I change into the parent folder on the sambaserver I can select the files and copy them into the local folder without any problems. So I think, the permissions on the sambaserver are right.

More Tests after that malfunction:
I install on the same Lubuntu System with the untouched sambaserver the filemanager Nautilus and Thunar and it shows, that I can copy folders recursiv from the sambaserver into local folders they are opened in Thunar- or Nautilus-Windows. Also if I drag and drop the samba shares with PCmanFM-qt into a Thunar- or Nautilus-Window it works fine. Only if I drag and drop from Thunar-, Nautilus or PCmanFM-qt into a PCmanFM-qt Window every times only the parent folder without files was copied. So I think the "Input" of a PCmanFM-qt Window is the problem. Extremely ugly is, that also the Desktop is a "PCmanFM-qt Wondow"...

In advance, thanks a lot for your nice work!

**Comment by agaida** [comment]
Hint: We made a fine form to be filled out - we don't have much time to read prosa, here it is again:
```
<!--- Provide a general summary of the issue in the title above. You       --->
<!--- should not delete relevant sections and/or questions in your report  --->

<!--- BEFORE FILLING OUT THIS REPORT FORM:                                 --->
<!--- Dear users of stable and LTS (long term service) distributions:      --->
<!--- Please do NOT file bugs against old (dead) versions but use your     --->
<!--- distribution bugtracker instead. This is esp. true for Ubuntu LTS.   --->

##### Expected Behavior
<!--- If you're describing a bug, tell us what should happen                -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

##### Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected    --->
<!--- behaviour. If suggesting a change/improvement, explain the difference -->
<!--- from current behavior (a screenshot might help)                      --->

##### Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug,                --->
<!--- or ideas how to implement the addition or change                     --->

##### Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to  --->
<!--- reproduce this bug. Include code to reproduce, if relevant           --->
1. 
2. 
3. 
4. 

##### Context
<!--- How has this issue affected you? What are you trying to accomplish?  --->
<!--- Providing context helps us come up with a solution that is most      --->
<!--- useful in the real world                                             --->

##### System Information
<!--- Include as many relevant details about the system you experienced    --->
<!--- the bug in                                                           --->
* Distribution & Version: 
* Kernel: 
* Qt Version: 
* libfm-qt Version:
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 
```
Maybe we should be more strict and harsh: No bug processing without filled out form - and limit Ubuntu users a bit more. Might sound unkind, but please dear lubuntu users: USE LAUNCHPAD!!!
Please let the Lubuntu Maintainers triage the bug and if the bug really exists and is reproducible in latest git - let them file a bug. We as upstream will not install and test Lubuntu, not our job. Thanks.

**Comment by tsujan** [comment]
In addition to what @agaida correctly said:

Before opening an issue, do please take a look at recently closed issues! The problem you tried to describe was reported and fixed in the git source months ago.

**Comment by agaida** [comment]
```
libfm-qt (0.14.1-9) unstable; urgency=medium                                                                                                                

  * Added upstream patch workaround-missed-file-monitoring.patch
    (Closes: #926803)
  * Added two new symbols - internal use only

 -- Alf Gaida <agaida@siduction.org>  Sat, 08 Jun 2019 16:39:11 +0200

libfm-qt (0.14.1-8) unstable; urgency=medium

  * Removed the wrongly introduced build dependency on lxqt-qtplugin

 -- Alf Gaida <agaida@siduction.org>  Sat, 27 Apr 2019 18:40:25 +0200

libfm-qt (0.14.1-7) unstable; urgency=medium

  * Workaround for GLib's recursive moving error (Closes: #927708)

 -- Alf Gaida <agaida@siduction.org>  Sat, 27 Apr 2019 10:50:16 +0200

libfm-qt (0.14.1-6) unstable; urgency=medium

  * Fixed ignored creation-deletion sequences (Closes: #927707)

 -- Alf Gaida <agaida@siduction.org>  Sun, 21 Apr 2019 20:50:23 +0200

libfm-qt (0.14.1-5) unstable; urgency=medium

  * Fixed license for vfs-search.c and vfs-menu.c - was forgotten upstream.
  * Fixed d/copyright that way.

 -- Alf Gaida <agaida@siduction.org>  Thu, 18 Apr 2019 20:52:30 +0200

libfm-qt (0.14.1-4) unstable; urgency=medium

  * Fix recursive copy to smb shares (and possible other remote filesystems)
    (Closes: #926626)

 -- Alf Gaida <agaida@siduction.org>  Mon, 08 Apr 2019 19:03:43 +0200
```
That's happend if a derivative try to be special and far more clever than both upstreams. Possible solution: 
* Use a sane distribution
* Try to convince them to do their damn work.

**Comment by wxl** [comment]
[The fix is in Eoan](https://phab.lubuntu.me/source/libfm-qt/browse/ubuntu%252Feoan/debian/patches/fix-smb-recursive-copy.patch) ([compare to Debian](https://salsa.debian.org/lxqt-team/libfm-qt/commit/93fea37706ebd43b71c700bc57b1958efa457806)). Has been for a while. That's set to be released in October.

And yes, PLEASE make that template required, or at least have language to suggest as such.

**Comment by agaida** [comment]
@wxl - i filed those bugs in debian as RC because it was changes in glib that leads to that behaviour - in release time these things worked fine :) - ok, mostly - the monitor thing was new. And it should be possible to put some of these things into an already released thing, don't know the way Ubuntu can do this, proposed-updates i guess. 

RE template: We can't make it required, it's just a text - but if you have any idea how to improve it - we would be glad to merge PRs, no joke - the templates help to save a lot of time and make the life of all involved parties far more easy. We can't force it, the only thing is that we don't process any bug without filled out form and leave a more or less nice comment when closing for that reason.

**Comment by Coresam** [comment]
Hello Guys,

I am sorry about the way I descriped that issue. Next time, I will use your form, I promisse!

Now I have to learn a lot more about how the different project teams work and how a bugfix gets into the releases of the different distributions.... it becomes a long night...

Thanks a lot!

**Comment by agaida** [comment]
Maybe i can help here, it is not a rocket science:
* we (Upstream) develop something, at some point we think that we should make a release
* $distribution (Downstream) pick up the released things and make something user installable from (packages)
* some distributions use packaging from another distribution (changed or unchanged), so called derivatives. The distribution where the packages are taken from is the upstream for the derivative (downstream)

And that's it. This result in some problems - downstreams can change things or introduces own things. And most downstreams only make packages for releases - and patch them if needed. That's perfectly fine, but in the very most cases we don't know what $distribution does, there are to many of them. So the best way to report bugs is to report it to the used distribution. Second: If one think, that one was running into an upstream bug, one has to build the whole thing from current upstream sources and see if the bug still exists - if so: File an upstream bug :smile:, much work i would suggest to leave that part to the distribution maintainers. Same for possible fixes, they do know best, if there is a chance to fix things for an already released thing.

**Comment by Coresam** [comment]
Wow, exactly what I am searching for!

Thank you.

Maybe, for me a science of a small rocket?! :)

**Comment by wxl** [comment]
@agaida ultimately Ubuntu and Debian do things similarly. I guess that should come as no surprise.

I'll do something to the template. I think maybe visually cleaning things up (read: less words) and saying something like "refusing to complete this form will result in your issue being ignored" would have a significant impact. 

@coresam actually the number one thing you can learn from this: get in touch with the Lubuntu Team if you have any issues with Lubuntu. There are email lists, forums, real time chat, social media— no shortage of options. 

You can always file a bug report with `ubuntu-bug PACKAGE` but the first rule of bug reporting is to see if the bug has already been filed (or fixed before it could even get filed). You can search on Launchpad, but in the event it's fixed with no bug report (as is the case here), you'd have to test the development version.

Like I said, maybe it would be easier just to ask.

**Comment by agaida** [comment]
@wxl  - we have only security and backports - in case backports == proposed-updates you are right.

**Comment by tsujan** [comment]
> saying something like "refusing to complete this form will result in your issue being ignored" would have a significant impact.

I agree. We shouldn't frighten users. We all know what a bad report is and don't waste our time with it. Encouragement is a much better approach.

**Comment by tsujan** [comment]
Oh, I mean I agree if you meant that we should NOT say that ;) Less words and a template without threatening ;)
